-- ============================================================
-- Desi Dhamaka — menu seed for South Plainfield
-- Source: https://desidhamakanj.net/south-plainfield/menu/
-- Categories: 20 · Items: 377
-- Idempotent: re-running will not duplicate categories or items.
-- ============================================================

BEGIN;

-- Categories
INSERT INTO public.menu_categories (name, slug, image, display_order, status, location_id)
VALUES
  ('Soups', 'soups', NULL, 0, 'active', 'south-plainfield'),
  ('Vegetarian Appetizers', 'vegetarian-appetizers', NULL, 1, 'active', 'south-plainfield'),
  ('Non-Vegetarian Appetizers', 'non-vegetarian-appetizers', NULL, 2, 'active', 'south-plainfield'),
  ('Breakfast', 'breakfast', NULL, 3, 'active', 'south-plainfield'),
  ('Kebab & Tandooris', 'kebab-tandooris', NULL, 4, 'active', 'south-plainfield'),
  ('Naans & Breads', 'naans-breads', NULL, 5, 'active', 'south-plainfield'),
  ('Vegetarian Entrees', 'vegetarian-entrees', NULL, 6, 'active', 'south-plainfield'),
  ('Non-Vegetarian Entrees', 'non-vegetarian-entrees', NULL, 7, 'active', 'south-plainfield'),
  ('Vegetarian Rice & Biryani', 'vegetarian-rice-biryani', NULL, 8, 'active', 'south-plainfield'),
  ('Non-Veg Biryani', 'non-veg-biryani', NULL, 9, 'active', 'south-plainfield'),
  ('DD Special Mandi', 'dd-special-mandi', NULL, 10, 'active', 'south-plainfield'),
  ('DD Specials', 'dd-specials', NULL, 11, 'active', 'south-plainfield'),
  ('DD Family Packs', 'dd-family-packs', NULL, 12, 'active', 'south-plainfield'),
  ('Indo Chinese', 'indo-chinese', NULL, 13, 'active', 'south-plainfield'),
  ('Snacks', 'snacks', NULL, 14, 'active', 'south-plainfield'),
  ('Chai & Coffee', 'chai-coffee', NULL, 15, 'active', 'south-plainfield'),
  ('Soft Drinks', 'soft-drinks', NULL, 16, 'active', 'south-plainfield'),
  ('Kids Menu', 'kids-menu', NULL, 17, 'active', 'south-plainfield'),
  ('Desserts', 'desserts', NULL, 18, 'active', 'south-plainfield'),
  ('Thali & Cooker Pulav', 'thali-cooker-pulav', NULL, 19, 'active', 'south-plainfield')
ON CONFLICT (location_id, slug) DO NOTHING;

-- Menu items (category resolved by slug, scoped to location)
WITH cat AS (
  SELECT id, slug FROM public.menu_categories WHERE location_id = 'south-plainfield'
)
INSERT INTO public.menu_items (category_id, name, description, price, image, veg, popular, chef_special, spice_level, status, display_order, location_id)
SELECT c.id, v.name, v.description, v.price, v.image, v.veg, v.popular, v.chef_special, v.spice_level, v.status, v.display_order, v.location_id
FROM (VALUES
  ('soups', 'Veg Sweet Corn Soup', 'A comforting blend of sweet corn, fresh vegetables, and rich broth — creamy, mildly seasoned, and soul-soothing in every spoonful.', 8.31, NULL, TRUE, FALSE, FALSE, NULL, 'active', 0, 'south-plainfield'),
  ('soups', 'Chicken Sweet Corn Soup', 'Tender chicken and golden corn kernels simmered in a smooth, savory broth — the perfect balance of comfort and flavor.', 8.31, NULL, FALSE, FALSE, FALSE, NULL, 'active', 1, 'south-plainfield'),
  ('soups', 'Veg Manchow Soup', 'A hot and spicy delight packed with crunchy vegetables and zesty flavors — finished with crispy noodles for that ultimate kick.', 8.31, NULL, TRUE, FALSE, FALSE, 2, 'active', 2, 'south-plainfield'),
  ('soups', 'Chicken Manchow Soup', 'A spicy, tangy Indo-Chinese favorite — loaded with shredded chicken, crunchy veggies, and topped with crispy noodles for that perfect crunch.', 8.31, NULL, FALSE, FALSE, FALSE, 2, 'active', 3, 'south-plainfield'),
  ('soups', 'Veg Hot & Sour Soup', 'A bold mix of tangy, spicy, and savory — packed with fresh vegetables and exotic Asian flavors to awaken your taste buds.', 8.31, NULL, TRUE, FALSE, FALSE, 2, 'active', 4, 'south-plainfield'),
  ('soups', 'Chicken Hot & Sour Soup', 'A fiery, tangy soup bursting with bold Indo-Chinese flavors — shredded chicken, veggies, and spice that warms you up instantly.', 8.31, NULL, FALSE, FALSE, FALSE, 2, 'active', 5, 'south-plainfield'),
  ('soups', 'Natu Kodi Soup', 'Authentic country chicken slow-cooked with bold spices and herbs — a traditional South Indian remedy that''s as flavorful as it is hearty.', 9.35, NULL, FALSE, FALSE, FALSE, NULL, 'active', 6, 'south-plainfield'),
  ('soups', 'Goat Paya (Aattukal) Soup', 'Traditional bone broth made from slow-cooked goat trotters — rich, nourishing, and bursting with authentic homemade flavor.', 9.35, NULL, FALSE, FALSE, FALSE, NULL, 'active', 7, 'south-plainfield'),
  ('vegetarian-appetizers', 'Punjabi Samosa', 'Golden, flaky samosas filled with spiced potato and peas — an all-time favorite Indian street snack.', 9.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 0, 'south-plainfield'),
  ('vegetarian-appetizers', 'Paneer Pepper Fry', 'Soft paneer cubes tossed with black pepper, curry leaves, and aromatic masalas — fiery and flavorful in every bite.', 14.55, NULL, TRUE, FALSE, FALSE, 2, 'active', 1, 'south-plainfield'),
  ('vegetarian-appetizers', 'Mushroom Pepper Fry', 'Tender mushrooms tossed with black pepper, onions, and curry leaves — a spicy, earthy classic.', 13.51, NULL, TRUE, FALSE, FALSE, 2, 'active', 2, 'south-plainfield'),
  ('vegetarian-appetizers', 'Baby Corn Pepper Fry', 'Tender baby corn stir-fried with cracked pepper and spices — crisp, spicy, and full of flavor.', 13.51, NULL, TRUE, FALSE, FALSE, 2, 'active', 3, 'south-plainfield'),
  ('vegetarian-appetizers', 'Gobi Pepper Fry', 'Cauliflower florets roasted with crushed pepper and curry leaves — a spicy, earthy flavor explosion.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 4, 'south-plainfield'),
  ('vegetarian-appetizers', 'Corn Masala Fry', 'Crispy golden corn sautéed with spicy masala, onions, and curry leaves — the perfect crunchy starter with a desi twist.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 5, 'south-plainfield'),
  ('vegetarian-appetizers', 'Gobi 65', 'Crispy South Indian-style cauliflower fry seasoned with aromatic spices — crunchy, spicy, and bursting with flavor.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 6, 'south-plainfield'),
  ('vegetarian-appetizers', 'Hyderabad Paneer 65', 'Signature Hyderabadi-style paneer fry — bold, spicy, and bursting with authentic South Indian flavors.', 14.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 7, 'south-plainfield'),
  ('vegetarian-appetizers', 'Onion Pakoda', 'Golden-fried onion fritters seasoned with herbs and gram flour — crispy, aromatic, and perfect for any mood.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 8, 'south-plainfield'),
  ('vegetarian-appetizers', 'Spinach Pakoda', 'Crispy spinach fritters seasoned with aromatic spices — light, crunchy, and irresistibly tasty.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 9, 'south-plainfield'),
  ('vegetarian-appetizers', 'Cashew Pakoda', 'Crunchy cashew fritters fried to perfection — rich, nutty, and irresistibly crisp.', 14.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 10, 'south-plainfield'),
  ('vegetarian-appetizers', 'Chilli Baby Corn', 'Crispy baby corn tossed in spicy chilli sauce with onions and bell peppers — hot, tangy, and addictive.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 11, 'south-plainfield'),
  ('vegetarian-appetizers', 'Chilli Gobi', 'Crispy cauliflower florets coated in fiery chilli sauce — bold, tangy, and downright addictive.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 12, 'south-plainfield'),
  ('vegetarian-appetizers', 'Chilli Mushroom', 'Juicy mushrooms tossed in hot chilli sauce with peppers and onions — tangy, spicy, and utterly satisfying.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 13, 'south-plainfield'),
  ('vegetarian-appetizers', 'Chilli Lotus Root', 'Crunchy lotus root rings tossed in hot and tangy chilli sauce — a unique twist for spice lovers.', 14.55, NULL, TRUE, FALSE, FALSE, 2, 'active', 14, 'south-plainfield'),
  ('vegetarian-appetizers', 'Chilli Paneer', 'Classic Indo-Chinese delight — soft paneer chunks coated in spicy, tangy chilli sauce and sautéed to perfection.', 14.55, NULL, TRUE, FALSE, FALSE, 2, 'active', 15, 'south-plainfield'),
  ('vegetarian-appetizers', 'Veg Manchurian', 'Crispy veggie balls tossed in tangy, spicy Indo-Chinese sauce — a fusion favorite that never fails to impress.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 16, 'south-plainfield'),
  ('vegetarian-appetizers', 'Baby Corn Manchurian', 'Golden-fried baby corn tossed in zesty Indo-Chinese sauce — crunchy, tangy, and full of flavor.', 13.51, NULL, TRUE, FALSE, FALSE, NULL, 'active', 17, 'south-plainfield'),
  ('vegetarian-appetizers', 'Lotus Root Manchurian', 'Crispy lotus root tossed in bold Manchurian sauce — crunchy, saucy, and perfectly balanced.', 14.55, NULL, TRUE, FALSE, FALSE, NULL, 'active', 18, 'south-plainfield'),
  ('vegetarian-appetizers', 'Gobi Manchurian', 'Crispy cauliflower florets wok-tossed in flavorful Manchurian sauce — spicy, saucy, and packed with crunch.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 19, 'south-plainfield'),
  ('vegetarian-appetizers', 'Paneer Manchurian', 'Soft paneer cubes wok-tossed in flavorful Manchurian sauce — spicy, saucy, and crowd-favorite.', 14.55, NULL, TRUE, FALSE, FALSE, 2, 'active', 20, 'south-plainfield'),
  ('vegetarian-appetizers', 'Mushroom Manchurian', 'Crispy mushrooms coated in spicy, tangy Manchurian sauce — a perfect Indo-Chinese favorite.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 21, 'south-plainfield'),
  ('vegetarian-appetizers', 'Paneer 555', 'A chef''s special fusion of crispy paneer and spicy seasoning — bold, flavorful, and perfectly addictive.', 14.99, NULL, TRUE, FALSE, TRUE, 2, 'active', 22, 'south-plainfield'),
  ('vegetarian-appetizers', 'Gobi 555', 'Crispy cauliflower tossed in fiery seasoning — a chef''s special creation that''s bold, spicy, and utterly addictive.', 14.55, NULL, TRUE, FALSE, TRUE, 2, 'active', 23, 'south-plainfield'),
  ('vegetarian-appetizers', 'Baby Corn 555', 'Crispy fried baby corn tossed in special 555 masala — spicy, crunchy, and full of flavor.', 14.55, NULL, TRUE, FALSE, TRUE, 2, 'active', 24, 'south-plainfield'),
  ('vegetarian-appetizers', 'Mushroom 555', 'Crispy mushrooms tossed in signature spicy seasoning — fiery, bold, and bursting with umami.', 14.55, NULL, TRUE, FALSE, TRUE, 2, 'active', 25, 'south-plainfield'),
  ('vegetarian-appetizers', 'Vegetable Bullets', 'Crispy veggie bites packed with flavor and spices — the perfect crunchy snack for spice lovers.', 14.55, NULL, TRUE, FALSE, FALSE, NULL, 'active', 26, 'south-plainfield'),
  ('vegetarian-appetizers', 'Paneer Burji Dry', 'Scrambled paneer sautéed with onions, spices, and herbs — dry, flavorful, and perfectly spiced for every craving.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 27, 'south-plainfield'),
  ('vegetarian-appetizers', 'Paneer Majestic', 'A royal appetizer made with golden-fried paneer tossed in creamy, spiced yogurt sauce — majestic in every sense.', 15.59, NULL, TRUE, FALSE, TRUE, NULL, 'active', 28, 'south-plainfield'),
  ('vegetarian-appetizers', 'Gobi Majestic', 'Crispy cauliflower tossed in creamy, spiced yogurt sauce — a true majestic treat with a fusion kick.', 14.55, NULL, TRUE, FALSE, TRUE, NULL, 'active', 29, 'south-plainfield'),
  ('vegetarian-appetizers', 'Mushroom Majestic', 'Golden-fried mushrooms coated in smooth, spiced yogurt-based sauce — rich, aromatic, and full of flavor.', 14.55, NULL, TRUE, FALSE, TRUE, NULL, 'active', 30, 'south-plainfield'),
  ('vegetarian-appetizers', 'Baby Corn Majestic', 'Crispy baby corn tossed in a rich, creamy, and mildly spiced majestic sauce — an irresistible Indo-fusion treat.', 14.55, NULL, TRUE, FALSE, TRUE, NULL, 'active', 31, 'south-plainfield'),
  ('vegetarian-appetizers', 'Plantain Bajji with Coconut Dip', 'Golden-fried raw banana fritters served with creamy coconut dip — a crispy, comforting South Indian favorite.', 14.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 32, 'south-plainfield'),
  ('vegetarian-appetizers', 'Chaana Pepper Fry', 'Crispy fried chickpeas tossed with cracked pepper and South Indian spices — bold, crunchy, and irresistibly spiced.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 33, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Ameerpet Egg Fry', 'Street-style masala egg fry loaded with onions, chilies, and signature Ameerpet spice.', 14.55, NULL, FALSE, FALSE, FALSE, NULL, 'active', 0, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Chilli Egg', 'Boiled eggs tossed in a tangy Indo-Chinese chili sauce — a fiery twist on comfort.', 15.59, NULL, FALSE, FALSE, FALSE, 2, 'active', 1, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Chilli Chicken', 'Crispy Indo-Chinese chicken coated in a spicy chili garlic sauce.', 15.59, NULL, FALSE, FALSE, FALSE, 2, 'active', 2, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Chicken 65 Dry', 'Crispy, spicy, and iconic — the original South Indian chicken starter.', 15.59, NULL, FALSE, FALSE, FALSE, 2, 'active', 3, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Chicken Majestic', 'Crispy strips of chicken tossed in a creamy, spicy sauce — majestic indeed!', 15.59, NULL, FALSE, FALSE, TRUE, 2, 'active', 4, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Chicken Pepper Fry', 'Aromatic South-style pepper chicken with roasted curry leaves and black pepper heat.', 15.59, NULL, FALSE, FALSE, FALSE, 2, 'active', 5, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Chicken Manchurian', 'Indo-Chinese fusion favorite — crispy chicken tossed in tangy soy-chili sauce.', 15.59, NULL, FALSE, FALSE, FALSE, 2, 'active', 6, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Hyd Chicken 65 Wet', 'A juicy, saucy twist to the classic Chicken 65 — bursting with Hyderabad spice.', 15.59, NULL, FALSE, FALSE, FALSE, 2, 'active', 7, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Chicken Lollipop', 'Crispy lollipop chicken glazed in spicy sauce — juicy inside, crunchy outside.', 16.63, NULL, FALSE, FALSE, FALSE, 2, 'active', 8, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Hell of Chicken Drums', 'Drumsticks coated in fiery marinade — spicy, smoky, and dangerously addictive.', 17.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 9, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Chicken 555', 'A crowd-favorite spicy dry chicken with crunchy texture and rich masala coating.', 16.63, NULL, FALSE, FALSE, TRUE, 2, 'active', 10, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Kothimeera Chicken', 'Juicy chicken tossed with fresh coriander, chili, and house masala — fresh and zesty.', 16.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 11, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Karivepaaku Kodi', 'Crispy chicken cooked with curry leaf tempering — full of aroma and crunch.', 16.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 12, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Guntur Karampodi Kodi', 'Signature Guntur-style chicken fry dusted with fiery karampodi spice powder.', 16.63, NULL, FALSE, FALSE, FALSE, 2, 'active', 13, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Ginger Chicken', 'Tender chicken bites tossed in a flavorful ginger-garlic masala.', 16.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 14, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Garlic Chicken', 'Soft chicken chunks glazed in garlic sauce — aromatic and satisfying.', 16.63, NULL, FALSE, FALSE, FALSE, NULL, 'active', 15, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Andhra Kodi Vepudu (Bone-In)', 'Traditional spicy chicken roast with bones — rustic, bold, and full of aroma.', 16.63, NULL, FALSE, FALSE, FALSE, 2, 'active', 16, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Andhra Kodi Vepudu (Boneless)', 'Classic Andhra chicken roast cooked to perfection — tender and fiery.', 17.67, NULL, FALSE, FALSE, FALSE, 2, 'active', 17, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Mirapakaya Kodi Vepudu', 'A spicy dry chicken roast infused with green chilies and Andhra-style seasoning.', 16.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 18, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Natu Kodi Roast', 'Traditional country chicken slow-roasted with signature Andhra masalas.', 18.71, NULL, FALSE, FALSE, FALSE, NULL, 'active', 19, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Mutton Ghee Roast (Bone-In)', 'Bone-in mutton slow-roasted with ghee and fiery red masala — a royal treat.', 18.71, NULL, FALSE, FALSE, FALSE, 2, 'active', 20, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Mutton Ghee Roast (Boneless)', 'Succulent mutton roasted in ghee and Mangalorean spices — rich and aromatic.', 20.79, NULL, FALSE, FALSE, FALSE, NULL, 'active', 21, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Gongura Mamsam Fry (Bone-In)', 'Tangy gongura leaves meet spicy mutton — Andhra-style perfection.', 18.71, NULL, FALSE, FALSE, FALSE, 2, 'active', 22, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Gongura Mamsam Fry (Boneless)', 'Tender mutton roasted with gongura (sorrel leaves) — tangy, spicy, and unforgettable.', 20.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 23, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Mutton Sukka (Bone-In)', 'Traditional dry mutton fry with a coarse masala and rustic South flavor.', 18.71, NULL, FALSE, FALSE, FALSE, NULL, 'active', 24, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Mutton Sukka (Boneless)', 'Boneless mutton roasted with coconut and coarse spices — a perfect bar-style starter.', 20.79, NULL, FALSE, FALSE, FALSE, NULL, 'active', 25, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Palnadu Mamsam Roast (Bone-In)', 'Classic Palnadu-style mutton fry — spicy, smoky, and ghee-rich.', 18.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 26, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Palnadu Mamsam Roast (Boneless)', 'Authentic Palnadu-style dry mutton roast with ghee and local masalas.', 20.79, NULL, FALSE, FALSE, FALSE, NULL, 'active', 27, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Mutton Pepper Fry (Bone-In)', 'Mutton roasted with freshly ground pepper and coconut bits — bold and meaty.', 18.71, NULL, FALSE, FALSE, FALSE, 2, 'active', 28, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Mutton Pepper Fry (Boneless)', 'Tender mutton tossed with pepper masala and ghee — spicy, earthy, and rich.', 20.79, NULL, FALSE, FALSE, FALSE, 2, 'active', 29, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Fish 65', 'Golden-fried fish bites tossed in spicy 65 masala — crisp, spicy, and flavorful.', 17.67, NULL, FALSE, FALSE, FALSE, 2, 'active', 30, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Apollo Fish', 'Crispy fish tossed in Indo-Chinese spices — juicy, bold, and full of heat.', 17.67, NULL, FALSE, FALSE, FALSE, NULL, 'active', 31, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Schezwan Chilli Fish', 'Crispy fish in spicy Schezwan sauce — a must-try Indo-Chinese favorite.', 17.67, NULL, FALSE, FALSE, FALSE, 2, 'active', 32, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'DD Spl Cilantro Fish', 'Pan-seared fish flavored with fresh cilantro and South Indian spices.', 17.67, NULL, FALSE, FALSE, TRUE, NULL, 'active', 33, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Gongura Royyala Vepudu', 'Juicy prawns tossed with tangy gongura paste — a Telugu delicacy.', 18.71, NULL, FALSE, FALSE, FALSE, NULL, 'active', 34, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Black Pepper Prawns', 'Prawns stir-fried with cracked pepper and curry leaves — bold and aromatic.', 18.71, NULL, FALSE, FALSE, FALSE, NULL, 'active', 35, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Loose Prawns', 'Lightly battered prawns stir-fried with onions, garlic, and green chilies.', 18.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 36, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Godavari Fish Fry', 'Coastal-style fried fish marinated in tangy masala and shallow-fried to golden perfection.', 21.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 37, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Shrimp Majestic', 'Crispy shrimp tossed in a creamy, spicy Andhra-style sauce.', 18.71, NULL, FALSE, FALSE, TRUE, 2, 'active', 38, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Chilli Shrimp', 'Crispy shrimp tossed in a bold Indo-Chinese chili sauce with peppers.', 18.71, NULL, FALSE, FALSE, FALSE, 2, 'active', 39, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Shrimp Fry', 'Pan-fried shrimp tossed with house spices and curry leaves — coastal perfection.', 18.71, NULL, FALSE, FALSE, FALSE, NULL, 'active', 40, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Pachi Mirchi Kodi Vepudu', 'Andhra-style green chili chicken fry — bold, spicy, and aromatic.', 15.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 41, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Fish Tikka Kebab', 'Tender fish cubes marinated in yogurt and grilled to smoky perfection.', 20.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 42, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Andhra Chilli Chicken', 'Fiery Andhra-style chicken bites tossed in a punchy, peppery sauce.', 15.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 43, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Party Chicken Wings', 'Crispy fried wings tossed in bold desi spices — the ultimate party starter!', 19.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 44, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Mutton Milagu Pirattal (Bone-In)', 'Bone-in mutton roasted with crushed black pepper and curry leaves — pure South Indian spice.', 18.71, NULL, FALSE, FALSE, FALSE, NULL, 'active', 45, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Fish Amritsar', 'Crispy golden fish fillets fried Amritsari-style — crunchy, flaky, and flavorful.', 20.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 46, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Shrimp Koli Wada with Jalapeno Sauce', 'Mumbai-style spiced shrimp fritters served with a zesty jalapeño dip.', 20.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 47, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Sesame Prawn Roast', 'Juicy prawns coated with toasted sesame and spicy masala for a nutty, coastal kick.', 20.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 48, 'south-plainfield'),
  ('non-vegetarian-appetizers', 'Party Chicken Wild Wings', 'Crispy fried wings tossed in bold desi spices — the ultimate party starter!', 19.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 49, 'south-plainfield'),
  ('breakfast', 'Vada', 'Crispy, golden South Indian lentil fritters — crunchy on the outside, soft inside.', 11.43, NULL, TRUE, FALSE, FALSE, NULL, 'active', 0, 'south-plainfield'),
  ('breakfast', 'Idli with Vada (Combo)', 'Soft steamed rice cakes paired with crispy vada — a classic South Indian breakfast combo.', 12.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'south-plainfield'),
  ('breakfast', 'Guntur Ghee Karam Idli', 'Soft idlis topped with spicy Guntur karam and ghee drizzle — simple, spicy, and addictive.', 11.43, NULL, TRUE, FALSE, FALSE, 2, 'active', 2, 'south-plainfield'),
  ('breakfast', 'Sambar Vada', 'Crispy vadas dunked in hot, tangy sambar — a comforting South Indian classic.', 11.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'south-plainfield'),
  ('breakfast', 'Mysore Bonda', 'Fluffy, deep-fried lentil dumplings served with coconut chutney — a Mysore-style favorite.', 11.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 4, 'south-plainfield'),
  ('breakfast', 'Plain Dosa', 'Thin, crispy rice crepe served with sambar and chutney — the timeless South Indian classic.', 10.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 5, 'south-plainfield'),
  ('breakfast', 'Podi Dosa', 'Crispy dosa smeared with spicy gunpowder podi and ghee — bold and aromatic.', 12.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 6, 'south-plainfield'),
  ('breakfast', 'Onion Dosa', 'Crispy dosa layered with chopped onions and green chilies — crunchy, spicy, and flavorful.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 7, 'south-plainfield'),
  ('breakfast', 'Masala Dosa', 'Crispy dosa filled with spiced potato masala — a South Indian breakfast icon.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 8, 'south-plainfield'),
  ('breakfast', 'Mysore Masala Dosa', 'Crispy dosa spread with spicy Mysore chutney and filled with potato masala.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 9, 'south-plainfield'),
  ('breakfast', 'Set Dosa', 'Soft, fluffy dosas served in a set of three with sambar and chutney.', 12.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 10, 'south-plainfield'),
  ('breakfast', 'Ghee Karam Dosa', 'Aromatic dosa brushed with ghee and spicy karam — pure Andhra-style indulgence.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 11, 'south-plainfield'),
  ('breakfast', 'Rayalaseema Karam Dosa', 'Fiery dosa from Rayalaseema with bold chili karam and ghee — not for the faint-hearted!', 12.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 12, 'south-plainfield'),
  ('breakfast', 'Cheese Dosa', 'Crispy dosa filled with melted cheese — a kid-friendly and indulgent twist.', 12.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 13, 'south-plainfield'),
  ('breakfast', 'Egg Dosa', 'Crispy dosa topped with a freshly cracked egg — protein-rich and delicious.', 13.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 14, 'south-plainfield'),
  ('breakfast', 'Cone Dosa', 'A fun cone-shaped crispy dosa — light, crunchy, and perfect for snacking.', 11.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 15, 'south-plainfield'),
  ('breakfast', 'Uthappam Onion Chilli', 'Thick, soft rice pancake topped with onions and green chilies — savory and satisfying.', 12.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 16, 'south-plainfield'),
  ('breakfast', 'Uthappam Mix Veg', 'Fluffy uthappam loaded with colorful mixed vegetables — wholesome and flavorful.', 12.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 17, 'south-plainfield'),
  ('breakfast', 'Chapathi with Veg Kurma', 'Soft whole wheat chapathi served with mild, aromatic vegetable kurma.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 18, 'south-plainfield'),
  ('breakfast', 'Chapathi with Chicken Kurma', 'Flaky chapathi paired with rich, spiced chicken kurma — a satisfying combination.', 14.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 19, 'south-plainfield'),
  ('breakfast', 'Chapathi with Goat Kurma', 'Soft chapathi served with slow-cooked, flavorful goat kurma.', 15.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 20, 'south-plainfield'),
  ('breakfast', 'Parota with Veg Kurma', 'Crispy, layered parotas served with mild vegetable kurma — a perfect vegetarian delight.', 12.47, NULL, TRUE, FALSE, FALSE, NULL, 'active', 21, 'south-plainfield'),
  ('breakfast', 'Parota with Chicken Kurma', 'Layered parotas paired with aromatic chicken kurma — soft, spicy, and comforting.', 14.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 22, 'south-plainfield'),
  ('breakfast', 'Parota with Goat Kurma', 'Flaky parotas served with rich goat kurma — hearty and full of flavor.', 15.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 23, 'south-plainfield'),
  ('breakfast', 'Poori with Bhaji', 'Fluffy deep-fried pooris served with spiced potato bhaji — a classic Indian breakfast.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 24, 'south-plainfield'),
  ('breakfast', 'Poori with Chicken Curry', 'Golden pooris paired with spicy chicken curry — a hearty, satisfying meal.', 14.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 25, 'south-plainfield'),
  ('breakfast', 'Chicken Curry Dosa', 'Crispy dosa filled with flavorful chicken curry — a non-veg twist on a classic.', 15.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 26, 'south-plainfield'),
  ('kebab-tandooris', 'Paneer Tikka Kebab', 'Chargrilled paneer with bell peppers and onions — tandoor magic on a skewer.', 16.63, NULL, TRUE, FALSE, FALSE, NULL, 'active', 0, 'south-plainfield'),
  ('kebab-tandooris', 'Makhmali Paneer Tikka', 'Soft paneer cubes marinated in spiced cream and roasted till melt-in-mouth.', 16.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'south-plainfield'),
  ('kebab-tandooris', 'Chicken Tandoori', 'The classic red-hot tandoori chicken — smoky, spicy, and full of flavor.', 16.63, NULL, FALSE, FALSE, FALSE, 2, 'active', 2, 'south-plainfield'),
  ('kebab-tandooris', 'Seekh Kebab (Chicken)', 'Tender chicken marinated in creamy cashew yogurt mix, grilled to perfection.', 20.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 3, 'south-plainfield'),
  ('kebab-tandooris', 'Mixed Veg Kebab', 'A colorful mix of grilled veggies and paneer tossed with tangy masala.', 17.67, NULL, TRUE, FALSE, FALSE, NULL, 'active', 4, 'south-plainfield'),
  ('kebab-tandooris', 'Chicken Tikka Kebab', 'Classic tandoori delight — boneless chicken infused with rich spices and charred aroma.', 17.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 5, 'south-plainfield'),
  ('kebab-tandooris', 'Tangdi Kebab', 'Juicy drumsticks marinated overnight and flame-grilled for smoky perfection.', 17.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 6, 'south-plainfield'),
  ('kebab-tandooris', 'Chicken Seekh Kebab', 'Minced chicken mixed with herbs and spices, skewered and grilled to perfection.', 17.67, NULL, FALSE, FALSE, FALSE, NULL, 'active', 7, 'south-plainfield'),
  ('kebab-tandooris', 'Chicken Chapli', 'Spicy minced chicken patties shallow-fried — a North Indian street-style favorite.', 17.67, NULL, FALSE, FALSE, FALSE, 2, 'active', 8, 'south-plainfield'),
  ('kebab-tandooris', 'Chicken Hariyali', 'Green-marinated chicken rich in mint and coriander — fresh and flavorful.', 17.67, NULL, FALSE, FALSE, FALSE, NULL, 'active', 9, 'south-plainfield'),
  ('kebab-tandooris', 'Murg Malai Kebab', 'Creamy, velvety chicken kebabs that melt in your mouth with every bite.', 17.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 10, 'south-plainfield'),
  ('kebab-tandooris', 'Tawa Fish', 'Pan-seared fish cooked with house spices for a bold and zesty flavor.', 19.75, NULL, FALSE, FALSE, FALSE, NULL, 'active', 11, 'south-plainfield'),
  ('kebab-tandooris', 'Tandoori Jinga', 'Succulent jumbo prawns grilled with a smoky tandoori punch.', 20.79, NULL, TRUE, FALSE, FALSE, NULL, 'active', 12, 'south-plainfield'),
  ('kebab-tandooris', 'Tandoori Pomfret', 'Whole pomfret marinated in spicy tandoori masala — grilled crisp and flavorful.', 20.79, NULL, TRUE, FALSE, FALSE, 2, 'active', 13, 'south-plainfield'),
  ('kebab-tandooris', 'Pathar Ka Gosht (Goat)', 'Traditional Hyderabadi-style goat slices cooked on hot stone with signature spices.', 21.83, NULL, FALSE, FALSE, FALSE, NULL, 'active', 14, 'south-plainfield'),
  ('kebab-tandooris', 'DD Spl Non Veg Kebab Platter', 'A chef''s special assortment of our best kebabs — juicy, smoky, and irresistible.', 24.95, NULL, TRUE, FALSE, TRUE, NULL, 'active', 15, 'south-plainfield'),
  ('kebab-tandooris', 'Reshmi Kebab Chicken', 'Tender chicken marinated in creamy cashew yogurt mix, grilled to perfection.', 20.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 16, 'south-plainfield'),
  ('naans-breads', 'Roti', 'Soft, homestyle whole wheat bread that pairs beautifully with all curries.', 3.11, NULL, TRUE, FALSE, FALSE, NULL, 'active', 0, 'south-plainfield'),
  ('naans-breads', 'Butter Roti', 'Soft whole wheat roti brushed with creamy butter — the perfect sidekick to any curry.', 3.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'south-plainfield'),
  ('naans-breads', 'Plain Naan', 'Classic tandoor-baked naan — soft, light, and perfect with every bite of gravy.', 3.11, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'south-plainfield'),
  ('naans-breads', 'Butter Naan', 'Tandoor-baked, golden naan slathered in melted butter — a crowd favorite!', 4.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'south-plainfield'),
  ('naans-breads', 'Garlic Naan', 'Fluffy naan roasted with fresh garlic and butter — pure aroma therapy for food lovers.', 4.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 4, 'south-plainfield'),
  ('naans-breads', 'Chilli Garlic Naan', 'Spicy and flavorful naan brushed with garlic butter and green chili — for the bold palate.', 4.15, NULL, TRUE, FALSE, FALSE, 2, 'active', 5, 'south-plainfield'),
  ('naans-breads', 'Cheese Naan', 'Melted cheese tucked inside soft naan — indulgence in every bite.', 4.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 6, 'south-plainfield'),
  ('naans-breads', 'Chilli Cheese Naan', 'A cheesy naan with a hint of heat — a delicious Indo-fusion twist.', 4.15, NULL, TRUE, FALSE, FALSE, 2, 'active', 7, 'south-plainfield'),
  ('naans-breads', 'Peshwari Naan', 'Sweet and nutty naan filled with coconut and dry fruits — a royal treat.', 4.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 8, 'south-plainfield'),
  ('naans-breads', 'Onion Kulcha', 'Stuffed with caramelized onions and spices — soft, aromatic, and addictive.', 4.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 9, 'south-plainfield'),
  ('naans-breads', 'Lachha Paratha', 'Buttery, multi-layered paratha that''s crisp, rich, and oh-so-satisfying.', 5.19, NULL, TRUE, FALSE, FALSE, NULL, 'active', 10, 'south-plainfield'),
  ('naans-breads', 'Malabar Paratha', 'Flaky, layered paratha with crisp edges and soft layers — Kerala-style indulgence.', 5.19, NULL, TRUE, FALSE, FALSE, NULL, 'active', 11, 'south-plainfield'),
  ('naans-breads', 'Bread Basket', 'An assorted mix of our best breads — naan, roti, paratha — a must for sharing!', 16.63, NULL, TRUE, FALSE, FALSE, NULL, 'active', 12, 'south-plainfield'),
  ('vegetarian-entrees', 'Dal Tadka', 'Yellow lentils tempered with ghee, garlic, and cumin — simple, comforting, and loaded with homestyle flavor.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 0, 'south-plainfield'),
  ('vegetarian-entrees', 'Tomato Dal', 'Lentils simmered with tangy tomatoes and tempered with garlic and mustard seeds — simple yet full of flavor.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'south-plainfield'),
  ('vegetarian-entrees', 'Mango Dal', 'A tangy South Indian-style lentil curry with raw mango — unique, comforting, and perfectly balanced.', 13.51, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'south-plainfield'),
  ('vegetarian-entrees', 'Palak Dal', 'Lentils simmered with fresh spinach and garlic tempering — simple, healthy, and home-style comfort.', 13.51, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'south-plainfield'),
  ('vegetarian-entrees', 'Dal Makhani', 'Slow-cooked black lentils simmered overnight in butter and cream — smooth, smoky, and irresistibly rich.', 13.51, NULL, TRUE, FALSE, FALSE, NULL, 'active', 4, 'south-plainfield'),
  ('vegetarian-entrees', 'Shahi Paneer', 'Royal North Indian curry with paneer cooked in cashew-cream sauce — mild, creamy, and full of regal flavor.', 14.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 5, 'south-plainfield'),
  ('vegetarian-entrees', 'Chana Saag', 'Protein-rich chickpeas cooked in creamy spinach gravy — hearty, healthy, and delicious.', 14.55, NULL, TRUE, FALSE, FALSE, NULL, 'active', 6, 'south-plainfield'),
  ('vegetarian-entrees', 'Bendi Masala', 'Okra sautéed with onions, tomatoes, and Indian spices — flavorful, homestyle, and perfectly spiced.', 14.55, NULL, TRUE, FALSE, FALSE, NULL, 'active', 7, 'south-plainfield'),
  ('vegetarian-entrees', 'Bendi Vepudu', 'Crispy fried okra tossed with South Indian spices — dry-fried, flavorful, and the perfect side dish.', 14.55, NULL, TRUE, FALSE, FALSE, NULL, 'active', 8, 'south-plainfield'),
  ('vegetarian-entrees', 'Bendi Pulusu', 'Traditional Andhra-style tangy okra curry cooked in tamarind gravy — bold, flavorful, and deeply satisfying.', 14.55, NULL, TRUE, FALSE, FALSE, NULL, 'active', 9, 'south-plainfield'),
  ('vegetarian-entrees', 'Kadai Bendi', 'Okra cooked with peppers and tomatoes in classic Kadai masala — spicy, fresh, and full of crunch.', 14.55, NULL, TRUE, FALSE, FALSE, 2, 'active', 10, 'south-plainfield'),
  ('vegetarian-entrees', 'Chana Masala', 'Chickpeas cooked in tangy tomato gravy with aromatic North Indian spices — spicy, hearty, and flavorful.', 14.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 11, 'south-plainfield'),
  ('vegetarian-entrees', 'Paneer Burji Gravy', 'Scrambled paneer cooked with spiced onion-tomato gravy — flavorful, rustic, and delicious with naan.', 14.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 12, 'south-plainfield'),
  ('vegetarian-entrees', 'Chettinad Mushroom', 'Mushrooms tossed in spicy, coconut-based Chettinad masala — hot, earthy, and packed with South Indian flavor.', 14.55, NULL, TRUE, FALSE, FALSE, 2, 'active', 13, 'south-plainfield'),
  ('vegetarian-entrees', 'Chettinad Paneer', 'Paneer tossed in bold Chettinad spices and coconut gravy — fiery, flavorful, and distinctly South Indian.', 14.55, NULL, TRUE, FALSE, FALSE, 2, 'active', 14, 'south-plainfield'),
  ('vegetarian-entrees', 'Chettinad Mix Veg', 'A spicy South Indian-style curry made with mixed vegetables and Chettinad masala — bold and aromatic.', 14.55, NULL, TRUE, FALSE, FALSE, 2, 'active', 15, 'south-plainfield'),
  ('vegetarian-entrees', 'Aloo Gobi', 'Classic North Indian curry of potatoes and cauliflower cooked with aromatic spices — comforting and homestyle.', 14.55, NULL, TRUE, FALSE, FALSE, NULL, 'active', 16, 'south-plainfield'),
  ('vegetarian-entrees', 'Aloo Palak', 'Potatoes cooked in smooth spinach gravy — mild, creamy, and wholesome with every bite.', 14.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 17, 'south-plainfield'),
  ('vegetarian-entrees', 'Aloo Mutter', 'Potatoes and green peas cooked in a spiced tomato gravy — a simple, hearty North Indian classic.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 18, 'south-plainfield'),
  ('vegetarian-entrees', 'Kadai Veg', 'Mixed vegetables tossed in spicy tomato-based Kadai gravy — vibrant, flavorful, and full of zest.', 15.59, NULL, TRUE, FALSE, FALSE, 2, 'active', 19, 'south-plainfield'),
  ('vegetarian-entrees', 'Kadai Paneer', 'Paneer sautéed with bell peppers, onions, and Kadai spices — smoky, spicy, and full of flavor.', 15.59, NULL, TRUE, FALSE, FALSE, 2, 'active', 20, 'south-plainfield'),
  ('vegetarian-entrees', 'Kadai Mushroom', 'Tender mushrooms cooked in spicy tomato gravy with capsicum and onions — smoky and irresistibly bold.', 15.59, NULL, TRUE, FALSE, FALSE, 2, 'active', 21, 'south-plainfield'),
  ('vegetarian-entrees', 'Veg Korma', 'A mix of seasonal vegetables cooked in a mildly spiced cashew-coconut gravy — rich, aromatic, and perfectly balanced.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 22, 'south-plainfield'),
  ('vegetarian-entrees', 'Paneer Korma', 'Paneer cubes cooked in a creamy, nut-based gravy — mild, rich, and packed with aromatic flavors.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 23, 'south-plainfield'),
  ('vegetarian-entrees', 'Aloo Korma', 'Soft potatoes cooked in creamy, spiced coconut-cashew gravy — mild, aromatic, and perfectly comforting.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 24, 'south-plainfield'),
  ('vegetarian-entrees', 'Mushroom Korma', 'Tender mushrooms cooked in creamy cashew-coconut gravy — rich, silky, and full of flavor.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 25, 'south-plainfield'),
  ('vegetarian-entrees', 'Gutti Vankaya (Stuffed Brinjal)', 'Tender eggplants stuffed with spicy peanut masala and slow-cooked — a true Andhra delicacy.', 15.59, NULL, TRUE, FALSE, FALSE, 2, 'active', 26, 'south-plainfield'),
  ('vegetarian-entrees', 'Punjabi Palak Paneer', 'Soft paneer cooked in creamy spinach gravy with Punjabi spices — wholesome, earthy, and soul-satisfying.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 27, 'south-plainfield'),
  ('vegetarian-entrees', 'Paneer Tikka Masala', 'Char-grilled paneer cubes simmered in rich, spiced tomato gravy — smoky, creamy, and bursting with flavor.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 28, 'south-plainfield'),
  ('vegetarian-entrees', 'Paneer Butter Masala', 'Soft paneer simmered in buttery tomato gravy — mildly sweet, creamy, and everyone''s all-time favorite.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 29, 'south-plainfield'),
  ('vegetarian-entrees', 'Navratan Korma', 'A royal medley of nine veggies and fruits cooked in creamy gravy — rich, mildly sweet, and full of color.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 30, 'south-plainfield'),
  ('vegetarian-entrees', 'Malai Kofta', 'Golden-fried cottage cheese dumplings served in a luscious cashew cream sauce — rich, royal, and comforting.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 31, 'south-plainfield'),
  ('vegetarian-entrees', 'Kaju Curry', 'Rich and creamy curry made with cashews in spiced tomato-onion gravy — decadent and flavorful.', 14.55, NULL, TRUE, FALSE, FALSE, NULL, 'active', 32, 'south-plainfield'),
  ('non-vegetarian-entrees', 'Egg Bhurji Dry', 'Masala-scrambled eggs tossed with onions, green chili, and Indian spices.', 13.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 0, 'south-plainfield'),
  ('non-vegetarian-entrees', 'Egg Pulusu', 'Eggs simmered in tangy tamarind-based Andhra gravy — bold, flavorful, and deeply satisfying.', 15.59, NULL, FALSE, FALSE, FALSE, NULL, 'active', 1, 'south-plainfield'),
  ('non-vegetarian-entrees', 'Chicken Vindaloo', 'Spicy Goan chicken curry packed with vinegar-based masala heat.', 16.63, NULL, FALSE, FALSE, FALSE, 2, 'active', 2, 'south-plainfield'),
  ('non-vegetarian-entrees', 'Andhra Chicken Curry', 'Classic Andhra chicken bursting with fiery red chili and earthy aromas.', 16.63, NULL, FALSE, FALSE, FALSE, 2, 'active', 3, 'south-plainfield'),
  ('non-vegetarian-entrees', 'Chicken Mughlai', 'Royal Mughlai-style chicken in a luscious cream-cashew sauce.', 16.63, NULL, FALSE, FALSE, FALSE, NULL, 'active', 4, 'south-plainfield'),
  ('non-vegetarian-entrees', 'Chicken Chettinad', 'A fiery South Indian curry with roasted coconut, black pepper, and bold masalas.', 16.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 5, 'south-plainfield'),
  ('non-vegetarian-entrees', 'Methi Chicken', 'Chicken cooked with fresh fenugreek leaves in a mildly spiced creamy base.', 16.63, NULL, FALSE, FALSE, FALSE, NULL, 'active', 6, 'south-plainfield'),
  ('non-vegetarian-entrees', 'Chicken Tikka Masala', 'Grilled chicken pieces in a rich tomato-onion gravy — the ultimate crowd-pleaser.', 16.63, NULL, FALSE, FALSE, FALSE, NULL, 'active', 7, 'south-plainfield'),
  ('non-vegetarian-entrees', 'Chicken Karaikudi', 'Chettinad-style curry packed with roasted spices and bold flavors.', 16.63, NULL, FALSE, FALSE, FALSE, NULL, 'active', 8, 'south-plainfield'),
  ('non-vegetarian-entrees', 'Butter Chicken', 'Creamy tomato gravy hugging juicy tandoori chicken — smooth, rich, and comforting.', 16.63, NULL, FALSE, FALSE, FALSE, NULL, 'active', 9, 'south-plainfield'),
  ('non-vegetarian-entrees', 'Desi Chicken Curry (With Bone)', 'Homestyle country chicken curry — simple, spicy, and full of soul.', 16.63, NULL, FALSE, FALSE, FALSE, 2, 'active', 10, 'south-plainfield'),
  ('non-vegetarian-entrees', 'Railway Chicken Curry (With Bone)', 'British-era comfort curry cooked with whole spices and coconut hints.', 16.63, NULL, FALSE, FALSE, FALSE, NULL, 'active', 11, 'south-plainfield'),
  ('non-vegetarian-entrees', 'DD Chef''s Special Chicken Curry (Homestyle)', 'A nostalgic homestyle curry cooked with hand-pounded spices and love.', 17.67, NULL, FALSE, FALSE, TRUE, NULL, 'active', 12, 'south-plainfield'),
  ('non-vegetarian-entrees', 'Natu Kodi Curry', 'Country-style chicken cooked in traditional Andhra spices — rustic and full of flavor.', 18.71, NULL, FALSE, FALSE, FALSE, NULL, 'active', 13, 'south-plainfield'),
  ('non-vegetarian-entrees', 'Hyderabadi Goat Curry', 'Slow-cooked goat curry simmered in Hyderabadi spice blend — authentic and aromatic.', 18.71, NULL, FALSE, FALSE, FALSE, NULL, 'active', 14, 'south-plainfield'),
  ('non-vegetarian-entrees', 'Goat Vindaloo', 'Goan-style spicy goat curry with vinegar tang and deep spice tones.', 18.71, NULL, FALSE, FALSE, FALSE, 2, 'active', 15, 'south-plainfield'),
  ('non-vegetarian-entrees', 'Kashmiri Goat Rogan Josh', 'Aromatic Kashmiri goat curry with saffron and rich masala base.', 18.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 16, 'south-plainfield'),
  ('non-vegetarian-entrees', 'Goat Chettinad', 'Fiery and peppery goat curry — a South Indian spice bomb.', 18.71, NULL, FALSE, FALSE, FALSE, 2, 'active', 17, 'south-plainfield'),
  ('non-vegetarian-entrees', 'Goat Mughalai', 'Rich Mughlai-inspired goat curry simmered in spiced yogurt and nuts.', 18.71, NULL, FALSE, FALSE, FALSE, NULL, 'active', 18, 'south-plainfield'),
  ('non-vegetarian-entrees', 'DD Chef''s Special Mutton Curry (Homestyle)', 'Tender mutton slow-cooked in a spicy gravy — comfort food at its finest.', 19.75, NULL, FALSE, FALSE, TRUE, 2, 'active', 19, 'south-plainfield'),
  ('non-vegetarian-entrees', 'Goan Fish Curry', 'Coconut-rich coastal fish curry — tangy, creamy, and irresistibly good.', 17.67, NULL, FALSE, FALSE, FALSE, NULL, 'active', 20, 'south-plainfield'),
  ('non-vegetarian-entrees', 'Chepala Pulusu', 'Traditional Andhra fish curry slow-cooked in tangy tamarind gravy.', 17.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 21, 'south-plainfield'),
  ('non-vegetarian-entrees', 'Royyala Pulusu', 'Prawns simmered in tangy tamarind curry — coastal flavors at their best.', 18.71, NULL, FALSE, FALSE, FALSE, NULL, 'active', 22, 'south-plainfield'),
  ('non-vegetarian-entrees', 'Bhimavaram Royyala Vepudu', 'Fiery coastal prawns cooked in signature Bhimavaram masala for true heat lovers.', 20.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 23, 'south-plainfield'),
  ('non-vegetarian-entrees', 'Royyala Vepudu', 'Andhra-style prawn fry bursting with spicy flavors and ghee-roasted goodness.', 20.79, NULL, FALSE, FALSE, FALSE, 2, 'active', 24, 'south-plainfield'),
  ('non-vegetarian-entrees', 'Mutton Milagu Pirattal (Boneless)', 'Tender mutton chunks tossed with crushed pepper and curry leaves — pure South spice.', 20.79, NULL, FALSE, FALSE, FALSE, NULL, 'active', 25, 'south-plainfield'),
  ('vegetarian-rice-biryani', 'Jeera Rice', 'Aromatic basmati rice tempered with roasted cumin seeds and ghee — simple, fragrant, and the perfect side.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 0, 'south-plainfield'),
  ('vegetarian-rice-biryani', 'Veg Biryani', 'Long-grain basmati rice cooked with garden-fresh vegetables, saffron, and spices — light, flavorful, and satisfying.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'south-plainfield'),
  ('vegetarian-rice-biryani', 'Chilli Mushroom Biryani', 'Spicy mushrooms tossed in chilli masala and layered with flavorful biryani rice — bold, saucy, and full of zest.', 15.59, NULL, TRUE, FALSE, FALSE, 2, 'active', 2, 'south-plainfield'),
  ('vegetarian-rice-biryani', 'Gobi Masala Biryani', 'Crispy cauliflower tossed in spicy masala and layered with aromatic rice — a bold, flavorful twist on classic biryani.', 15.59, NULL, TRUE, FALSE, FALSE, 2, 'active', 3, 'south-plainfield'),
  ('vegetarian-rice-biryani', 'Cut Mirchi Biryani', 'Crispy cut mirchi tossed in spicy masala and layered with fragrant biryani rice — fiery, crunchy, and irresistibly flavorful.', 15.59, NULL, TRUE, FALSE, FALSE, 2, 'active', 4, 'south-plainfield'),
  ('vegetarian-rice-biryani', 'Paneer Biryani', 'Soft paneer cubes layered with fragrant rice and house-blend biryani masala — rich, creamy, and irresistibly aromatic.', 16.63, NULL, TRUE, FALSE, FALSE, NULL, 'active', 5, 'south-plainfield'),
  ('vegetarian-rice-biryani', 'Gutti Vankaya Biryani', 'A Hyderabadi classic! Basmati rice cooked with stuffed brinjal and aromatic spices — smoky, spicy, and full of traditional flavor.', 16.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 6, 'south-plainfield'),
  ('vegetarian-rice-biryani', 'Ulavacharu Biryani (Veg)', 'Fragrant basmati rice layered with slow-cooked horse gram gravy and mixed vegetables — earthy, rich, and authentically Andhra-style.', 16.63, NULL, TRUE, FALSE, FALSE, NULL, 'active', 7, 'south-plainfield'),
  ('vegetarian-rice-biryani', 'Ulavacharu Biryani (Paneer)', 'Paneer cubes simmered in rich horse gram gravy and layered with fragrant biryani rice — earthy, creamy, and full of Andhra flavor.', 16.63, NULL, TRUE, FALSE, FALSE, NULL, 'active', 8, 'south-plainfield'),
  ('vegetarian-rice-biryani', 'Gongura Biryani (Veg)', 'Zesty gongura masala cooked with fresh vegetables and aromatic rice — tangy, spicy, and authentically South Indian.', 16.63, NULL, TRUE, FALSE, FALSE, 2, 'active', 9, 'south-plainfield'),
  ('vegetarian-rice-biryani', 'Gongura Biryani (Paneer)', 'Tangy gongura (sorrel leaves) blended with paneer and layered in spicy biryani rice — a true Andhra delicacy.', 16.63, NULL, TRUE, FALSE, FALSE, 2, 'active', 10, 'south-plainfield'),
  ('vegetarian-rice-biryani', 'Veg Keema Biryani', 'Minced vegetable masala slow-cooked with aromatic basmati rice — spicy, flavorful, and a vegetarian favorite.', 16.63, NULL, TRUE, FALSE, FALSE, 2, 'active', 11, 'south-plainfield'),
  ('vegetarian-rice-biryani', 'Paneer Keema Biryani', 'Finely minced paneer cooked with robust biryani spices and layered with saffron rice — indulgent, spicy, and unique.', 16.63, NULL, TRUE, FALSE, FALSE, 2, 'active', 12, 'south-plainfield'),
  ('vegetarian-rice-biryani', 'Curd Rice', 'Comfort in every bite — chilled curd mixed with rice, tempered with mustard, ginger, and curry leaves.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 13, 'south-plainfield'),
  ('non-veg-biryani', 'Egg Biryani', 'Soft-boiled eggs layered with flavorful biryani rice and spices — simple yet full of flavor.', 15.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 0, 'south-plainfield'),
  ('non-veg-biryani', 'Chicken Dum Biryani', 'Tender chicken simmered with aromatic spices and saffron basmati rice — pure Hyderabadi perfection in every bite.', 16.63, NULL, FALSE, FALSE, FALSE, NULL, 'active', 1, 'south-plainfield'),
  ('non-veg-biryani', 'Ulavacharu Chicken Dum Biryani', 'Slow-cooked chicken biryani blended with signature ulavacharu sauce — earthy and unforgettable.', 17.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 2, 'south-plainfield'),
  ('non-veg-biryani', 'Vijayawada Chicken Biryani (Boneless)', 'Boneless chicken in fiery Vijayawada-style spice mix layered with fragrant rice — a bold Andhra favorite.', 18.71, NULL, FALSE, FALSE, FALSE, 2, 'active', 3, 'south-plainfield'),
  ('non-veg-biryani', 'Gongura Chicken Biryani', 'Spicy, tangy gongura-flavored chicken biryani — a perfect Andhra specialty.', 17.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 4, 'south-plainfield'),
  ('non-veg-biryani', 'Chicken Biryani (Boneless)', 'Succulent boneless chicken cooked to perfection with layered fragrant rice — soft, spicy, and satisfying.', 17.67, NULL, FALSE, FALSE, FALSE, 2, 'active', 5, 'south-plainfield'),
  ('non-veg-biryani', 'Chicken Fry Piece Biryani (Bone-In)', 'Aromatic basmati rice layered with bone-in chicken fry pieces — a true Desi Dhamaka signature dish.', 18.71, NULL, FALSE, FALSE, FALSE, NULL, 'active', 6, 'south-plainfield'),
  ('non-veg-biryani', 'Chicken Fry Piece Biryani (Boneless)', 'Crispy boneless chicken fry blended with aromatic biryani rice — every bite a burst of spice.', 19.75, NULL, FALSE, FALSE, FALSE, NULL, 'active', 7, 'south-plainfield'),
  ('non-veg-biryani', 'DD Special Chicken Biryani (Bone-In)', 'House-special biryani bursting with flavors of chicken, caramelized onions, mint and chef''s secret masala.', 19.75, NULL, FALSE, FALSE, TRUE, NULL, 'active', 8, 'south-plainfield'),
  ('non-veg-biryani', 'DD Special Chicken Biryani (Boneless)', 'Chef''s boneless special — juicy chicken layered with rich masala and fragrant rice.', 20.79, NULL, FALSE, FALSE, TRUE, NULL, 'active', 9, 'south-plainfield'),
  ('non-veg-biryani', 'Chicken Keema Biryani', 'Spiced minced chicken layered with fluffy biryani rice — flavorful and satisfying.', 21.83, NULL, FALSE, FALSE, FALSE, NULL, 'active', 10, 'south-plainfield'),
  ('non-veg-biryani', 'DD Spl Natu Kodi Biryani', 'Traditional country chicken cooked with rustic Andhra spices — authentic and soul-satisfying.', 24.95, NULL, FALSE, FALSE, TRUE, NULL, 'active', 11, 'south-plainfield'),
  ('non-veg-biryani', 'Mutton Dum Biryani', 'Slow-cooked mutton layered with fragrant basmati rice, infused with rich spices and ghee — the royal Hyderabadi classic.', 19.75, NULL, FALSE, FALSE, FALSE, NULL, 'active', 12, 'south-plainfield'),
  ('non-veg-biryani', 'Gongura Mutton Biryani', 'Tangy gongura and spiced mutton layered in biryani rice — Andhra-style with a twist.', 20.79, NULL, FALSE, FALSE, FALSE, NULL, 'active', 13, 'south-plainfield'),
  ('non-veg-biryani', 'Ulavacharu Mutton Dum Biryani', 'Creamy horse gram meets spicy mutton dum biryani — smoky, tangy, and indulgent.', 20.79, NULL, FALSE, FALSE, FALSE, 2, 'active', 14, 'south-plainfield'),
  ('non-veg-biryani', 'Goat Kheema Biryani', 'Minced goat meat cooked in bold masala and layered with basmati rice — a must-try for biryani lovers.', 23.91, NULL, FALSE, FALSE, FALSE, NULL, 'active', 15, 'south-plainfield'),
  ('non-veg-biryani', 'DD Spl Nalli Gosht Biryani', 'Tender lamb shank biryani slow-cooked in royal spices — rich, melt-in-mouth and irresistibly aromatic.', 29.11, NULL, FALSE, FALSE, TRUE, NULL, 'active', 16, 'south-plainfield'),
  ('non-veg-biryani', 'Mamsam Roast Biryani (Bone-In)', 'Bone-in mutton roasted with spices and layered with aromatic rice — fiery and flavorful.', 20.79, NULL, FALSE, FALSE, FALSE, 2, 'active', 17, 'south-plainfield'),
  ('non-veg-biryani', 'Mamsam Roast Biryani (Boneless)', 'Boneless mutton slow-roasted and mixed with biryani rice — bold, meaty, and satisfying.', 21.83, NULL, FALSE, FALSE, FALSE, NULL, 'active', 18, 'south-plainfield'),
  ('non-veg-biryani', 'Fish Biryani', 'Fresh fish fillets cooked in flavorful biryani masala and layered with basmati rice — soft and aromatic.', 19.75, NULL, FALSE, FALSE, FALSE, NULL, 'active', 19, 'south-plainfield'),
  ('non-veg-biryani', 'Shrimp Fry Biryani', 'Golden fried shrimp tossed in spicy masala and layered with biryani rice — coastal flavor meets Hyderabadi aroma.', 19.75, NULL, FALSE, FALSE, FALSE, 2, 'active', 20, 'south-plainfield'),
  ('non-veg-biryani', 'Mutton Fry Piece Biryani (Bone-In)', 'Bone-in mutton cooked in authentic Hyderabadi dum style — juicy, spicy, and unforgettable.', 19.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 21, 'south-plainfield'),
  ('non-veg-biryani', 'Mutton Fry Piece Biryani (Boneless)', 'Juicy boneless mutton pieces fried and mixed with spiced biryani rice — rich, flavorful, and indulgent.', 21.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 22, 'south-plainfield'),
  ('non-veg-biryani', 'Mutton Keema Biryani', 'Minced mutton cooked with rich masala and basmati rice — hearty and full-bodied.', 23.91, NULL, FALSE, FALSE, FALSE, NULL, 'active', 23, 'south-plainfield'),
  ('dd-special-mandi', 'Veg Keema Mandi (Single)', NULL, 27.03, NULL, TRUE, FALSE, FALSE, NULL, 'active', 0, 'south-plainfield'),
  ('dd-special-mandi', 'Veg Keema Mandi (Half)', NULL, 44.71, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'south-plainfield'),
  ('dd-special-mandi', 'Veg Keema Mandi (Full)', NULL, 69.67, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'south-plainfield'),
  ('dd-special-mandi', 'Gutti Vankaya Mandi (Single)', NULL, 27.03, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'south-plainfield'),
  ('dd-special-mandi', 'Gutti Vankaya Mandi (Half)', NULL, 44.71, NULL, TRUE, FALSE, FALSE, NULL, 'active', 4, 'south-plainfield'),
  ('dd-special-mandi', 'Gutti Vankaya Mandi (Full)', NULL, 69.67, NULL, TRUE, FALSE, FALSE, NULL, 'active', 5, 'south-plainfield'),
  ('dd-special-mandi', 'Paneer Mandi (Single)', NULL, 27.03, NULL, TRUE, FALSE, FALSE, NULL, 'active', 6, 'south-plainfield'),
  ('dd-special-mandi', 'Paneer Mandi (Half)', NULL, 44.71, NULL, TRUE, FALSE, FALSE, NULL, 'active', 7, 'south-plainfield'),
  ('dd-special-mandi', 'Paneer Mandi (Full)', NULL, 69.67, NULL, TRUE, FALSE, FALSE, NULL, 'active', 8, 'south-plainfield'),
  ('dd-special-mandi', 'Egg Mandi (Single)', NULL, 27.03, NULL, FALSE, FALSE, FALSE, NULL, 'active', 9, 'south-plainfield'),
  ('dd-special-mandi', 'Egg Mandi (Half)', NULL, 44.71, NULL, FALSE, FALSE, FALSE, NULL, 'active', 10, 'south-plainfield'),
  ('dd-special-mandi', 'Egg Mandi (Full)', NULL, 69.67, NULL, FALSE, FALSE, FALSE, NULL, 'active', 11, 'south-plainfield'),
  ('dd-special-mandi', 'Chicken Mandi (Single)', NULL, 27.03, NULL, FALSE, FALSE, FALSE, NULL, 'active', 12, 'south-plainfield'),
  ('dd-special-mandi', 'Chicken Mandi (Half)', NULL, 47.83, NULL, FALSE, FALSE, FALSE, NULL, 'active', 13, 'south-plainfield'),
  ('dd-special-mandi', 'Chicken Mandi (Full)', NULL, 79.03, NULL, FALSE, FALSE, FALSE, NULL, 'active', 14, 'south-plainfield'),
  ('dd-special-mandi', 'NatuKodi Mandi (Single)', NULL, 27.03, NULL, FALSE, FALSE, FALSE, NULL, 'active', 15, 'south-plainfield'),
  ('dd-special-mandi', 'NatuKodi Mandi (Half)', NULL, 47.83, NULL, FALSE, FALSE, FALSE, NULL, 'active', 16, 'south-plainfield'),
  ('dd-special-mandi', 'NatuKodi Mandi (Full)', NULL, 84.23, NULL, FALSE, FALSE, FALSE, NULL, 'active', 17, 'south-plainfield'),
  ('dd-special-mandi', 'Goat Mandi (Single)', NULL, 27.03, NULL, FALSE, FALSE, FALSE, NULL, 'active', 18, 'south-plainfield'),
  ('dd-special-mandi', 'Goat Mandi (Half)', NULL, 47.83, NULL, FALSE, FALSE, FALSE, NULL, 'active', 19, 'south-plainfield'),
  ('dd-special-mandi', 'Goat Mandi (Full)', NULL, 84.23, NULL, FALSE, FALSE, FALSE, NULL, 'active', 20, 'south-plainfield'),
  ('dd-special-mandi', 'Fish Mandi (Single)', NULL, 27.03, NULL, FALSE, FALSE, FALSE, NULL, 'active', 21, 'south-plainfield'),
  ('dd-special-mandi', 'Fish Mandi (Half)', NULL, 47.83, NULL, FALSE, FALSE, FALSE, NULL, 'active', 22, 'south-plainfield'),
  ('dd-special-mandi', 'Fish Mandi (Full)', NULL, 84.23, NULL, FALSE, FALSE, FALSE, NULL, 'active', 23, 'south-plainfield'),
  ('dd-special-mandi', 'DD Special Nalli Gosht Mandi (Single)', NULL, 27.03, NULL, FALSE, FALSE, TRUE, NULL, 'active', 24, 'south-plainfield'),
  ('dd-special-mandi', 'DD Special Nalli Gosht Mandi (Half)', NULL, 58.23, NULL, FALSE, FALSE, TRUE, NULL, 'active', 25, 'south-plainfield'),
  ('dd-special-mandi', 'DD Special Nalli Gosht Mandi (Full)', NULL, 94.63, NULL, FALSE, FALSE, TRUE, NULL, 'active', 26, 'south-plainfield'),
  ('dd-special-mandi', 'Shrimp Mandi (Single)', NULL, 27.03, NULL, FALSE, FALSE, FALSE, NULL, 'active', 27, 'south-plainfield'),
  ('dd-special-mandi', 'Shrimp Mandi (Half)', NULL, 47.83, NULL, FALSE, FALSE, FALSE, NULL, 'active', 28, 'south-plainfield'),
  ('dd-special-mandi', 'Shrimp Mandi (Full)', NULL, 94.63, NULL, FALSE, FALSE, FALSE, NULL, 'active', 29, 'south-plainfield'),
  ('dd-special-mandi', 'Mixed Full Mandi (Chicken/Mutton)', NULL, 89.43, NULL, FALSE, FALSE, FALSE, NULL, 'active', 30, 'south-plainfield'),
  ('dd-special-mandi', 'SeaFood Mandi (Fish/Shrimp)', NULL, 94.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 31, 'south-plainfield'),
  ('dd-special-mandi', 'Extra Mandi Rice', NULL, 14.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 32, 'south-plainfield'),
  ('dd-specials', 'Goat Haleem', 'Slow-cooked to perfection — tender goat blended with wheat, lentils, and aromatic spices. Creamy, hearty, and rich in authentic Hyderabadi flavor.', 18.71, NULL, FALSE, FALSE, FALSE, NULL, 'active', 0, 'south-plainfield'),
  ('dd-specials', 'Boti Fry', 'Juicy chunks of goat boti sautéed with bold Andhra spices — smoky, spicy, and irresistibly flavorful.', 17.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 1, 'south-plainfield'),
  ('dd-specials', 'DD Chef''s Special Tawa Fish (Bone-In)', 'Bone-in fish fillet seared to perfection with Chef''s signature masala — crisp outside, soft inside, and bursting with flavor.', 20.79, NULL, FALSE, FALSE, TRUE, NULL, 'active', 2, 'south-plainfield'),
  ('dd-specials', 'DD Chef''s Special Tawa Fish (Boneless)', 'Fresh boneless fish grilled on a hot tawa with house-blend spices — smoky, juicy, and absolutely addictive.', 21.83, NULL, FALSE, FALSE, TRUE, NULL, 'active', 3, 'south-plainfield'),
  ('dd-specials', 'Nalli Gosht Roast', 'Tender lamb shanks slow-roasted in rich gravy — fall-off-the-bone perfection loaded with royal Hyderabadi taste.', 21.83, NULL, FALSE, FALSE, FALSE, NULL, 'active', 4, 'south-plainfield'),
  ('dd-specials', 'DD Spl Potlam Biryani', 'Our show-stopper! Spicy biryani wrapped in an omelet and cooked to perfection — layers of flavor in every bite.', 24.95, NULL, TRUE, FALSE, TRUE, 2, 'active', 5, 'south-plainfield'),
  ('dd-family-packs', 'Veg Biryani Family Pack', 'Aromatic basmati rice cooked with fresh vegetables, mint, and traditional spices.', 41.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 0, 'south-plainfield'),
  ('dd-family-packs', 'Egg Biryani Family Pack', 'Fluffy basmati rice layered with spiced boiled eggs and aromatic masala.', 42.63, NULL, FALSE, FALSE, FALSE, NULL, 'active', 1, 'south-plainfield'),
  ('dd-family-packs', 'Paneer Biryani Family Pack', 'Soft paneer cubes cooked in fragrant biryani masala and layered with saffron rice.', 46.79, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'south-plainfield'),
  ('dd-family-packs', 'Chicken Dum Biryani Family Pack', 'Classic Hyderabadi dum biryani — aromatic basmati rice layered with tender chicken.', 46.79, NULL, FALSE, FALSE, FALSE, NULL, 'active', 3, 'south-plainfield'),
  ('dd-family-packs', 'Ulavacharu Chicken Dum Biryani Family Pack', 'Tender chicken layered with biryani rice and simmered in authentic ulavacharu gravy.', 51.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 4, 'south-plainfield'),
  ('dd-family-packs', 'Vijayawada Boneless Biryani Family Pack', 'A fiery South Indian special with boneless chicken cooked in bold masala.', 51.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 5, 'south-plainfield'),
  ('dd-family-packs', 'DD Spl Chicken Biryani Family Pack', 'Our signature Desi Dhamaka special — juicy chicken, aromatic rice, and secret spices.', 51.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 6, 'south-plainfield'),
  ('dd-family-packs', 'Ulavacharu Chicken Boneless Biryani Family Pack', 'Boneless chicken cooked in rich horse gram gravy and layered with biryani rice.', 51.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 7, 'south-plainfield'),
  ('dd-family-packs', 'Ulavacharu Goat Dum Biryani Family Pack', 'Slow-cooked goat meat infused with earthy ulavacharu flavors — a rich Andhra-style biryani.', 59.27, NULL, FALSE, FALSE, FALSE, NULL, 'active', 8, 'south-plainfield'),
  ('dd-family-packs', 'Goat Dum Biryani Family Pack', 'Traditional Hyderabadi-style dum biryani with tender goat meat and fragrant basmati rice.', 57.19, NULL, FALSE, FALSE, FALSE, NULL, 'active', 9, 'south-plainfield'),
  ('dd-family-packs', 'Shrimp Biryani Family Pack', 'Succulent shrimp simmered in spiced biryani masala and layered with long-grain rice.', 57.19, NULL, FALSE, FALSE, FALSE, NULL, 'active', 10, 'south-plainfield'),
  ('dd-family-packs', 'Chicken FryPiece Biryani Bone-In Family Pack', 'Crispy fried chicken layered with flavorful biryani rice — perfect blend of crunch, spice, and aroma.', 47.83, NULL, FALSE, FALSE, FALSE, NULL, 'active', 11, 'south-plainfield'),
  ('dd-family-packs', 'Chicken FryPiece Biryani Boneless Family Pack', 'Juicy boneless chicken pieces fried and layered with fragrant biryani rice.', 55, NULL, FALSE, FALSE, FALSE, NULL, 'active', 12, 'south-plainfield'),
  ('dd-family-packs', 'Mutton Fry Piece Biryani Bone-In Family Pack', 'Tender mutton pieces cooked to perfection and mixed with spiced rice.', 59.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 13, 'south-plainfield'),
  ('dd-family-packs', 'Mutton Fry Piece Biryani Boneless Family Pack', 'Boneless mutton chunks tossed in signature masala and layered with aromatic rice.', 64.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 14, 'south-plainfield'),
  ('indo-chinese', 'Veg Noodles', 'Soft noodles tossed with colorful vegetables and house-made sauces — light, flavorful, and satisfying.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 0, 'south-plainfield'),
  ('indo-chinese', 'Egg Noodles', 'Stir-fried noodles with scrambled egg, soy, and veggies — perfect for egg lovers!', 14.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 1, 'south-plainfield'),
  ('indo-chinese', 'Chicken Noodles', 'Classic stir-fried noodles with tender chicken and crunchy veggies — comforting and full of taste.', 15.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 2, 'south-plainfield'),
  ('indo-chinese', 'Veg Fried Rice', 'Simple yet delicious — wok-tossed rice loaded with veggies and authentic Indo-Chinese flavors.', 14.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'south-plainfield'),
  ('indo-chinese', 'Egg Fried Rice', 'Fluffy rice blended with scrambled eggs, veggies, and spices — a delicious quick meal.', 14.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 4, 'south-plainfield'),
  ('indo-chinese', 'Chicken Fried Rice', 'Aromatic rice wok-tossed with juicy chicken, egg, and veggies — the ultimate comfort meal.', 15.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 5, 'south-plainfield'),
  ('indo-chinese', 'Veg Schezwan Fried Rice', 'Wok-tossed rice infused with chili-garlic Schezwan sauce and crunchy vegetables.', 14.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 6, 'south-plainfield'),
  ('indo-chinese', 'Egg Schezwan Fried Rice', 'Egg fried rice meets Schezwan spice — bold, saucy, and unforgettable!', 15.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 7, 'south-plainfield'),
  ('indo-chinese', 'Chicken Schezwan Fried Rice', 'Spicy Schezwan rice bursting with flavors of garlic, chili, and tender chicken.', 16.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 8, 'south-plainfield'),
  ('indo-chinese', 'Schezwan Shrimp Fried Rice', 'Spicy, zesty rice with shrimp and Schezwan sauce — a fiery twist for seafood lovers.', 16.63, NULL, FALSE, FALSE, FALSE, 2, 'active', 9, 'south-plainfield'),
  ('indo-chinese', 'Shrimp Fried Rice', 'Juicy shrimp tossed with rice, soy, and aromatic spices — ocean-fresh goodness in every bite.', 16.63, NULL, FALSE, FALSE, FALSE, NULL, 'active', 10, 'south-plainfield'),
  ('indo-chinese', 'Street Food Fried Rice (Chicken/Egg/Veg)', 'Inspired by Indian street flavors — smoky, spicy, and irresistibly tasty in every bite!', 16.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 11, 'south-plainfield'),
  ('indo-chinese', 'Schezwan Veg Noodles', 'Loaded with fresh vegetables and tossed in spicy Schezwan sauce — a perfect balance of heat and flavor.', 14.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 12, 'south-plainfield'),
  ('indo-chinese', 'Schezwan Chicken Noodles', 'Fiery noodles tossed with juicy chicken, veggies, and Schezwan spice — a bold Indo-Chinese favorite!', 15.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 13, 'south-plainfield'),
  ('snacks', 'Roasted Peanut Masala', 'Crispy roasted peanuts mixed with zesty masala — perfect for crunchy cravings.', 11.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 0, 'south-plainfield'),
  ('snacks', 'Samosa', 'Crispy pastry stuffed with spiced potatoes — the all-time favorite Indian snack.', 11.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'south-plainfield'),
  ('snacks', 'Cut Mirchi', 'Crispy fried green chilies sliced and seasoned to perfection — bold, spicy, and addictive!', 10.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 2, 'south-plainfield'),
  ('snacks', 'Mirchi Bajji', 'Street-style hot chili fritters coated in gram flour — crunchy outside, soft inside.', 11.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 3, 'south-plainfield'),
  ('snacks', 'Stuffed Mirchi', 'Green chilies stuffed with flavorful masala, deep-fried till golden — fiery and irresistible.', 11.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 4, 'south-plainfield'),
  ('snacks', 'Bandi Punugulu', 'Golden, fluffy fritters made from fermented dosa batter — a South Indian favorite!', 11.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 5, 'south-plainfield'),
  ('snacks', 'Kaju Fry', 'Crunchy cashews tossed with pepper and house spices — a royal and irresistible snack.', 14.55, NULL, TRUE, FALSE, FALSE, NULL, 'active', 6, 'south-plainfield'),
  ('snacks', 'Egg Bonda (3 Pcs)', 'Boiled eggs dipped in spiced batter and fried golden brown — crispy, rich, and satisfying.', 12.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 7, 'south-plainfield'),
  ('snacks', 'Boiled Peanuts Masala', 'Tender peanuts tossed with onions, tomatoes, and spices — a spicy, tangy delight!', 11.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 8, 'south-plainfield'),
  ('snacks', 'Malai Bun', 'Soft, sweet bun filled with rich cream — a melt-in-the-mouth Hyderabad classic.', 5, NULL, TRUE, FALSE, FALSE, NULL, 'active', 9, 'south-plainfield'),
  ('snacks', 'Plain Bun', 'Fluffy, warm bun that''s simple, soft, and nostalgic — the perfect tea-time partner.', 5, NULL, TRUE, FALSE, FALSE, NULL, 'active', 10, 'south-plainfield'),
  ('chai-coffee', 'Masala Chai', 'A comforting blend of tea, milk, and Indian spices — a cup of warmth in every sip.', 2.07, NULL, TRUE, FALSE, FALSE, NULL, 'active', 0, 'south-plainfield'),
  ('chai-coffee', 'Irani Chai', 'Traditional Hyderabad-style tea — strong, creamy, and irresistibly aromatic.', 3.11, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'south-plainfield'),
  ('chai-coffee', 'Desi Chai', 'Simple, strong, and soul-warming — the classic Indian cup of tea.', 2.07, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'south-plainfield'),
  ('chai-coffee', 'Instant Coffee (Bru)', 'Quick, strong, and smooth — India''s favorite instant coffee delight.', 3.11, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'south-plainfield'),
  ('chai-coffee', 'DD Spl Filter Coffee', 'South Indian-style filter coffee, brewed to perfection with rich aroma and flavor.', 4.99, NULL, TRUE, FALSE, TRUE, NULL, 'active', 4, 'south-plainfield'),
  ('soft-drinks', 'Butter Milk', 'Cool, spiced yogurt drink — refreshing and perfect after a hearty meal.', 5.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 0, 'south-plainfield'),
  ('soft-drinks', 'Mango Lassi', 'Rich and creamy yogurt drink blended with ripe mangoes — a perfect desi cooler.', 6.23, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'south-plainfield'),
  ('soft-drinks', 'Sweet Lassi', 'Creamy, sweet, and soothing — a traditional Indian favorite.', 5.19, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'south-plainfield'),
  ('soft-drinks', 'Salt Lassi', 'A savory yogurt drink that cools you from the inside out.', 5.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'south-plainfield'),
  ('soft-drinks', 'Fresh Lemon Soda', 'Freshly squeezed lemon with sparkling soda — sweet, salty, or both!', 6.23, NULL, TRUE, FALSE, FALSE, NULL, 'active', 4, 'south-plainfield'),
  ('soft-drinks', 'Goli Soda', 'Old-school Indian soda pop — fun, fizzy, and full of nostalgia!', 4.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 5, 'south-plainfield'),
  ('soft-drinks', 'Can Drink', 'India''s bold cola with a strong, fizzy kick — perfect with spicy dishes!', 2.07, NULL, TRUE, FALSE, FALSE, 2, 'active', 6, 'south-plainfield'),
  ('soft-drinks', 'Topo Chico', 'The premium sparkling mineral water with a crisp, refreshing fizz.', 4.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 7, 'south-plainfield'),
  ('soft-drinks', 'Coke – Can', 'The timeless favorite — fizzy, cool, and always satisfying.', 2.07, NULL, TRUE, FALSE, FALSE, NULL, 'active', 8, 'south-plainfield'),
  ('soft-drinks', 'Diet Coke – Can', 'Light, bubbly, and refreshing — zero calories, all the flavor.', 2.07, NULL, TRUE, FALSE, FALSE, NULL, 'active', 9, 'south-plainfield'),
  ('soft-drinks', 'Zero Coke – Can', 'All the Coca-Cola taste with none of the sugar.', 2.07, NULL, TRUE, FALSE, FALSE, NULL, 'active', 10, 'south-plainfield'),
  ('soft-drinks', 'Sprite Can', 'Crisp lemon-lime fizz that hits refresh instantly.', 2.07, NULL, TRUE, FALSE, FALSE, NULL, 'active', 11, 'south-plainfield'),
  ('soft-drinks', 'Gingerale Can', 'Smooth and bubbly with a hint of ginger — a refreshing twist.', 2.07, NULL, TRUE, FALSE, FALSE, NULL, 'active', 12, 'south-plainfield'),
  ('soft-drinks', 'Mexican Coke', 'Made with real cane sugar — richer, smoother, and extra delicious!', 5.19, NULL, TRUE, FALSE, FALSE, NULL, 'active', 13, 'south-plainfield'),
  ('soft-drinks', 'Smart Water', 'Hydration with a hint of purity — stay smart, stay refreshed.', 4.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 14, 'south-plainfield'),
  ('soft-drinks', 'Poland Spring Water Bottle', 'Fresh, clean water to keep you cool and refreshed.', 0.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 15, 'south-plainfield'),
  ('soft-drinks', 'Limca Can', 'Zesty lemon drink with that unmistakable Indian tang.', 2.69, NULL, TRUE, FALSE, FALSE, NULL, 'active', 16, 'south-plainfield'),
  ('soft-drinks', 'Mexican Fanta', 'Burst of orange sweetness in every sip — pure sunshine in a bottle.', 5.19, NULL, TRUE, FALSE, FALSE, NULL, 'active', 17, 'south-plainfield'),
  ('soft-drinks', 'Coke – Mexican Bottle (20oz)', 'Classic Coca-Cola with authentic Mexican sweetness.', 4.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 18, 'south-plainfield'),
  ('soft-drinks', 'Sprite Bottle', 'Zingy lemon-lime refreshment in every sip.', 4.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 19, 'south-plainfield'),
  ('soft-drinks', 'Diet Coke – Bottle', 'Light, fizzy, and refreshing — the perfect guilt-free cola.', 4.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 20, 'south-plainfield'),
  ('soft-drinks', 'Mexican Sprite', 'Extra fizzy, extra flavorful — the ultimate lemon-lime experience.', 5.19, NULL, TRUE, FALSE, FALSE, NULL, 'active', 21, 'south-plainfield'),
  ('soft-drinks', 'Canada Dry', 'Classic ginger ale that pairs perfectly with rich, spicy meals.', 3.11, NULL, TRUE, FALSE, FALSE, 2, 'active', 22, 'south-plainfield'),
  ('soft-drinks', 'GingerAle Bottle', 'Crisp and full-bodied ginger ale to refresh your palate.', 4.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 23, 'south-plainfield'),
  ('soft-drinks', 'Canada Dry Can', 'Classic bubbly ginger flavor in a crisp, chilled can.', 2.07, NULL, TRUE, FALSE, FALSE, NULL, 'active', 24, 'south-plainfield'),
  ('soft-drinks', 'Zero Coke – Bottle', 'Full flavor, zero sugar — enjoy the lighter side of Coke.', 4.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 25, 'south-plainfield'),
  ('soft-drinks', 'Limca', 'The iconic lemony soda from India — cool, crisp, and citrusy.', 3.63, NULL, TRUE, FALSE, FALSE, NULL, 'active', 26, 'south-plainfield'),
  ('soft-drinks', 'Topochico – Can', 'Bright mineral fizz with natural sparkle — refreshingly different.', 3.11, NULL, TRUE, FALSE, FALSE, NULL, 'active', 27, 'south-plainfield'),
  ('soft-drinks', 'Thums Up – Can', 'Pure, crisp hydration to complement your meal perfectly.', 2.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 28, 'south-plainfield'),
  ('kids-menu', 'French Fries', 'Crispy golden fries served hot — the ultimate kid-favorite snack!', 8.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 0, 'south-plainfield'),
  ('kids-menu', 'Chicken Nuggets', 'Tender, juicy chicken bites coated in a crunchy golden crust — fun to eat and full of flavor.', 10.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 1, 'south-plainfield'),
  ('kids-menu', 'DD Mini Kulcha', 'Soft, buttery mini kulchas served with mild curry — a delightful desi treat made just for little tummies!', 10.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'south-plainfield'),
  ('desserts', 'Ice Cream', 'Chilled scoops of creamy delight — the perfect finish to your meal.', 6.23, NULL, TRUE, FALSE, FALSE, NULL, 'active', 0, 'south-plainfield'),
  ('desserts', 'Gulab Jamun', 'Soft, golden dumplings soaked in warm sugar syrup — a timeless Indian classic.', 6.23, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'south-plainfield'),
  ('desserts', 'Rasmalai', 'Soft cheese patties soaked in creamy, saffron milk — melt-in-mouth perfection.', 6.23, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'south-plainfield'),
  ('desserts', 'Carrot Halwa', 'Slow-cooked carrots in milk and ghee, topped with nuts — pure indulgence.', 7.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'south-plainfield'),
  ('desserts', 'Double Ka Meetha', 'Hyderabadi bread pudding made with ghee, milk, and saffron — rich and royal.', 8.31, NULL, TRUE, FALSE, FALSE, NULL, 'active', 4, 'south-plainfield'),
  ('desserts', 'Sorakaya Halwa', 'Delicately flavored bottle gourd halwa — light, rich, and wholesome.', 8.31, NULL, TRUE, FALSE, FALSE, NULL, 'active', 5, 'south-plainfield'),
  ('desserts', 'Gummadikaya Halwa', 'Pumpkin-based traditional sweet with rich ghee flavor and nutty aroma.', 8.31, NULL, TRUE, FALSE, FALSE, NULL, 'active', 6, 'south-plainfield'),
  ('desserts', 'DD Special Sweet', 'Chef''s special house dessert — a sweet surprise worth saving room for.', 12.47, NULL, TRUE, FALSE, TRUE, NULL, 'active', 7, 'south-plainfield'),
  ('desserts', 'Beetroot Halwa', 'A healthy twist on tradition — earthy beetroot cooked in milk and ghee.', 8.31, NULL, TRUE, FALSE, FALSE, NULL, 'active', 8, 'south-plainfield'),
  ('desserts', 'Icecream Gulabjamun', 'Warm gulab jamun paired with cold ice cream — a heavenly fusion dessert.', 8.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 9, 'south-plainfield'),
  ('desserts', 'Sweet Paan', 'Refreshing betel leaf delight filled with sweet nuts and flavors — the perfect after-meal treat.', 2.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 10, 'south-plainfield'),
  ('thali-cooker-pulav', 'Veg Thali', 'A wholesome South Indian platter with flavorful curries, dal, rice, roti, and sweets — a perfect balance of taste and tradition.', 20.79, NULL, TRUE, FALSE, FALSE, NULL, 'active', 0, 'south-plainfield'),
  ('thali-cooker-pulav', 'Non Veg Thali', 'A hearty feast featuring signature meat curries, rice, roti, and sides — crafted for true food lovers.', 22.87, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'south-plainfield'),
  ('thali-cooker-pulav', 'Chicken Cooker Pulav', 'Juicy chicken pieces simmered in aromatic rice and bold spices — a hearty, flavorful one-pot classic that tastes just like home.', 89.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 2, 'south-plainfield'),
  ('thali-cooker-pulav', 'Mutton Cooker Pulav', 'Tender mutton slow-cooked with fragrant basmati rice and house-made spices — rich, rustic, and bursting with authentic Andhra flavor.', 99.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 3, 'south-plainfield')
) AS v(cat_slug, name, description, price, image, veg, popular, chef_special, spice_level, status, display_order, location_id)
JOIN cat c ON c.slug = v.cat_slug
WHERE NOT EXISTS (
  SELECT 1 FROM public.menu_items mi
  JOIN public.menu_categories mc ON mc.id = mi.category_id
  WHERE mc.location_id = 'south-plainfield' AND mc.slug = v.cat_slug AND mi.name = v.name
);

COMMIT;
