-- ============================================================
-- Desi Dhamaka — website menu seed for Oak Tree
-- location_id: oak-tree
-- Source: desidhamakanj.net website menu
-- Categories: 19 · Items: 324
-- Run DELETE on menu_items/menu_categories BEFORE this file.
-- Idempotent: re-running will not duplicate rows.
-- ============================================================

BEGIN;

-- Categories
INSERT INTO public.menu_categories (name, slug, image, display_order, status, location_id)
VALUES
  ('Soups', 'soups', NULL, 1, 'active', 'oak-tree'),
  ('Vegetarian Appetizers', 'vegetarian-appetizers', NULL, 2, 'active', 'oak-tree'),
  ('Non-Vegetarian Appetizers', 'non-vegetarian-appetizers', NULL, 3, 'active', 'oak-tree'),
  ('Kebab & Tandooris', 'kebab-and-tandooris', NULL, 4, 'active', 'oak-tree'),
  ('Naans & Breads', 'naans-and-breads', NULL, 5, 'active', 'oak-tree'),
  ('Vegetarian Entrees', 'vegetarian-entrees', NULL, 6, 'active', 'oak-tree'),
  ('Non-Vegetarian Entrees', 'non-vegetarian-entrees', NULL, 7, 'active', 'oak-tree'),
  ('Vegetarian Rice & Biryani', 'vegetarian-rice-and-biryani', NULL, 8, 'active', 'oak-tree'),
  ('Non-Veg Biryani', 'non-veg-biryani', NULL, 9, 'active', 'oak-tree'),
  ('DD Special Mandi', 'dd-special-mandi', NULL, 10, 'active', 'oak-tree'),
  ('DD Specials', 'dd-specials', NULL, 11, 'active', 'oak-tree'),
  ('DD Family Packs', 'dd-family-packs', NULL, 12, 'active', 'oak-tree'),
  ('Indo Chinese', 'indo-chinese', NULL, 13, 'active', 'oak-tree'),
  ('Snacks', 'snacks', NULL, 14, 'active', 'oak-tree'),
  ('Chai & Coffee', 'chai-and-coffee', NULL, 15, 'active', 'oak-tree'),
  ('Soft Drinks', 'soft-drinks', NULL, 16, 'active', 'oak-tree'),
  ('Kids Menu', 'kids-menu', NULL, 17, 'active', 'oak-tree'),
  ('Desserts', 'desserts', NULL, 18, 'active', 'oak-tree'),
  ('Thali', 'thali', NULL, 19, 'active', 'oak-tree')
ON CONFLICT (location_id, slug) DO NOTHING;

-- Menu items
WITH cat AS (
  SELECT id, slug FROM public.menu_categories WHERE location_id = 'oak-tree'
)
INSERT INTO public.menu_items (category_id, name, description, price, image, veg, popular, chef_special, spice_level, status, display_order, location_id)
SELECT c.id, v.name, v.description, v.price, v.image, v.veg, v.popular, v.chef_special, v.spice_level, v.status::public.content_status, v.display_order, v.location_id
FROM (VALUES
  ('soups', 'Veg Sweet Corn Soup', 'A comforting blend of sweet corn, fresh vegetables, and rich broth — creamy, mildly seasoned, and soul-soothing in every spoonful.', 7.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('soups', 'Chicken Sweet Corn Soup', 'Tender chicken and golden corn kernels simmered in a smooth, savory broth — the perfect balance of comfort and flavor.', 7.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 2, 'oak-tree'),
  ('soups', 'Veg Manchow Soup', 'A hot and spicy delight packed with crunchy vegetables and zesty flavors — finished with crispy noodles for that ultimate kick.', 7.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 3, 'oak-tree'),
  ('soups', 'Chicken Manchow Soup', 'A spicy, tangy Indo-Chinese favorite — loaded with shredded chicken, crunchy veggies, and topped with crispy noodles for that perfect crunch.', 7.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 4, 'oak-tree'),
  ('soups', 'Veg Hot & Sour Soup', 'A bold mix of tangy, spicy, and savory — packed with fresh vegetables and exotic Asian flavors to awaken your taste buds.', 7.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 5, 'oak-tree'),
  ('soups', 'Chicken Hot & Sour Soup', 'A fiery, tangy soup bursting with bold Indo-Chinese flavors — shredded chicken, veggies, and spice that warms you up instantly.', 7.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 6, 'oak-tree'),
  ('soups', 'Natu Kodi Soup', 'Authentic country chicken slow-cooked with bold spices and herbs — a traditional South Indian remedy that''s as flavorful as it is hearty.', 8.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 7, 'oak-tree'),
  ('soups', 'Goat Paya (Aattukal) Soup', 'Traditional bone broth made from slow-cooked goat trotters — rich, nourishing, and bursting with authentic homemade flavor.', 8.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 8, 'oak-tree'),
  ('vegetarian-appetizers', 'Punjabi Samosa', 'Golden, flaky samosas filled with spiced potato and peas — an all-time favorite Indian street snack.', 8.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('vegetarian-appetizers', 'Paneer Pepper Fry', 'Soft paneer cubes tossed with black pepper, curry leaves, and aromatic masalas — fiery and flavorful in every bite.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 2, 'oak-tree'),
  ('vegetarian-appetizers', 'Mushroom Pepper Fry', 'Tender mushrooms tossed with black pepper, onions, and curry leaves — a spicy, earthy classic.', 12.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 3, 'oak-tree'),
  ('vegetarian-appetizers', 'Baby Corn Pepper Fry', 'Tender baby corn stir-fried with cracked pepper and spices — crisp, spicy, and full of flavor.', 12.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 4, 'oak-tree'),
  ('vegetarian-appetizers', 'Gobi Pepper Fry', 'Cauliflower florets roasted with crushed pepper and curry leaves — a spicy, earthy flavor explosion.', 12.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 5, 'oak-tree'),
  ('vegetarian-appetizers', 'Corn Masala Fry', 'Crispy golden corn sautéed with spicy masala, onions, and curry leaves — the perfect crunchy starter with a desi twist.', 12.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 6, 'oak-tree'),
  ('vegetarian-appetizers', 'Gobi 65', 'Crispy South Indian-style cauliflower fry seasoned with aromatic spices — crunchy, spicy, and bursting with flavor.', 12.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 7, 'oak-tree'),
  ('vegetarian-appetizers', 'Hyderabad Paneer 65', 'Signature Hyderabadi-style paneer fry — bold, spicy, and bursting with authentic South Indian flavors.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 8, 'oak-tree'),
  ('vegetarian-appetizers', 'Paneer Pakoda', 'Crispy golden fritters made with tender paneer dipped in seasoned gram-flour batter.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 9, 'oak-tree'),
  ('vegetarian-appetizers', 'Onion Pakoda', 'Golden-fried onion fritters seasoned with herbs and gram flour — crispy, aromatic, and perfect for any mood.', 12.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 10, 'oak-tree'),
  ('vegetarian-appetizers', 'Spinach Pakoda', 'Crispy spinach fritters seasoned with aromatic spices — light, crunchy, and irresistibly tasty.', 12.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 11, 'oak-tree'),
  ('vegetarian-appetizers', 'Cashew Pakoda', 'Crunchy cashew fritters fried to perfection — rich, nutty, and irresistibly crisp.', 12.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 12, 'oak-tree'),
  ('vegetarian-appetizers', 'Chilli Baby Corn', 'Crispy baby corn tossed in spicy chilli sauce with onions and bell peppers — hot, tangy, and addictive.', 12.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 13, 'oak-tree'),
  ('vegetarian-appetizers', 'Chilli Gobi', 'Crispy cauliflower florets coated in fiery chilli sauce — bold, tangy, and downright addictive.', 12.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 14, 'oak-tree'),
  ('vegetarian-appetizers', 'Chilli Mushroom', 'Juicy mushrooms tossed in hot chilli sauce with peppers and onions — tangy, spicy, and utterly satisfying.', 12.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 15, 'oak-tree'),
  ('vegetarian-appetizers', 'Chilli Lotus Root', 'Crunchy lotus root rings tossed in hot and tangy chilli sauce — a unique twist for spice lovers.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 16, 'oak-tree'),
  ('vegetarian-appetizers', 'Chilli Paneer', 'Classic Indo-Chinese delight — soft paneer chunks coated in spicy, tangy chilli sauce and sautéed to perfection.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 17, 'oak-tree'),
  ('vegetarian-appetizers', 'Veg Manchurian', 'Crispy veggie balls tossed in tangy, spicy Indo-Chinese sauce — a fusion favorite that never fails to impress.', 12.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 18, 'oak-tree'),
  ('vegetarian-appetizers', 'Baby Corn Manchurian', 'Golden-fried baby corn tossed in zesty Indo-Chinese sauce — crunchy, tangy, and full of flavor.', 12.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 19, 'oak-tree'),
  ('vegetarian-appetizers', 'Lotus Root Manchurian', 'Crispy lotus root tossed in bold Manchurian sauce — crunchy, saucy, and perfectly balanced.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 20, 'oak-tree'),
  ('vegetarian-appetizers', 'Gobi Manchurian', 'Crispy cauliflower florets wok-tossed in flavorful Manchurian sauce — spicy, saucy, and packed with crunch.', 12.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 21, 'oak-tree'),
  ('vegetarian-appetizers', 'Paneer Manchurian', 'Soft paneer cubes wok-tossed in flavorful Manchurian sauce — spicy, saucy, and crowd-favorite.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 22, 'oak-tree'),
  ('vegetarian-appetizers', 'Mushroom Manchurian', 'Crispy mushrooms coated in spicy, tangy Manchurian sauce — a perfect Indo-Chinese favorite.', 12.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 23, 'oak-tree'),
  ('vegetarian-appetizers', 'Paneer 555', 'A chef''s special fusion of crispy paneer and spicy seasoning — bold, flavorful, and perfectly addictive.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 24, 'oak-tree'),
  ('vegetarian-appetizers', 'Gobi 555', 'Crispy cauliflower tossed in fiery seasoning — a chef''s special creation that''s bold, spicy, and utterly addictive.', 12.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 25, 'oak-tree'),
  ('vegetarian-appetizers', 'Baby Corn 555', 'Crispy fried baby corn tossed in special 555 masala — spicy, crunchy, and full of flavor.', 12.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 26, 'oak-tree'),
  ('vegetarian-appetizers', 'Mushroom 555', 'Crispy mushrooms tossed in signature spicy seasoning — fiery, bold, and bursting with umami.', 12.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 27, 'oak-tree'),
  ('vegetarian-appetizers', 'Vegetable Bullets', 'Crispy veggie bites packed with flavor and spices — the perfect crunchy snack for spice lovers.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 28, 'oak-tree'),
  ('vegetarian-appetizers', 'Paneer Burji Dry', 'Scrambled paneer sautéed with onions, spices, and herbs — dry, flavorful, and perfectly spiced for every craving.', 14.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 29, 'oak-tree'),
  ('vegetarian-appetizers', 'Paneer Majestic', 'A royal appetizer made with golden-fried paneer tossed in creamy, spiced yogurt sauce — majestic in every sense.', 14.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 30, 'oak-tree'),
  ('vegetarian-appetizers', 'Gobi Majestic', 'Crispy cauliflower tossed in creamy, spiced yogurt sauce — a true majestic treat with a fusion kick.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 31, 'oak-tree'),
  ('vegetarian-appetizers', 'Mushroom Majestic', 'Golden-fried mushrooms coated in smooth, spiced yogurt-based sauce — rich, aromatic, and full of flavor.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 32, 'oak-tree'),
  ('vegetarian-appetizers', 'Baby Corn Majestic', 'Crispy baby corn tossed in a rich, creamy, and mildly spiced majestic sauce — an irresistible Indo-fusion treat.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 33, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Ameerpet Egg Fry', 'Street-style masala egg fry loaded with onions, chilies, and signature Ameerpet spice.', 13.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Chilli Egg', 'Boiled eggs tossed in a tangy Indo-Chinese chili sauce — a fiery twist on comfort.', 14.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 2, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Chilli Chicken', 'Crispy Indo-Chinese chicken coated in a spicy chili garlic sauce.', 14.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 3, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Chicken 65 Dry', 'Crispy, spicy, and iconic — the original South Indian chicken starter.', 14.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 4, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Chicken Majestic', 'Crispy strips of chicken tossed in a creamy, spicy sauce — majestic indeed!', 14.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 5, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Chicken Pepper Fry', 'Aromatic South-style pepper chicken with roasted curry leaves and black pepper heat.', 14.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 6, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Chicken Manchurian', 'Indo-Chinese fusion favorite — crispy chicken tossed in tangy soy-chili sauce.', 14.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 7, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Hyd Chicken 65 Wet', 'A juicy, saucy twist to the classic Chicken 65 — bursting with Hyderabad spice.', 14.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 8, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Chicken Lollipop', 'Crispy lollipop chicken glazed in spicy sauce — juicy inside, crunchy outside.', 15.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 9, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Hell of Chicken Drums', 'Drumsticks coated in fiery marinade — spicy, smoky, and dangerously addictive.', 15.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 10, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Chicken 555', 'A crowd-favorite spicy dry chicken with crunchy texture and rich masala coating.', 15.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 11, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Kothimeera Chicken', 'Juicy chicken tossed with fresh coriander, chili, and house masala — fresh and zesty.', 15.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 12, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Ginger Chicken', 'Tender chicken bites tossed in a flavorful ginger-garlic masala.', 15.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 13, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Garlic Chicken', 'Soft chicken chunks glazed in garlic sauce — aromatic and satisfying.', 15.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 14, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Andhra Kodi Vepudu (Bone-In)', 'Traditional spicy chicken roast with bones — rustic, bold, and full of aroma.', 15.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 15, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Andhra Kodi Vepudu (Boneless)', 'Classic Andhra chicken roast cooked to perfection — tender and fiery.', 16.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 16, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Mirapakaya Kodi Vepudu', 'A spicy dry chicken roast infused with green chilies and Andhra-style seasoning.', 15.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 17, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Natu Kodi Roast', 'Traditional country chicken slow-roasted with signature Andhra masalas.', 17.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 18, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Mutton Ghee Roast (Bone-In)', 'Bone-in mutton slow-roasted with ghee and fiery red masala — a royal treat.', 17.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 19, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Mutton Ghee Roast (Boneless)', 'Succulent mutton roasted in ghee and Mangalorean spices — rich and aromatic.', 19.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 20, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Gongura Mamsam Fry (Bone-In)', 'Tangy gongura leaves meet spicy mutton — Andhra-style perfection.', 17.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 21, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Gongura Mamsam Fry (Boneless)', 'Tender mutton roasted with gongura (sorrel leaves) — tangy, spicy, and unforgettable.', 19.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 22, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Mutton Sukka (Bone-In)', 'Traditional dry mutton fry with a coarse masala and rustic South flavor.', 17.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 23, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Mutton Sukka (Boneless)', 'Boneless mutton roasted with coconut and coarse spices — a perfect bar-style starter.', 19.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 24, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Palnadu Mamsam Roast (Bone-In)', 'Classic Palnadu-style mutton fry — spicy, smoky, and ghee-rich.', 17.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 25, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Palnadu Mamsam Roast (Boneless)', 'Authentic Palnadu-style dry mutton roast with ghee and local masalas.', 19.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 26, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Mutton Pepper Fry (Bone-In)', 'Mutton roasted with freshly ground pepper and coconut bits — bold and meaty.', 17.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 27, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Mutton Pepper Fry (Boneless)', 'Tender mutton tossed with pepper masala and ghee — spicy, earthy, and rich.', 19.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 28, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Fish 65', 'Golden-fried fish bites tossed in spicy 65 masala — crisp, spicy, and flavorful.', 16.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 29, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Apollo Fish', 'Crispy fish tossed in Indo-Chinese spices — juicy, bold, and full of heat.', 16.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 30, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Schezwan Chilli Fish', 'Crispy fish in spicy Schezwan sauce — a must-try Indo-Chinese favorite.', 16.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 31, 'oak-tree'),
  ('non-vegetarian-appetizers', 'DD Spl Cilantro Fish', 'Pan-seared fish flavored with fresh cilantro and South Indian spices.', 16.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 32, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Black Pepper Prawns', 'Prawns stir-fried with cracked pepper and curry leaves — bold and aromatic.', 17.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 33, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Loose Prawns', 'Lightly battered prawns stir-fried with onions, garlic, and green chilies.', 17.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 34, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Godavari Fish Fry', 'Coastal-style fried fish marinated in tangy masala and shallow-fried to golden perfection.', 20.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 35, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Shrimp Majestic', 'Crispy shrimp tossed in a creamy, spicy Andhra-style sauce.', 17.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 36, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Chilli Shrimp', 'Crispy shrimp tossed in a bold Indo-Chinese chili sauce with peppers.', 17.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 37, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Shrimp Fry', 'Pan-fried shrimp tossed with house spices and curry leaves — coastal perfection.', 17.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 38, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Karivepaaku Kodi', 'Crispy chicken cooked with curry leaf tempering — full of aroma and crunch.', 14.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 39, 'oak-tree'),
  ('non-vegetarian-appetizers', 'Karampodi Kodi', 'Signature Guntur-style chicken fry dusted with fiery karampodi spice powder.', 14.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 40, 'oak-tree'),
  ('kebab-and-tandooris', 'Tangdi Kebab', 'Juicy drumsticks marinated overnight and flame-grilled for smoky perfection.', 16.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('kebab-and-tandooris', 'Chicken Seekh Kebab', 'Minced chicken mixed with herbs and spices, skewered and grilled to perfection.', 16.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 2, 'oak-tree'),
  ('kebab-and-tandooris', 'Chicken Chapli', 'Spicy minced chicken patties shallow-fried — a North Indian street-style favorite.', 16.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 3, 'oak-tree'),
  ('kebab-and-tandooris', 'Chicken Hariyali', 'Green-marinated chicken rich in mint and coriander — fresh and flavorful.', 16.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 4, 'oak-tree'),
  ('kebab-and-tandooris', 'Murg Malai Kebab', 'Creamy, velvety chicken kebabs that melt in your mouth with every bite.', 16.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 5, 'oak-tree'),
  ('kebab-and-tandooris', 'Tandoori Chicken Wild Wings', 'Smoky tandoori-marinated wings grilled to perfection — bold, juicy, and absolutely irresistible!', 17.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 6, 'oak-tree'),
  ('kebab-and-tandooris', 'Tawa Fish', 'Pan-seared fish cooked with house spices for a bold and zesty flavor.', 18.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 7, 'oak-tree'),
  ('kebab-and-tandooris', 'Tandoori Jinga', 'Succulent jumbo prawns grilled with a smoky tandoori punch.', 19.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 8, 'oak-tree'),
  ('kebab-and-tandooris', 'Tandoori Pomfret', 'Whole pomfret marinated in spicy tandoori masala — grilled crisp and flavorful.', 19.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 9, 'oak-tree'),
  ('kebab-and-tandooris', 'Pathar Ka Gosht (Goat)', 'Traditional Hyderabadi-style goat slices cooked on hot stone with signature spices.', 20.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 10, 'oak-tree'),
  ('kebab-and-tandooris', 'DD Spl Non Veg Kebab Platter', 'A chef''s special assortment of our best kebabs — juicy, smoky, and irresistible.', 23.99, NULL, TRUE, FALSE, TRUE, NULL, 'active', 11, 'oak-tree'),
  ('kebab-and-tandooris', 'Paneer Tikka Kebab', 'Chargrilled paneer with bell peppers and onions — tandoor magic on a skewer.', 15.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 12, 'oak-tree'),
  ('kebab-and-tandooris', 'Makhmali Paneer Tikka', 'Soft paneer cubes marinated in spiced cream and roasted till melt-in-mouth.', 15.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 13, 'oak-tree'),
  ('kebab-and-tandooris', 'Chicken Tandoori', 'The classic red-hot tandoori chicken — smoky, spicy, and full of flavor.', 15.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 14, 'oak-tree'),
  ('kebab-and-tandooris', 'Mixed Veg Kebab (Gobi/Mushroom/Paneer/Peppers)', 'A colorful mix of grilled veggies and paneer tossed with tangy masala.', 16.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 15, 'oak-tree'),
  ('kebab-and-tandooris', 'Chicken Malai Kebab', 'Creamy, soft chicken marinated with cheese and herbs — a royal bite.', 16.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 16, 'oak-tree'),
  ('kebab-and-tandooris', 'Chicken Tikka Kebab', 'Classic tandoori delight — boneless chicken infused with rich spices and charred aroma.', 16.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 17, 'oak-tree'),
  ('naans-and-breads', 'Roti', 'Soft, homestyle whole wheat bread that pairs beautifully with all curries.', 2.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('naans-and-breads', 'Plain Naan', 'Classic tandoor-baked naan — soft, light, and perfect with every bite of gravy.', 2.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'oak-tree'),
  ('naans-and-breads', 'Butter Naan', 'Tandoor-baked, golden naan slathered in melted butter — a crowd favorite!', 3.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'oak-tree'),
  ('naans-and-breads', 'Garlic Naan', 'Fluffy naan roasted with fresh garlic and butter — pure aroma therapy for food lovers.', 3.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 4, 'oak-tree'),
  ('naans-and-breads', 'Chilli Garlic Naan', 'Spicy and flavorful naan brushed with garlic butter and green chili — for the bold palate.', 3.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 5, 'oak-tree'),
  ('naans-and-breads', 'Cheese Naan', 'Melted cheese tucked inside soft naan — indulgence in every bite.', 3.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 6, 'oak-tree'),
  ('naans-and-breads', 'Chilli Cheese Naan', 'A cheesy naan with a hint of heat — a delicious Indo-fusion twist.', 3.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 7, 'oak-tree'),
  ('naans-and-breads', 'Peshwari Naan', 'Sweet and nutty naan filled with coconut and dry fruits — a royal treat.', 3.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 8, 'oak-tree'),
  ('naans-and-breads', 'Onion Kulcha', 'Stuffed with caramelized onions and spices — soft, aromatic, and addictive.', 3.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 9, 'oak-tree'),
  ('naans-and-breads', 'Lachha Paratha', 'Buttery, multi-layered paratha that''s crisp, rich, and oh-so-satisfying.', 4.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 10, 'oak-tree'),
  ('naans-and-breads', 'Malabar Paratha', 'Flaky, layered paratha with crisp edges and soft layers — Kerala-style indulgence.', 4.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 11, 'oak-tree'),
  ('naans-and-breads', 'Bread Basket', 'An assorted mix of our best breads — naan, roti, paratha — a must for sharing!', 15.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 12, 'oak-tree'),
  ('vegetarian-entrees', 'Dal Tadka', 'Yellow lentils tempered with ghee, garlic, and cumin — simple, comforting, and loaded with homestyle flavor.', 12.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('vegetarian-entrees', 'Tomato Dal', 'Lentils simmered with tangy tomatoes and tempered with garlic and mustard seeds — simple yet full of flavor.', 12.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'oak-tree'),
  ('vegetarian-entrees', 'Mango Dal', 'A tangy South Indian-style lentil curry with raw mango — unique, comforting, and perfectly balanced.', 12.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'oak-tree'),
  ('vegetarian-entrees', 'Palak Dal', 'Lentils simmered with fresh spinach and garlic tempering — simple, healthy, and home-style comfort.', 12.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 4, 'oak-tree'),
  ('vegetarian-entrees', 'Dal Makhani', 'Slow-cooked black lentils simmered overnight in butter and cream — smooth, smoky, and irresistibly rich.', 12.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 5, 'oak-tree'),
  ('vegetarian-entrees', 'Shahi Paneer', 'Royal North Indian curry with paneer cooked in cashew-cream sauce — mild, creamy, and full of regal flavor.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 6, 'oak-tree'),
  ('vegetarian-entrees', 'Chana Saag', 'Protein-rich chickpeas cooked in creamy spinach gravy — hearty, healthy, and delicious.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 7, 'oak-tree'),
  ('vegetarian-entrees', 'Bendi Masala', 'Okra sautéed with onions, tomatoes, and Indian spices — flavorful, homestyle, and perfectly spiced.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 8, 'oak-tree'),
  ('vegetarian-entrees', 'Bendi Vepudu', 'Crispy fried okra tossed with South Indian spices — dry-fried, flavorful, and the perfect side dish.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 9, 'oak-tree'),
  ('vegetarian-entrees', 'Bendi Pulusu', 'Traditional Andhra-style tangy okra curry cooked in tamarind gravy — bold, flavorful, and deeply satisfying.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 10, 'oak-tree'),
  ('vegetarian-entrees', 'Kadai Bendi', 'Okra cooked with peppers and tomatoes in classic Kadai masala — spicy, fresh, and full of crunch.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 11, 'oak-tree'),
  ('vegetarian-entrees', 'Chana Masala', 'Chickpeas cooked in tangy tomato gravy with aromatic North Indian spices — spicy, hearty, and flavorful.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 12, 'oak-tree'),
  ('vegetarian-entrees', 'Paneer Burji Gravy', 'Scrambled paneer cooked with spiced onion-tomato gravy — flavorful, rustic, and delicious with naan.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 13, 'oak-tree'),
  ('vegetarian-entrees', 'Chettinad Mushroom', 'Mushrooms tossed in spicy, coconut-based Chettinad masala — hot, earthy, and packed with South Indian flavor.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 14, 'oak-tree'),
  ('vegetarian-entrees', 'Chettinad Paneer', 'Paneer tossed in bold Chettinad spices and coconut gravy — fiery, flavorful, and distinctly South Indian.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 15, 'oak-tree'),
  ('vegetarian-entrees', 'Chettinad Mix Veg', 'A spicy South Indian-style curry made with mixed vegetables and Chettinad masala — bold and aromatic.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 16, 'oak-tree'),
  ('vegetarian-entrees', 'Aloo Gobi', 'Classic North Indian curry of potatoes and cauliflower cooked with aromatic spices — comforting and homestyle.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 17, 'oak-tree'),
  ('vegetarian-entrees', 'Aloo Palak', 'Potatoes cooked in smooth spinach gravy — mild, creamy, and wholesome with every bite.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 18, 'oak-tree'),
  ('vegetarian-entrees', 'Aloo Mutter', 'A comforting blend of potatoes and peas simmered in a rich, flavorful gravy.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 19, 'oak-tree'),
  ('vegetarian-entrees', 'Kadai Veg', 'Mixed vegetables tossed in spicy tomato-based Kadai gravy — vibrant, flavorful, and full of zest.', 14.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 20, 'oak-tree'),
  ('vegetarian-entrees', 'Kadai Paneer', 'Paneer sautéed with bell peppers, onions, and Kadai spices — smoky, spicy, and full of flavor.', 14.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 21, 'oak-tree'),
  ('vegetarian-entrees', 'Kadai Mushroom', 'Tender mushrooms cooked in spicy tomato gravy with capsicum and onions — smoky and irresistibly bold.', 14.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 22, 'oak-tree'),
  ('vegetarian-entrees', 'Veg Korma', 'A mix of seasonal vegetables cooked in a mildly spiced cashew-coconut gravy — rich, aromatic, and perfectly balanced.', 14.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 23, 'oak-tree'),
  ('vegetarian-entrees', 'Paneer Korma', 'Paneer cubes cooked in a creamy, nut-based gravy — mild, rich, and packed with aromatic flavors.', 14.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 24, 'oak-tree'),
  ('vegetarian-entrees', 'Aloo Korma', 'Soft potatoes cooked in creamy, spiced coconut-cashew gravy — mild, aromatic, and perfectly comforting.', 14.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 25, 'oak-tree'),
  ('vegetarian-entrees', 'Mushroom Korma', 'Tender mushrooms cooked in creamy cashew-coconut gravy — rich, silky, and full of flavor.', 14.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 26, 'oak-tree'),
  ('vegetarian-entrees', 'Gutti Vankaya (Stuffed Brinjal)', 'Tender eggplants stuffed with spicy peanut masala and slow-cooked — a true Andhra delicacy.', 14.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 27, 'oak-tree'),
  ('vegetarian-entrees', 'Punjabi Palak Paneer', 'Soft paneer cooked in creamy spinach gravy with Punjabi spices — wholesome, earthy, and soul-satisfying.', 14.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 28, 'oak-tree'),
  ('vegetarian-entrees', 'Paneer Tikka Masala', 'Char-grilled paneer cubes simmered in rich, spiced tomato gravy — smoky, creamy, and bursting with flavor.', 14.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 29, 'oak-tree'),
  ('vegetarian-entrees', 'Paneer Butter Masala', 'Soft paneer simmered in buttery tomato gravy — mildly sweet, creamy, and everyone''s all-time favorite.', 14.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 30, 'oak-tree'),
  ('vegetarian-entrees', 'Navratan Korma', 'A royal medley of nine veggies and fruits cooked in creamy gravy — rich, mildly sweet, and full of color.', 14.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 31, 'oak-tree'),
  ('vegetarian-entrees', 'Malai Kofta', 'Golden-fried cottage cheese dumplings served in a luscious cashew cream sauce — rich, royal, and comforting.', 14.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 32, 'oak-tree'),
  ('vegetarian-entrees', 'Kaju Curry', 'Rich and creamy curry made with cashews in spiced tomato-onion gravy — decadent and flavorful.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 33, 'oak-tree'),
  ('non-vegetarian-entrees', 'Egg Bhurji Dry', 'Masala-scrambled eggs tossed with onions, green chili, and Indian spices.', 11.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 1, 'oak-tree'),
  ('non-vegetarian-entrees', 'Egg Pulusu', 'Eggs simmered in tangy tamarind gravy — a flavorful South Indian specialty.', 14.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 2, 'oak-tree'),
  ('non-vegetarian-entrees', 'Chicken Vindaloo', 'Spicy Goan chicken curry packed with vinegar-based masala heat.', 15.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 3, 'oak-tree'),
  ('non-vegetarian-entrees', 'Andhra Chicken Curry', 'Classic Andhra chicken bursting with fiery red chili and earthy aromas.', 15.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 4, 'oak-tree'),
  ('non-vegetarian-entrees', 'Chicken Mughlai', 'Royal Mughlai-style chicken in a luscious cream-cashew sauce.', 15.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 5, 'oak-tree'),
  ('non-vegetarian-entrees', 'Chicken Chettinad', 'A fiery South Indian curry with roasted coconut, black pepper, and bold masalas.', 15.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 6, 'oak-tree'),
  ('non-vegetarian-entrees', 'Methi Chicken', 'Chicken cooked with fresh fenugreek leaves in a mildly spiced creamy base.', 15.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 7, 'oak-tree'),
  ('non-vegetarian-entrees', 'Chicken Tikka Masala', 'Grilled chicken pieces in a rich tomato-onion gravy — the ultimate crowd-pleaser.', 15.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 8, 'oak-tree'),
  ('non-vegetarian-entrees', 'Chicken Karaikudi', 'Chettinad-style curry packed with roasted spices and bold flavors.', 15.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 9, 'oak-tree'),
  ('non-vegetarian-entrees', 'Butter Chicken', 'Creamy tomato gravy hugging juicy tandoori chicken — smooth, rich, and comforting.', 15.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 10, 'oak-tree'),
  ('non-vegetarian-entrees', 'Desi Chicken Curry (With Bone)', 'Tender bone-in chicken simmered in a rich, home-style masala gravy.', 15.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 11, 'oak-tree'),
  ('non-vegetarian-entrees', 'Railway Chicken Curry (With Bone)', 'British-era comfort curry cooked with whole spices and coconut hints.', 15.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 12, 'oak-tree'),
  ('non-vegetarian-entrees', 'DD Chef''s Special Chicken Curry (Homestyle)', 'A nostalgic homestyle curry cooked with hand-pounded spices and love.', 16.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 13, 'oak-tree'),
  ('non-vegetarian-entrees', 'Natu Kodi Curry', 'Country-style chicken cooked in traditional Andhra spices — rustic and full of flavor.', 17.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 14, 'oak-tree'),
  ('non-vegetarian-entrees', 'Venchina Chicken (Chicken Fry with Masala Rice)', 'Crispy, perfectly-fried chicken tossed in aromatic masala, served with flavorful masala rice for the ultimate comfort combo.', 19.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 15, 'oak-tree'),
  ('non-vegetarian-entrees', 'Hyderabadi Goat Curry', 'Slow-cooked goat curry simmered in Hyderabadi spice blend — authentic and aromatic.', 17.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 16, 'oak-tree'),
  ('non-vegetarian-entrees', 'Goat Vindaloo', 'Goan-style spicy goat curry with vinegar tang and deep spice tones.', 17.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 17, 'oak-tree'),
  ('non-vegetarian-entrees', 'Kashmiri Goat Rogan Josh', 'Aromatic Kashmiri goat curry with saffron and rich masala base.', 17.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 18, 'oak-tree'),
  ('non-vegetarian-entrees', 'Goat Chettinad', 'Fiery and peppery goat curry — a South Indian spice bomb.', 17.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 19, 'oak-tree'),
  ('non-vegetarian-entrees', 'Goat Mughalai', 'Rich Mughlai-inspired goat curry simmered in spiced yogurt and nuts.', 17.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 20, 'oak-tree'),
  ('non-vegetarian-entrees', 'DD Chef''s Special Mutton Curry (Homestyle)', 'Tender mutton slow-cooked in a spicy gravy — comfort food at its finest.', 18.99, NULL, FALSE, FALSE, TRUE, 2, 'active', 21, 'oak-tree'),
  ('non-vegetarian-entrees', 'Goan Fish Curry', 'Coconut-rich coastal fish curry — tangy, creamy, and irresistibly good.', 16.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 22, 'oak-tree'),
  ('non-vegetarian-entrees', 'Nellore Chepala Pulusu', 'Traditional Andhra fish curry slow-cooked in tangy tamarind gravy.', 16.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 23, 'oak-tree'),
  ('vegetarian-rice-and-biryani', 'Jeera Rice', 'Aromatic basmati rice tempered with roasted cumin seeds and ghee — simple, fragrant, and the perfect side.', 8.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('vegetarian-rice-and-biryani', 'Curd Rice', 'Comfort in every bite — chilled curd mixed with rice, tempered with mustard, ginger, and curry leaves.', 10.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'oak-tree'),
  ('vegetarian-rice-and-biryani', 'Veg Biryani', 'Aromatic basmati rice slow-cooked with fresh vegetables, mild spices, and herbs for a rich, soulful biryani experience.', 14.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'oak-tree'),
  ('vegetarian-rice-and-biryani', 'Chilli Mushroom Biryani', 'Spicy mushrooms tossed in chilli masala and layered with flavorful biryani rice — bold, saucy, and full of zest.', 14.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 4, 'oak-tree'),
  ('vegetarian-rice-and-biryani', 'Gobi Masala Biryani', 'Crispy cauliflower tossed in spicy masala and layered with aromatic rice — a bold, flavorful twist on classic biryani.', 14.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 5, 'oak-tree'),
  ('vegetarian-rice-and-biryani', 'Cut Mirchi Biryani', 'Crispy cut mirchi tossed in spicy masala and layered with fragrant biryani rice — fiery, crunchy, and irresistibly flavorful.', 14.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 6, 'oak-tree'),
  ('vegetarian-rice-and-biryani', 'Paneer Biryani', 'Soft paneer cubes layered with fragrant rice and house-blend biryani masala — rich, creamy, and irresistibly aromatic.', 15.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 7, 'oak-tree'),
  ('vegetarian-rice-and-biryani', 'Jack Fruit Biryani', 'Tender marinated jackfruit cooked like meat and layered with spiced, fragrant biryani rice.', 15.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 8, 'oak-tree'),
  ('vegetarian-rice-and-biryani', 'Gutti Vankaya Biryani', 'A Hyderabadi classic! Basmati rice cooked with stuffed brinjal and aromatic spices — smoky, spicy, and full of traditional flavor.', 15.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 9, 'oak-tree'),
  ('vegetarian-rice-and-biryani', 'Ulavacharu Biryani (Veg)', 'Fragrant basmati rice layered with slow-cooked horse gram (ulavacharu) gravy and mixed vegetables — earthy, rich, and authentically Andhra-style.', 15.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 10, 'oak-tree'),
  ('vegetarian-rice-and-biryani', 'Ulavacharu Biryani (Paneer)', 'Paneer cubes simmered in rich horse gram (ulavacharu) gravy and layered with fragrant biryani rice — earthy, creamy, and full of Andhra flavor.', 15.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 11, 'oak-tree'),
  ('vegetarian-rice-and-biryani', 'Gongura Biryani (Veg)', 'Zesty gongura masala cooked with fresh vegetables and aromatic rice — tangy, spicy, and authentically South Indian.', 15.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 12, 'oak-tree'),
  ('vegetarian-rice-and-biryani', 'Gongura Biryani (Paneer)', 'Tangy gongura (sorrel leaves) blended with paneer and layered in spicy biryani rice — a true Andhra delicacy.', 15.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 13, 'oak-tree'),
  ('vegetarian-rice-and-biryani', 'Veg Keema Biryani', 'Minced vegetable masala slow-cooked with aromatic basmati rice — spicy, flavorful, and a vegetarian favorite.', 15.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 14, 'oak-tree'),
  ('vegetarian-rice-and-biryani', 'Paneer Keema Biryani', 'Finely minced paneer cooked with robust biryani spices and layered with saffron rice — indulgent, spicy, and unique.', 15.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 15, 'oak-tree'),
  ('non-veg-biryani', 'Egg Biryani', 'Fluffy basmati rice layered with spiced boiled eggs and aromatic masala — a hearty, flavor-packed family favorite.', 14.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('non-veg-biryani', 'Chicken Dum Biryani', 'Tender chicken simmered with aromatic spices and saffron basmati rice — pure Hyderabadi perfection in every bite.', 15.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 2, 'oak-tree'),
  ('non-veg-biryani', 'Ulavacharu Chicken Dum Biryani', 'Slow-cooked chicken biryani blended with signature ulavacharu sauce — earthy and unforgettable.', 16.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 3, 'oak-tree'),
  ('non-veg-biryani', 'Vijayawada Chicken Biryani (Boneless)', 'Boneless chicken in fiery Vijayawada-style spice mix layered with fragrant rice — a bold Andhra favorite.', 17.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 4, 'oak-tree'),
  ('non-veg-biryani', 'Gongura Chicken Biryani', 'Spicy, tangy gongura-flavored chicken biryani — a perfect Andhra specialty.', 16.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 5, 'oak-tree'),
  ('non-veg-biryani', 'Chicken Biryani (Boneless)', 'Succulent boneless chicken cooked to perfection with layered fragrant rice — soft, spicy, and satisfying.', 17.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 6, 'oak-tree'),
  ('non-veg-biryani', 'Chicken Fry Piece Biryani (Bone-In)', 'Aromatic basmati rice layered with bone-in chicken fry pieces — a true Desi Dhamaka signature dish.', 17.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 7, 'oak-tree'),
  ('non-veg-biryani', 'Chicken Fry Piece Biryani (Boneless)', 'Crispy boneless chicken fry blended with aromatic biryani rice — every bite a burst of spice.', 18.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 8, 'oak-tree'),
  ('non-veg-biryani', 'DD Special Chicken Biryani (Bone-In)', 'House-special biryani bursting with flavors of chicken, caramelized onions, mint & chef''s secret masala.', 18.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 9, 'oak-tree'),
  ('non-veg-biryani', 'DD Special Chicken Biryani (Boneless)', 'Chef''s boneless special — juicy chicken layered with rich masala and fragrant rice.', 19.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 10, 'oak-tree'),
  ('non-veg-biryani', 'DD Spl Natu Kodi Biryani', 'Traditional country chicken cooked with rustic Andhra spices — authentic and soul-satisfying.', 23.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 11, 'oak-tree'),
  ('non-veg-biryani', 'Mutton Dum Biryani', 'Slow-cooked mutton layered with fragrant basmati rice, infused with rich spices and ghee — the royal Hyderabadi classic.', 18.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 12, 'oak-tree'),
  ('non-veg-biryani', 'Gongura Mutton Biryani', 'Tangy gongura and spiced mutton layered in biryani rice — Andhra-style with a twist.', 19.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 13, 'oak-tree'),
  ('non-veg-biryani', 'Ulavacharu Mutton Dum Biryani', 'Creamy horse gram (ulavacharu) meets spicy mutton dum biryani — smoky, tangy, and indulgent.', 19.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 14, 'oak-tree'),
  ('non-veg-biryani', 'Goat Kheema Biryani', 'Minced goat meat cooked in bold masala and layered with basmati rice — a must-try for biryani lovers.', 22.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 15, 'oak-tree'),
  ('non-veg-biryani', 'DD Spl Nalli Gosht Biryani', 'Tender lamb shank biryani slow-cooked in royal spices — rich, melt-in-mouth and irresistibly aromatic.', 27.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 16, 'oak-tree'),
  ('non-veg-biryani', 'Mamsam Roast Biryani (Bone-In)', 'Bone-in mutton roasted with spices and layered with aromatic rice — fiery and flavorful.', 19.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 17, 'oak-tree'),
  ('non-veg-biryani', 'Mamsam Roast Biryani (Boneless)', 'Boneless mutton slow-roasted and mixed with biryani rice — bold, meaty, and satisfying.', 20.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 18, 'oak-tree'),
  ('non-veg-biryani', 'Fish Biryani', 'Fresh fish fillets cooked in flavorful biryani masala and layered with basmati rice — soft and aromatic.', 18.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 19, 'oak-tree'),
  ('non-veg-biryani', 'Shrimp Fry Biryani', 'Golden fried shrimp tossed in spicy masala and layered with biryani rice — coastal flavor meets Hyderabadi aroma.', 18.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 20, 'oak-tree'),
  ('non-veg-biryani', 'Mutton Fry Piece Biryani (Bone-In)', 'Bone-in mutton cooked in authentic Hyderabadi dum style — juicy, spicy, and unforgettable.', 18.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 21, 'oak-tree'),
  ('non-veg-biryani', 'Mutton Fry Piece Biryani (Boneless)', 'Juicy boneless mutton pieces fried and mixed with spiced biryani rice — rich, flavorful, and indulgent.', 20.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 22, 'oak-tree'),
  ('non-veg-biryani', 'Mutton Keema Biryani', 'Minced mutton cooked with rich masala and basmati rice — hearty and full-bodied.', 22.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 23, 'oak-tree'),
  ('dd-special-mandi', 'Veg Keema Mandi (Single)', NULL, 25.99, NULL, TRUE, FALSE, TRUE, NULL, 'active', 1, 'oak-tree'),
  ('dd-special-mandi', 'Veg Keema Mandi (Half)', NULL, 42.99, NULL, TRUE, FALSE, TRUE, NULL, 'active', 2, 'oak-tree'),
  ('dd-special-mandi', 'Veg Keema Mandi (Full)', NULL, 66.99, NULL, TRUE, FALSE, TRUE, NULL, 'active', 3, 'oak-tree'),
  ('dd-special-mandi', 'Gutti Vankaya Mandi (Single)', NULL, 25.99, NULL, TRUE, FALSE, TRUE, NULL, 'active', 4, 'oak-tree'),
  ('dd-special-mandi', 'Gutti Vankaya Mandi (Half)', NULL, 42.99, NULL, TRUE, FALSE, TRUE, NULL, 'active', 5, 'oak-tree'),
  ('dd-special-mandi', 'Gutti Vankaya Mandi (Full)', NULL, 66.99, NULL, TRUE, FALSE, TRUE, NULL, 'active', 6, 'oak-tree'),
  ('dd-special-mandi', 'Paneer Mandi (Single)', NULL, 25.99, NULL, TRUE, FALSE, TRUE, NULL, 'active', 7, 'oak-tree'),
  ('dd-special-mandi', 'Paneer Mandi (Half)', NULL, 42.99, NULL, TRUE, FALSE, TRUE, NULL, 'active', 8, 'oak-tree'),
  ('dd-special-mandi', 'Paneer Mandi (Full)', NULL, 66.99, NULL, TRUE, FALSE, TRUE, NULL, 'active', 9, 'oak-tree'),
  ('dd-special-mandi', 'Egg Mandi (Single)', NULL, 25.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 10, 'oak-tree'),
  ('dd-special-mandi', 'Egg Mandi (Half)', NULL, 45.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 11, 'oak-tree'),
  ('dd-special-mandi', 'Egg Mandi (Full)', NULL, 65.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 12, 'oak-tree'),
  ('dd-special-mandi', 'Chicken Mandi (Single)', NULL, 25.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 13, 'oak-tree'),
  ('dd-special-mandi', 'Chicken Mandi (Half)', NULL, 45.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 14, 'oak-tree'),
  ('dd-special-mandi', 'Chicken Mandi (Full)', NULL, 75.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 15, 'oak-tree'),
  ('dd-special-mandi', 'NatuKodi Mandi (Single)', NULL, 25.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 16, 'oak-tree'),
  ('dd-special-mandi', 'NatuKodi Mandi (Half)', NULL, 45.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 17, 'oak-tree'),
  ('dd-special-mandi', 'NatuKodi Mandi (Full)', NULL, 80.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 18, 'oak-tree'),
  ('dd-special-mandi', 'Goat Mandi (Single)', NULL, 25.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 19, 'oak-tree'),
  ('dd-special-mandi', 'Goat Mandi (Half)', NULL, 45.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 20, 'oak-tree'),
  ('dd-special-mandi', 'Goat Mandi (Full)', NULL, 80.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 21, 'oak-tree'),
  ('dd-special-mandi', 'Fish Mandi (Single)', NULL, 25.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 22, 'oak-tree'),
  ('dd-special-mandi', 'Fish Mandi (Half)', NULL, 45.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 23, 'oak-tree'),
  ('dd-special-mandi', 'Fish Mandi (Full)', NULL, 80.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 24, 'oak-tree'),
  ('dd-special-mandi', 'DD Special Nalli Gosht Mandi (Single)', NULL, 25.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 25, 'oak-tree'),
  ('dd-special-mandi', 'DD Special Nalli Gosht Mandi (Half)', NULL, 55.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 26, 'oak-tree'),
  ('dd-special-mandi', 'DD Special Nalli Gosht Mandi (Full)', NULL, 90.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 27, 'oak-tree'),
  ('dd-special-mandi', 'Shrimp Mandi (Single)', NULL, 25.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 28, 'oak-tree'),
  ('dd-special-mandi', 'Shrimp Mandi (Half)', NULL, 45.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 29, 'oak-tree'),
  ('dd-special-mandi', 'Shrimp Mandi (Full)', NULL, 90.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 30, 'oak-tree'),
  ('dd-special-mandi', 'Mixed Full Mandi (Choice of Two)', NULL, 85.99, NULL, TRUE, FALSE, TRUE, NULL, 'active', 31, 'oak-tree'),
  ('dd-special-mandi', 'Extra Mandi Rice', NULL, 10.99, NULL, TRUE, FALSE, TRUE, NULL, 'active', 32, 'oak-tree'),
  ('dd-specials', 'Goat Haleem', 'Slow-cooked to perfection — tender goat blended with wheat, lentils, and aromatic spices. Creamy, hearty, and rich in authentic Hyderabadi flavor.', 17.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('dd-specials', 'DD Chef''s Special Tawa Fish', 'Bone-in fish fillet seared to perfection with Chef''s signature masala — crisp outside, soft inside, and bursting with flavor.', 19.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 2, 'oak-tree'),
  ('dd-specials', 'Nalli Gosht Roast', 'Tender lamb shanks slow-roasted in rich gravy — fall-off-the-bone perfection loaded with royal Hyderabadi taste.', 20.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 3, 'oak-tree'),
  ('dd-specials', 'DD Chef''s Special Tawa Fish (Boneless)', 'Fresh boneless fish grilled on a hot tawa with house-blend spices — smoky, juicy, and absolutely addictive.', 20.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 4, 'oak-tree'),
  ('dd-family-packs', 'Veg Biryani Family Pack', 'Aromatic basmati rice cooked with fresh vegetables, mint, and traditional spices.', 40, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('dd-family-packs', 'Paneer Biryani Family Pack', 'Soft paneer cubes cooked in fragrant biryani masala and layered with saffron rice.', 50, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'oak-tree'),
  ('dd-family-packs', 'Egg Dum Biryani Family Pack', 'Fluffy basmati rice layered with spiced boiled eggs and aromatic masala.', 40.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 3, 'oak-tree'),
  ('dd-family-packs', 'Hyd Chicken Dum Biryani Family Pack', 'Classic Hyderabadi dum biryani — aromatic basmati rice layered with tender chicken.', 45, NULL, FALSE, FALSE, FALSE, NULL, 'active', 4, 'oak-tree'),
  ('dd-family-packs', 'Ulavacharu Chicken Dum Biryani Family Pack', 'Tender chicken layered with biryani rice and simmered in authentic ulavacharu gravy.', 47.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 5, 'oak-tree'),
  ('dd-family-packs', 'Vijayawada Boneless Biryani Family Pack', 'A fiery South Indian special with boneless chicken cooked in bold masala.', 55, NULL, TRUE, FALSE, FALSE, 2, 'active', 6, 'oak-tree'),
  ('dd-family-packs', 'DD Spl Chicken Biryani Family Pack', 'Our signature Desi Dhamaka special — juicy chicken, aromatic rice, and secret spices.', 55, NULL, FALSE, FALSE, TRUE, NULL, 'active', 7, 'oak-tree'),
  ('dd-family-packs', 'Ulavacharu Chicken Boneless Biryani Family Pack', 'Boneless chicken cooked in rich horse gram (ulavacharu) gravy and layered with biryani rice.', 56, NULL, FALSE, FALSE, FALSE, NULL, 'active', 8, 'oak-tree'),
  ('dd-family-packs', 'Ulavacharu Goat Dum Biryani Family Pack', 'Slow-cooked goat meat infused with earthy ulavacharu flavors — a rich Andhra-style biryani.', 61, NULL, FALSE, FALSE, FALSE, NULL, 'active', 9, 'oak-tree'),
  ('dd-family-packs', 'Goat Dum Biryani Family Pack', 'Traditional Hyderabadi-style dum biryani with tender goat meat and fragrant basmati rice.', 60, NULL, FALSE, FALSE, FALSE, NULL, 'active', 10, 'oak-tree'),
  ('dd-family-packs', 'Shrimp Biryani Family Pack', 'Succulent shrimp simmered in spiced biryani masala and layered with long-grain rice.', 60, NULL, FALSE, FALSE, FALSE, NULL, 'active', 11, 'oak-tree'),
  ('dd-family-packs', 'Mamsam Roast Biryani Family Pack', 'Tender boneless mutton roasted in rich masala and layered with aromatic biryani rice.', 60, NULL, FALSE, FALSE, FALSE, NULL, 'active', 12, 'oak-tree'),
  ('dd-family-packs', 'Gongura Biryani Family Pack', 'Zesty gongura masala cooked with fresh vegetables and aromatic rice — tangy and spicy.', 45, NULL, TRUE, FALSE, FALSE, 2, 'active', 13, 'oak-tree'),
  ('dd-family-packs', 'JackFruit Biryani Family Pack', 'Tender marinated jackfruit cooked like meat and layered with spiced, fragrant biryani rice.', 45, NULL, TRUE, FALSE, FALSE, NULL, 'active', 14, 'oak-tree'),
  ('dd-family-packs', 'FryPiece Chicken Biryani Family Pack', 'Aromatic basmati rice layered with chicken fry pieces — a true Desi Dhamaka signature.', 55, NULL, FALSE, FALSE, FALSE, NULL, 'active', 15, 'oak-tree'),
  ('dd-family-packs', 'Goat FryPiece Biryani Family Pack', 'Tender mutton pieces fried and mixed with spiced rice — rich, flavorful, and indulgent.', 60, NULL, FALSE, FALSE, FALSE, NULL, 'active', 16, 'oak-tree'),
  ('dd-family-packs', 'Goat Boneless Biryani Family Pack', 'Soft boneless goat cooked in rich spices and blended with fragrant biryani rice.', 62, NULL, FALSE, FALSE, FALSE, NULL, 'active', 17, 'oak-tree'),
  ('indo-chinese', 'Veg Noodles', 'Soft noodles tossed with colorful vegetables and house-made sauces — light, flavorful, and satisfying.', 11.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('indo-chinese', 'Egg Noodles', 'Stir-fried noodles with scrambled egg, soy, and veggies — perfect for egg lovers!', 11.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 2, 'oak-tree'),
  ('indo-chinese', 'Chicken Noodles', 'Classic stir-fried noodles with tender chicken and crunchy veggies — comforting and full of taste.', 11.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 3, 'oak-tree'),
  ('indo-chinese', 'Veg Fried Rice', 'Simple yet delicious — wok-tossed rice loaded with veggies and authentic Indo-Chinese flavors.', 12.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 4, 'oak-tree'),
  ('indo-chinese', 'Egg Fried Rice', 'Fluffy rice blended with scrambled eggs, veggies, and spices — a delicious quick meal.', 12.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 5, 'oak-tree'),
  ('indo-chinese', 'Chicken Fried Rice', 'Aromatic rice wok-tossed with juicy chicken, egg, and veggies — the ultimate comfort meal.', 12.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 6, 'oak-tree'),
  ('indo-chinese', 'Veg Schezwan Fried Rice', 'Wok-tossed rice infused with chili-garlic Schezwan sauce and crunchy vegetables.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 7, 'oak-tree'),
  ('indo-chinese', 'Egg Schezwan Fried Rice', 'Egg fried rice meets Schezwan spice — bold, saucy, and unforgettable!', 13.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 8, 'oak-tree'),
  ('indo-chinese', 'Chicken Schezwan Fried Rice', 'Spicy Schezwan rice bursting with flavors of garlic, chili, and tender chicken.', 13.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 9, 'oak-tree'),
  ('indo-chinese', 'Schezwan Shrimp Fried Rice', 'Spicy, zesty rice with shrimp and Schezwan sauce — a fiery twist for seafood lovers.', 15.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 10, 'oak-tree'),
  ('indo-chinese', 'Shrimp Fried Rice', 'Juicy shrimp tossed with rice, soy, and aromatic spices — ocean-fresh goodness in every bite.', 15.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 11, 'oak-tree'),
  ('indo-chinese', 'Street Food Fried Rice', 'Inspired by Indian street flavors — smoky, spicy, and irresistibly tasty in every bite!', 15.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 12, 'oak-tree'),
  ('indo-chinese', 'Chicken Hakka Noodles', 'Stir-fried noodles tossed with succulent chicken, veggies, and signature Indo-Chinese flavors.', 13.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 13, 'oak-tree'),
  ('indo-chinese', 'Veg Hakka Noodles', 'Stir-fried noodles tossed with crunchy veggies and Indo-Chinese seasonings for a tasty, street-style treat.', 11.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 14, 'oak-tree'),
  ('indo-chinese', 'Egg Hakka Noodles', 'Stir-fried noodles tossed with fluffy eggs, veggies, and flavorful Indo-Chinese seasoning.', 12.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 15, 'oak-tree'),
  ('snacks', 'Roasted Peanut Masala', 'Crispy roasted peanuts mixed with zesty masala — perfect for crunchy cravings.', 8.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('snacks', 'Samosa', 'Crispy pastry stuffed with spiced potatoes — the all-time favorite Indian snack.', 8.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'oak-tree'),
  ('snacks', 'Cut Mirchi', 'Crispy fried green chilies sliced and seasoned to perfection — bold, spicy, and addictive!', 9.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 3, 'oak-tree'),
  ('snacks', 'Mirchi Bajji', 'Street-style hot chili fritters coated in gram flour — crunchy outside, soft inside.', 9.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 4, 'oak-tree'),
  ('snacks', 'Kaju Fry', 'Crunchy cashews tossed with pepper and house spices — a royal and irresistible snack.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 5, 'oak-tree'),
  ('snacks', 'Egg Bonda (3 Pcs)', 'Boiled eggs dipped in spiced batter and fried golden brown — crispy, rich, and satisfying.', 10.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 6, 'oak-tree'),
  ('chai-and-coffee', 'Masala Chai', 'A comforting blend of tea, milk, and Indian spices — a cup of warmth in every sip.', 1.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('chai-and-coffee', 'Irani Chai', 'Traditional Hyderabad-style tea — strong, creamy, and irresistibly aromatic.', 2.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'oak-tree'),
  ('chai-and-coffee', 'Desi Chai', 'A warm, aromatic cup of traditional Indian chai brewed with bold spices.', 1.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'oak-tree'),
  ('chai-and-coffee', 'Instant Coffee (Bru)', 'Quick, strong, and smooth — India''s favorite instant coffee delight.', 2.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 4, 'oak-tree'),
  ('chai-and-coffee', 'Iyengar Filter Coffee', 'South Indian-style filter coffee, brewed to perfection with rich aroma and flavor.', 3.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 5, 'oak-tree'),
  ('soft-drinks', 'Butter Milk', 'Cool, spiced yogurt drink — refreshing and perfect after a hearty meal.', 3.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('soft-drinks', 'Mango Lassi', 'Rich and creamy yogurt drink blended with ripe mangoes — a perfect desi cooler.', 4.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'oak-tree'),
  ('soft-drinks', 'Sweet Lassi', 'Creamy, sweet, and soothing — a traditional Indian favorite.', 4.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'oak-tree'),
  ('soft-drinks', 'Salt Lassi', 'A savory yogurt drink that cools you from the inside out.', 4.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 4, 'oak-tree'),
  ('soft-drinks', 'Fresh Lemon Soda', 'Freshly squeezed lemon with sparkling soda — sweet, salty, or both!', 3.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 5, 'oak-tree'),
  ('soft-drinks', 'Goli Soda', 'Old-school Indian soda pop — fun, fizzy, and full of nostalgia!', 3.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 6, 'oak-tree'),
  ('soft-drinks', 'Thumps Up Can', 'India''s bold cola with a strong, fizzy kick — perfect with spicy dishes!', 2.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 7, 'oak-tree'),
  ('soft-drinks', 'Topo Chico', 'The premium sparkling mineral water with a crisp, refreshing fizz.', 3.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 8, 'oak-tree'),
  ('soft-drinks', 'Poland Spring Water Bottle', 'Fresh, clean water to keep you cool and refreshed.', 0.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 9, 'oak-tree'),
  ('soft-drinks', 'Coke Can', 'The timeless favorite — fizzy, cool, and always satisfying.', 1.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 10, 'oak-tree'),
  ('soft-drinks', 'Coke Bottle (20oz)', 'Refreshing, bubbly Coke served chilled for the perfect sip with any meal.', 3.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 11, 'oak-tree'),
  ('soft-drinks', 'Diet Coke Can', 'Light, bubbly, and refreshing — zero calories, all the flavor.', 1.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 12, 'oak-tree'),
  ('soft-drinks', 'Diet Coke Bottle', 'All the Diet Coke taste in a chilled bottle — zero calories, full fizz.', 3.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 13, 'oak-tree'),
  ('soft-drinks', 'Zero Coke Can', 'All the Coca-Cola taste with none of the sugar.', 1.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 14, 'oak-tree'),
  ('soft-drinks', 'Zero Coke Bottle', 'Zero sugar, full Coca-Cola flavor — now in a bottle.', 3.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 15, 'oak-tree'),
  ('soft-drinks', 'Sprite Can', 'Crisp lemon-lime fizz that hits refresh instantly.', 1.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 16, 'oak-tree'),
  ('soft-drinks', 'Ginger Ale Can', 'Light, bubbly ginger ale with a crisp, clean taste.', 1.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 17, 'oak-tree'),
  ('soft-drinks', 'Limca Can', 'Zesty lemon-lime Indian soda — light, tangy, and refreshing.', 2.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 18, 'oak-tree'),
  ('soft-drinks', 'Canada Dry Can', 'Smooth and crisp ginger ale — the classic go-to mixer and refresher.', 1.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 19, 'oak-tree'),
  ('soft-drinks', 'Sprite Bottle', 'Lemon-lime refreshment in a chilled bottle — crisp and satisfying.', 3.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 20, 'oak-tree'),
  ('soft-drinks', 'Ginger Ale Bottle', 'Smooth ginger ale served in a chilled bottle — perfect with any meal.', 3.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 21, 'oak-tree'),
  ('soft-drinks', 'Mexican Coke', 'Made with real cane sugar — richer, smoother, and extra delicious!', 4.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 22, 'oak-tree'),
  ('soft-drinks', 'Canada Dry', 'Classic ginger ale in a bottle — light, bubbly, and refreshingly smooth.', 2.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 23, 'oak-tree'),
  ('soft-drinks', 'Limca', 'Tangy lemon-lime Indian soda — refreshing and full of zest.', 2.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 24, 'oak-tree'),
  ('soft-drinks', 'Smart Water', 'Hydration with a hint of purity — stay smart, stay refreshed.', 3.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 25, 'oak-tree'),
  ('soft-drinks', 'Topo Chico Can', 'Crisp sparkling mineral water in a convenient can — refreshing fizz on the go.', 2.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 26, 'oak-tree'),
  ('kids-menu', 'French Fries', 'Crispy golden fries served hot — the ultimate kid-favorite snack!', 8.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('kids-menu', 'Chicken Nuggets', 'Tender, juicy chicken bites coated in a crunchy golden crust — fun to eat and full of flavor.', 10.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 2, 'oak-tree'),
  ('kids-menu', 'DD Mini Kulcha', 'Soft, buttery mini kulchas served with mild curry — a delightful desi treat made just for little tummies!', 10.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'oak-tree'),
  ('desserts', 'Ice Cream', 'Chilled scoops of creamy delight — the perfect finish to your meal.', 5.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('desserts', 'Gulab Jamun', 'Soft, golden dumplings soaked in warm sugar syrup — a timeless Indian classic.', 5.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'oak-tree'),
  ('desserts', 'Rasmalai', 'Soft cheese patties soaked in creamy, saffron milk — melt-in-mouth perfection.', 5.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'oak-tree'),
  ('desserts', 'Carrot Halwa', 'Slow-cooked carrots in milk and ghee, topped with nuts — pure indulgence.', 6.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 4, 'oak-tree'),
  ('desserts', 'Double Ka Meetha', 'Hyderabadi bread pudding made with ghee, milk, and saffron — rich and royal.', 7.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 5, 'oak-tree'),
  ('desserts', 'Sorakaya Halwa', 'Delicately flavored bottle gourd halwa — light, rich, and wholesome.', 7.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 6, 'oak-tree'),
  ('desserts', 'Gummadikaya Halwa', 'A healthy twist on tradition — earthy pumpkin cooked in milk and ghee.', 7.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 7, 'oak-tree'),
  ('desserts', 'DD Special Sweet', 'Chef''s special house dessert — a sweet surprise worth saving room for.', 11.99, NULL, TRUE, FALSE, TRUE, NULL, 'active', 8, 'oak-tree'),
  ('desserts', 'Beetroot Halwa', 'A healthy twist on tradition — earthy beetroot cooked in milk and ghee.', 7.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 9, 'oak-tree'),
  ('desserts', 'Icecream Gulabjamun', 'Warm gulab jamun paired with cold ice cream — a heavenly fusion dessert.', 5.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 10, 'oak-tree'),
  ('thali', 'Veg Thali', 'A wholesome South Indian platter with flavorful curries, dal, rice, roti, and sweets — a symphony of flavors.', 18.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('thali', 'Non Veg Thali', 'A hearty feast featuring signature meat curries, rice, roti, and sides — crafted for true food lovers.', 21.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'oak-tree')
) AS v(cat_slug, name, description, price, image, veg, popular, chef_special, spice_level, status, display_order, location_id)
JOIN cat c ON c.slug = v.cat_slug
WHERE NOT EXISTS (
  SELECT 1 FROM public.menu_items mi
  JOIN public.menu_categories mc ON mc.id = mi.category_id
  WHERE mc.location_id = 'oak-tree' AND mc.slug = v.cat_slug AND mi.name = v.name
);

COMMIT;
