-- ============================================================
-- Desi Dhamaka — menu seed for Oak Tree
-- location_id: oak-tree
-- Source: ChefGaa API outlet 70 (order_type 106)
-- Order URL: https://order.chefgaa.com/store/desi-dhamaka?order_type=108
-- Categories: 29 · Items: 433
-- Run supabase/clear_menu_locations.sql BEFORE this file.
-- Idempotent: re-running will not duplicate rows.
-- ============================================================

BEGIN;

-- Categories
INSERT INTO public.menu_categories (name, slug, image, display_order, status, location_id)
VALUES
  ('Pulav', 'pulav', NULL, 1, 'active', 'oak-tree'),
  ('Add Ons', 'add-ons', NULL, 2, 'active', 'oak-tree'),
  ('Quick Lunch', 'quick-lunch', NULL, 3, 'active', 'oak-tree'),
  ('Ramdan Specials', 'ramdan-specials', NULL, 4, 'active', 'oak-tree'),
  ('Mocktails', 'mocktails', NULL, 5, 'active', 'oak-tree'),
  ('Soups', 'soups', NULL, 6, 'active', 'oak-tree'),
  ('Vegetarian Appetizers', 'vegetarian-appetizers', NULL, 7, 'active', 'oak-tree'),
  ('Vegetarian Entrees', 'vegetarian-entrees', NULL, 8, 'active', 'oak-tree'),
  ('Vegetarian Rice & Biryanis', 'vegetarian-rice-and-biryanis', NULL, 9, 'active', 'oak-tree'),
  ('DD Family Packs (To Go Only)', 'dd-family-packs-to-go-only', NULL, 10, 'active', 'oak-tree'),
  ('Cooker Pulav', 'cooker-pulav', NULL, 11, 'active', 'oak-tree'),
  ('Naans', 'naans', NULL, 12, 'active', 'oak-tree'),
  ('Kebab and Tandooris', 'kebab-and-tandooris', NULL, 13, 'active', 'oak-tree'),
  ('Non-Veg Entrees', 'non-veg-entrees', NULL, 14, 'active', 'oak-tree'),
  ('Non-Veg Appetizers', 'non-veg-appetizers', NULL, 15, 'active', 'oak-tree'),
  ('South Indian Special', 'south-indian-special', NULL, 16, 'active', 'oak-tree'),
  ('Biryanis', 'biryanis', NULL, 17, 'active', 'oak-tree'),
  ('DD Special Mandi', 'dd-special-mandi', NULL, 18, 'active', 'oak-tree'),
  ('DD Specials', 'dd-specials', NULL, 19, 'active', 'oak-tree'),
  ('Kids Menu', 'kids-menu', NULL, 20, 'active', 'oak-tree'),
  ('Snacks', 'snacks', NULL, 21, 'active', 'oak-tree'),
  ('Indo Chinese', 'indo-chinese', NULL, 22, 'active', 'oak-tree'),
  ('Soft Drinks', 'soft-drinks', NULL, 23, 'active', 'oak-tree'),
  ('Chai', 'chai', NULL, 24, 'active', 'oak-tree'),
  ('Coffee', 'coffee', NULL, 25, 'active', 'oak-tree'),
  ('Desserts', 'desserts', NULL, 26, 'active', 'oak-tree'),
  ('Thalis', 'thalis', NULL, 27, 'active', 'oak-tree'),
  ('Weekend Specials', 'weekend-specials', NULL, 28, 'active', 'oak-tree'),
  ('Tuesday Offers', 'tuesday-offers', NULL, 29, 'active', 'oak-tree')
ON CONFLICT (location_id, slug) DO NOTHING;

-- Menu items
WITH cat AS (
  SELECT id, slug FROM public.menu_categories WHERE location_id = 'oak-tree'
)
INSERT INTO public.menu_items (category_id, name, description, price, image, veg, popular, chef_special, spice_level, status, display_order, location_id)
SELECT c.id, v.name, v.description, v.price, v.image, v.veg, v.popular, v.chef_special, v.spice_level, v.status::public.content_status, v.display_order, v.location_id
FROM (VALUES
  ('pulav', 'Natukodi Pulav', NULL, 24.99, NULL, FALSE, FALSE, FALSE, NULL, 'inactive', 1, 'oak-tree'),
  ('pulav', 'Panner Pulav', NULL, 16.99, NULL, TRUE, FALSE, FALSE, NULL, 'inactive', 2, 'oak-tree'),
  ('pulav', 'Egg Pulav', NULL, 16.99, NULL, FALSE, FALSE, FALSE, NULL, 'inactive', 3, 'oak-tree'),
  ('pulav', 'Guttivankay Pulav', NULL, 16.99, NULL, TRUE, FALSE, FALSE, NULL, 'inactive', 4, 'oak-tree'),
  ('pulav', 'Mutton Boneless Pulav', NULL, 22.99, NULL, FALSE, FALSE, FALSE, NULL, 'inactive', 5, 'oak-tree'),
  ('pulav', 'Mutton Bone-in Pulav', NULL, 20.99, NULL, FALSE, FALSE, FALSE, NULL, 'inactive', 6, 'oak-tree'),
  ('pulav', 'Boneless Chicken Pulav', NULL, 19.99, NULL, FALSE, FALSE, FALSE, NULL, 'inactive', 7, 'oak-tree'),
  ('pulav', 'Bone-in Chicken Pulav', NULL, 18.99, NULL, FALSE, FALSE, FALSE, NULL, 'inactive', 8, 'oak-tree'),
  ('add-ons', 'Side Of Onions&lemon', NULL, 1.49, NULL, TRUE, FALSE, FALSE, NULL, 'inactive', 1, 'oak-tree'),
  ('add-ons', 'Extra Salan', NULL, 0.99, NULL, TRUE, FALSE, FALSE, NULL, 'inactive', 2, 'oak-tree'),
  ('add-ons', 'Extra Raita', NULL, 0.99, NULL, TRUE, FALSE, FALSE, NULL, 'inactive', 3, 'oak-tree'),
  ('quick-lunch', 'Non Veg Quick Lunch', NULL, 10.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('quick-lunch', 'Veg Quick Lunch', NULL, 9.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'oak-tree'),
  ('ramdan-specials', 'Ramdan GoatDumBiryani FamilyPack', NULL, 77.78, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('ramdan-specials', 'Ramdan ChickenDum Biryani FamilyPack', NULL, 70.78, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'oak-tree'),
  ('mocktails', 'Bollywood Dreams', NULL, 9.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('mocktails', 'Sunrise Mocktail', NULL, 9.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'oak-tree'),
  ('mocktails', 'Virgin Mojito', NULL, 9.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'oak-tree'),
  ('soups', 'Veg Sweet Corn Soup', 'A comforting blend of sweet corn, fresh vegetables, and rich broth — creamy, mildly seasoned, and soul-soothing in every spoonful.', 8.31, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('soups', 'Chicken Manchow Soup', 'A spicy, tangy Indo-Chinese favorite — loaded with shredded chicken, crunchy veggies, and topped with crispy noodles for that perfect crunch.', 8.31, NULL, FALSE, FALSE, FALSE, 2, 'active', 2, 'oak-tree'),
  ('soups', 'Natu Kodi Soup', 'Authentic country chicken slow-cooked with bold spices and herbs — a traditional South Indian remedy that’s as flavorful as it is hearty.', 9.35, NULL, FALSE, FALSE, FALSE, NULL, 'active', 3, 'oak-tree'),
  ('soups', 'Chicken Sweet Corn Soup', 'Tender chicken and golden corn kernels simmered in a smooth, savory broth — the perfect balance of comfort and flavor.', 8.31, NULL, FALSE, FALSE, FALSE, NULL, 'active', 4, 'oak-tree'),
  ('soups', 'Chicken Hot & Sour Soup', 'A fiery, tangy soup bursting with bold Indo-Chinese flavors — shredded chicken, veggies, and spice that warms you up instantly.', 8.31, NULL, FALSE, FALSE, FALSE, 2, 'active', 5, 'oak-tree'),
  ('soups', 'Veg  Manchow Soup', 'A hot and spicy delight packed with crunchy vegetables and zesty flavors — finished with crispy noodles for that ultimate kick.', 8.31, NULL, TRUE, FALSE, FALSE, 2, 'active', 6, 'oak-tree'),
  ('soups', 'Goat Paya (Aattukal) Soup', 'Traditional bone broth made from slow-cooked goat trotters — rich, nourishing, and bursting with authentic homemade flavor.', 9.35, NULL, FALSE, FALSE, FALSE, NULL, 'active', 7, 'oak-tree'),
  ('soups', 'Veg Hot & Sour Soup', 'A bold mix of tangy, spicy, and savory — packed with fresh vegetables and exotic Asian flavors to awaken your taste buds.', 8.31, NULL, TRUE, FALSE, FALSE, 2, 'active', 8, 'oak-tree'),
  ('vegetarian-appetizers', '3G Cauliflower(Golden Garden Gobi)', NULL, 13.69, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('vegetarian-appetizers', 'Chaana Pepper Fry', 'Crispy fried chickpeas tossed with cracked pepper and South Indian spices — bold,
crunchy, and irresistibly spiced.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 2, 'oak-tree'),
  ('vegetarian-appetizers', 'Plantain Bajji with coconut Dip', 'Golden-fried raw banana fritters served with creamy coconut dip — a crispy, comforting
South Indian favorite.', 14.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'oak-tree'),
  ('vegetarian-appetizers', 'Corn Masala Fry', 'Crispy golden corn sautéed with spicy masala, onions, and curry leaves — the perfect crunchy starter with a desi twist.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 4, 'oak-tree'),
  ('vegetarian-appetizers', 'Veg Manchurian', 'Crispy veggie balls tossed in tangy, spicy Indo-Chinese sauce — a fusion favorite that never fails to impress.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 5, 'oak-tree'),
  ('vegetarian-appetizers', 'Gobi Manchurian', 'Crispy cauliflower florets wok-tossed in flavorful Manchurian sauce — spicy, saucy, and packed with crunch.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 6, 'oak-tree'),
  ('vegetarian-appetizers', 'Paneer Pepper Fry', 'Soft paneer cubes tossed with black pepper, curry leaves, and aromatic masalas — fiery and flavorful in every bite.', 14.55, NULL, TRUE, FALSE, FALSE, 2, 'active', 7, 'oak-tree'),
  ('vegetarian-appetizers', 'Paneer 555', 'A chef’s special fusion of crispy paneer and spicy seasoning — bold, flavorful, and perfectly addictive.', 14.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 8, 'oak-tree'),
  ('vegetarian-appetizers', 'Baby Corn Manchurian', 'Golden-fried baby corn tossed in zesty Indo-Chinese sauce — crunchy, tangy, and full of flavor.', 13.51, NULL, TRUE, FALSE, FALSE, NULL, 'active', 9, 'oak-tree'),
  ('vegetarian-appetizers', 'Chilli Paneer', 'Classic Indo-Chinese delight — soft paneer chunks coated in spicy, tangy chilli sauce and sautéed to perfection.', 14.55, NULL, TRUE, FALSE, FALSE, 2, 'active', 10, 'oak-tree'),
  ('vegetarian-appetizers', 'Paneer Majestic', 'A royal appetizer made with golden-fried paneer tossed in creamy, spiced yogurt sauce — majestic in every sense.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 11, 'oak-tree'),
  ('vegetarian-appetizers', 'Vegtable Bullets', 'Crispy veggie bites packed with flavor and spices — the perfect crunchy snack for spice lovers.', 14.55, NULL, TRUE, FALSE, FALSE, NULL, 'active', 12, 'oak-tree'),
  ('vegetarian-appetizers', 'Baby Corn Majestic', 'Crispy baby corn tossed in a rich, creamy, and mildly spiced majestic sauce — an irresistible Indo-fusion treat.', 14.55, NULL, TRUE, FALSE, FALSE, NULL, 'active', 13, 'oak-tree'),
  ('vegetarian-appetizers', 'Chilli Gobi', 'Crispy cauliflower florets coated in fiery chilli sauce — bold, tangy, and downright addictive.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 14, 'oak-tree'),
  ('vegetarian-appetizers', 'Chilli Lotus Root', 'Crunchy lotus root rings tossed in hot and tangy chilli sauce — a unique twist for spice lovers.', 14.55, NULL, TRUE, FALSE, FALSE, 2, 'active', 15, 'oak-tree'),
  ('vegetarian-appetizers', 'Gobi 65', 'Crispy South Indian-style cauliflower fry seasoned with aromatic spices — crunchy, spicy, and bursting with flavor.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 16, 'oak-tree'),
  ('vegetarian-appetizers', 'Onion Pakoda', 'Golden-fried onion fritters seasoned with herbs and gram flour — crispy, aromatic, and perfect for any mood.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 17, 'oak-tree'),
  ('vegetarian-appetizers', 'Gobi Pepper Fry', 'Cauliflower florets roasted with crushed pepper and curry leaves — a spicy, earthy flavor explosion.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 18, 'oak-tree'),
  ('vegetarian-appetizers', 'Baby Corn Pepper Fry', 'Tender baby corn stir-fried with cracked pepper and spices — crisp, spicy, and full of flavor.', 13.51, NULL, TRUE, FALSE, FALSE, 2, 'active', 19, 'oak-tree'),
  ('vegetarian-appetizers', 'Lotus Root Manchurian', 'Crispy lotus root tossed in bold Manchurian sauce — crunchy, saucy, and perfectly balanced.', 14.55, NULL, TRUE, FALSE, FALSE, NULL, 'active', 20, 'oak-tree'),
  ('vegetarian-appetizers', 'Cashew Pakoda', 'Crunchy cashew fritters fried to perfection — rich, nutty, and irresistibly crisp.', 14.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 21, 'oak-tree'),
  ('vegetarian-appetizers', 'Gobi Majestic', 'Crispy cauliflower tossed in creamy, spiced yogurt sauce — a true majestic treat with a fusion kick.', 14.55, NULL, TRUE, FALSE, FALSE, NULL, 'active', 22, 'oak-tree'),
  ('vegetarian-appetizers', 'Mushroom Majestic', 'Golden-fried mushrooms coated in smooth, spiced yogurt-based sauce — rich, aromatic, and full of flavor.', 14.55, NULL, TRUE, FALSE, FALSE, NULL, 'active', 23, 'oak-tree'),
  ('vegetarian-appetizers', 'Chilli Baby Corn', 'Crispy baby corn tossed in spicy chilli sauce with onions and bell peppers — hot, tangy, and addictive.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 24, 'oak-tree'),
  ('vegetarian-appetizers', 'Hyderabad Paneer 65', 'Signature Hyderabadi-style paneer fry — bold, spicy, and bursting with authentic South Indian flavors.', 14.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 25, 'oak-tree'),
  ('vegetarian-appetizers', 'Mushroom Pepper Fry', 'Tender mushrooms tossed with black pepper, onions, and curry leaves — a spicy, earthy classic.', 13.51, NULL, TRUE, FALSE, FALSE, 2, 'active', 26, 'oak-tree'),
  ('vegetarian-appetizers', 'Punjabi Samosa', 'Golden, flaky samosas filled with spiced potato and peas — an all-time favorite Indian street snack.', 9.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 27, 'oak-tree'),
  ('vegetarian-appetizers', 'Gobi 555', 'Crispy cauliflower tossed in fiery seasoning — a chef’s special creation that’s bold, spicy, and utterly addictive.', 14.55, NULL, TRUE, FALSE, FALSE, 2, 'active', 28, 'oak-tree'),
  ('vegetarian-appetizers', 'Mushroom Manchurian', 'Crispy mushrooms coated in spicy, tangy Manchurian sauce — a perfect Indo-Chinese favorite.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 29, 'oak-tree'),
  ('vegetarian-appetizers', 'Paneer Manchurian', 'Soft paneer cubes wok-tossed in flavorful Manchurian sauce — spicy, saucy, and crowd-favorite.', 14.55, NULL, TRUE, FALSE, FALSE, 2, 'active', 30, 'oak-tree'),
  ('vegetarian-appetizers', 'Chilli Mushroom', 'Juicy mushrooms tossed in hot chilli sauce with peppers and onions — tangy, spicy, and utterly satisfying.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 31, 'oak-tree'),
  ('vegetarian-appetizers', 'Spinach Pakoda', 'Crispy spinach fritters seasoned with aromatic spices — light, crunchy, and irresistibly tasty.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 32, 'oak-tree'),
  ('vegetarian-appetizers', 'Mushroom 555', 'Crispy mushrooms tossed in signature spicy seasoning — fiery, bold, and bursting with umami.', 14.55, NULL, TRUE, FALSE, FALSE, 2, 'active', 33, 'oak-tree'),
  ('vegetarian-appetizers', 'Baby Corn 555', 'Crispy fried baby corn tossed in special 555 masala — spicy, crunchy, and full of flavor.', 14.55, NULL, TRUE, FALSE, FALSE, 2, 'active', 34, 'oak-tree'),
  ('vegetarian-appetizers', 'Paneer Burji Dry', 'Scrambled paneer sautéed with onions, spices, and herbs — dry, flavorful, and perfectly spiced for every craving.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 35, 'oak-tree'),
  ('vegetarian-entrees', 'Paneer Tikka Masala', 'Char-grilled paneer cubes simmered in rich, spiced tomato gravy — smoky, creamy, and bursting with flavor.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('vegetarian-entrees', 'Punjabi Palak Paneer', 'Soft paneer cooked in creamy spinach gravy with Punjabi spices — wholesome, earthy, and soul-satisfying.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'oak-tree'),
  ('vegetarian-entrees', 'Malai Kofta', 'Golden-fried cottage cheese dumplings served in a luscious cashew cream sauce — rich, royal, and comforting.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'oak-tree'),
  ('vegetarian-entrees', 'Paneer Butter Masala', 'Soft paneer simmered in buttery tomato gravy — mildly sweet, creamy, and everyone’s all-time favorite.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 4, 'oak-tree'),
  ('vegetarian-entrees', 'Veg Korma', 'A mix of seasonal vegetables cooked in a mildly spiced cashew-coconut gravy — rich, aromatic, and perfectly balanced.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 5, 'oak-tree'),
  ('vegetarian-entrees', 'Dal Tadka', 'Yellow lentils tempered with ghee, garlic, and cumin — simple, comforting, and loaded with homestyle flavor.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 6, 'oak-tree'),
  ('vegetarian-entrees', 'Gutti Vankaya (Stuffed Brinjal)', 'Tender eggplants stuffed with spicy peanut masala and slow-cooked — a true Andhra delicacy.', 15.59, NULL, TRUE, FALSE, FALSE, 2, 'active', 7, 'oak-tree'),
  ('vegetarian-entrees', 'Dal Makhani', 'Slow-cooked black lentils simmered overnight in butter and cream — smooth, smoky, and irresistibly rich.', 13.51, NULL, TRUE, FALSE, FALSE, NULL, 'active', 8, 'oak-tree'),
  ('vegetarian-entrees', 'Shahi Paneer', 'Royal North Indian curry with paneer cooked in cashew-cream sauce — mild, creamy, and full of regal flavor.', 14.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 9, 'oak-tree'),
  ('vegetarian-entrees', 'Paneer Burji Gravy', 'Scrambled paneer cooked with spiced onion-tomato gravy — flavorful, rustic, and delicious with naan.', 14.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 10, 'oak-tree'),
  ('vegetarian-entrees', 'Mango Dal', 'A tangy South Indian-style lentil curry with raw mango — unique, comforting, and perfectly balanced.', 13.51, NULL, TRUE, FALSE, FALSE, NULL, 'active', 11, 'oak-tree'),
  ('vegetarian-entrees', 'Paneer Korma', 'Paneer cubes cooked in a creamy, nut-based gravy — mild, rich, and packed with aromatic flavors.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 12, 'oak-tree'),
  ('vegetarian-entrees', 'Chettinad Paneer', 'Paneer tossed in bold Chettinad spices and coconut gravy — fiery, flavorful, and distinctly South Indian.', 14.55, NULL, TRUE, FALSE, FALSE, 2, 'active', 13, 'oak-tree'),
  ('vegetarian-entrees', 'Navratan Korma', 'A royal medley of nine veggies and fruits cooked in creamy gravy — rich, mildly sweet, and full of color.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 14, 'oak-tree'),
  ('vegetarian-entrees', 'Chettinad Mix Veg', 'A spicy South Indian-style curry made with mixed vegetables and Chettinad masala — bold and aromatic.', 14.55, NULL, TRUE, FALSE, FALSE, 2, 'active', 15, 'oak-tree'),
  ('vegetarian-entrees', 'Kadai Paneer', 'Paneer sautéed with bell peppers, onions, and Kadai spices — smoky, spicy, and full of flavor.', 15.59, NULL, TRUE, FALSE, FALSE, 2, 'active', 16, 'oak-tree'),
  ('vegetarian-entrees', 'Chana Saag', 'Protein-rich chickpeas cooked in creamy spinach gravy — hearty, healthy, and delicious.', 14.55, NULL, TRUE, FALSE, FALSE, NULL, 'active', 17, 'oak-tree'),
  ('vegetarian-entrees', 'Kadai Veg', 'Mixed vegetables tossed in spicy tomato-based Kadai gravy — vibrant, flavorful, and full of zest.', 15.59, NULL, TRUE, FALSE, FALSE, 2, 'active', 18, 'oak-tree'),
  ('vegetarian-entrees', 'Aloo Gobi', 'Classic North Indian curry of potatoes and cauliflower cooked with aromatic spices — comforting and homestyle.', 14.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 19, 'oak-tree'),
  ('vegetarian-entrees', 'Bendi Vepudu', 'Crispy fried okra tossed with South Indian spices — dry-fried, flavorful, and the perfect side dish.', 14.55, NULL, TRUE, FALSE, FALSE, NULL, 'active', 20, 'oak-tree'),
  ('vegetarian-entrees', 'Palak Dal', 'Lentils simmered with fresh spinach and garlic tempering — simple, healthy, and home-style comfort.', 13.51, NULL, TRUE, FALSE, FALSE, NULL, 'active', 21, 'oak-tree'),
  ('vegetarian-entrees', 'Aloo Palak', 'Potatoes cooked in smooth spinach gravy — mild, creamy, and wholesome with every bite.', 14.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 22, 'oak-tree'),
  ('vegetarian-entrees', 'Bendi Pulusu', 'Traditional Andhra-style tangy okra curry cooked in tamarind gravy — bold, flavorful, and deeply satisfying.', 14.55, NULL, TRUE, FALSE, FALSE, NULL, 'active', 23, 'oak-tree'),
  ('vegetarian-entrees', 'Kadai Mushroom', 'Tender mushrooms cooked in spicy tomato gravy with capsicum and onions — smoky and irresistibly bold.', 15.59, NULL, TRUE, FALSE, FALSE, 2, 'active', 24, 'oak-tree'),
  ('vegetarian-entrees', 'Chana Masala', 'Chickpeas cooked in tangy tomato gravy with aromatic North Indian spices — spicy, hearty, and flavorful.', 14.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 25, 'oak-tree'),
  ('vegetarian-entrees', 'Chettinad Mushroom', 'Mushrooms tossed in spicy, coconut-based Chettinad masala — hot, earthy, and packed with South Indian flavor.', 14.55, NULL, TRUE, FALSE, FALSE, 2, 'active', 26, 'oak-tree'),
  ('vegetarian-entrees', 'Kadai Bendi', 'Okra cooked with peppers and tomatoes in classic Kadai masala — spicy, fresh, and full of crunch.', 14.55, NULL, TRUE, FALSE, FALSE, 2, 'active', 27, 'oak-tree'),
  ('vegetarian-entrees', 'kaju curry', 'Rich and creamy curry made with cashews in spiced tomato-onion gravy — decadent and flavorful.', 14.55, NULL, TRUE, FALSE, FALSE, NULL, 'active', 28, 'oak-tree'),
  ('vegetarian-entrees', 'Bendi Masala', 'Okra sautéed with onions, tomatoes, and Indian spices — flavorful, homestyle, and perfectly spiced.', 14.55, NULL, TRUE, FALSE, FALSE, NULL, 'active', 29, 'oak-tree'),
  ('vegetarian-entrees', 'Mushroom Korma', 'Tender mushrooms cooked in creamy cashew-coconut gravy — rich, silky, and full of flavor.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 30, 'oak-tree'),
  ('vegetarian-entrees', 'Tomato Dal', 'Lentils simmered with tangy tomatoes and tempered with garlic and mustard seeds — simple yet full of flavor.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 31, 'oak-tree'),
  ('vegetarian-entrees', 'Aloo Korma', 'Soft potatoes cooked in creamy, spiced coconut-cashew gravy — mild, aromatic, and perfectly comforting.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 32, 'oak-tree'),
  ('vegetarian-rice-and-biryanis', 'Ulavacharu Biryani (Veg)', 'Fragrant basmati rice layered with slow-cooked horse gram (ulavacharu) gravy and mixed vegetables — earthy, rich, and authentically Andhra-style.', 16.63, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('vegetarian-rice-and-biryanis', 'Gutti Vankaya Biryani', 'A Hyderabadi classic! Basmati rice cooked with stuffed brinjal and aromatic spices — smoky, spicy, and full of traditional flavor.', 16.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 2, 'oak-tree'),
  ('vegetarian-rice-and-biryanis', 'Veg Biryani', 'Long-grain basmati rice cooked with garden-fresh vegetables, saffron, and spices — light, flavorful, and satisfying.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'oak-tree'),
  ('vegetarian-rice-and-biryanis', 'Paneer Biryani', 'Soft paneer cubes layered with fragrant rice and house-blend biryani masala — rich, creamy, and irresistibly aromatic', 16.63, NULL, TRUE, FALSE, FALSE, NULL, 'active', 4, 'oak-tree'),
  ('vegetarian-rice-and-biryanis', 'Gobi Masala Biryani', 'Crispy cauliflower tossed in spicy masala and layered with aromatic rice — a bold, flavorful twist on classic biryani.', 15.59, NULL, TRUE, FALSE, FALSE, 2, 'active', 5, 'oak-tree'),
  ('vegetarian-rice-and-biryanis', 'Paneer Keema Biryani', 'Finely minced paneer cooked with robust biryani spices and layered with saffron rice — indulgent, spicy, and unique.', 16.63, NULL, TRUE, FALSE, FALSE, 2, 'active', 6, 'oak-tree'),
  ('vegetarian-rice-and-biryanis', 'Curd Rice', 'Comfort in every bite — chilled curd mixed with rice, tempered with mustard, ginger, and curry leaves.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 7, 'oak-tree'),
  ('vegetarian-rice-and-biryanis', 'Veg Keema Biryani', 'Minced vegetable masala slow-cooked with aromatic basmati rice — spicy, flavorful, and a vegetarian favorite.', 16.63, NULL, TRUE, FALSE, FALSE, 2, 'active', 8, 'oak-tree'),
  ('vegetarian-rice-and-biryanis', 'Chilli Mushroom Biryani', 'Spicy mushrooms tossed in chilli masala and layered with flavorful biryani rice — bold, saucy, and full of zest.', 15.59, NULL, TRUE, FALSE, FALSE, 2, 'active', 9, 'oak-tree'),
  ('vegetarian-rice-and-biryanis', 'Ulavacharu Biryani (Paneer)', 'Paneer cubes simmered in rich horse gram (ulavacharu) gravy and layered with fragrant biryani rice — earthy, creamy, and full of Andhra flavor.', 16.63, NULL, TRUE, FALSE, FALSE, NULL, 'active', 10, 'oak-tree'),
  ('vegetarian-rice-and-biryanis', 'Jeera Rice', 'Aromatic basmati rice tempered with roasted cumin seeds and ghee — simple, fragrant, and the perfect side.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 11, 'oak-tree'),
  ('vegetarian-rice-and-biryanis', 'Gongura Biryani (Paneer)', 'Tangy gongura (sorrel leaves) blended with paneer and layered in spicy biryani rice — a true Andhra delicacy.', 16.63, NULL, TRUE, FALSE, FALSE, 2, 'active', 12, 'oak-tree'),
  ('vegetarian-rice-and-biryanis', 'Gongura Biryani (Veg)', 'Zesty gongura masala cooked with fresh vegetables and aromatic rice — tangy, spicy, and authentically South Indian.', 16.63, NULL, TRUE, FALSE, FALSE, 2, 'active', 13, 'oak-tree'),
  ('vegetarian-rice-and-biryanis', 'Cut Mirchi Biryani', 'Crispy cut mirchi tossed in spicy masala and layered with fragrant biryani rice — fiery, crunchy, and irresistibly flavorful.', 15.59, NULL, TRUE, FALSE, FALSE, 2, 'active', 14, 'oak-tree'),
  ('dd-family-packs-to-go-only', 'Egg Biryani - Family PACK', 'Aromatic basmati rice cooked with fresh vegetables, mint, and traditional spices — light, flavorful, and family-perfect.', 42.63, NULL, FALSE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('dd-family-packs-to-go-only', 'Chicken FryPiece Biryani Boneless - Family Pack', 'Juicy boneless chicken pieces fried and layered with fragrant biryani rice — bold, spicy, and perfect for sharing', 55, NULL, FALSE, FALSE, FALSE, 2, 'active', 2, 'oak-tree'),
  ('dd-family-packs-to-go-only', 'Mutton Fry Piece Biryani - FamilyPack(Bone-In)', 'Tender mutton pieces cooked to perfection and mixed with spiced rice — rich, flavorful, and made for true biryani lovers.', 59.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 3, 'oak-tree'),
  ('dd-family-packs-to-go-only', 'Mutton Fry Piece Biryani - FamilyPack (Boneless)', 'Boneless mutton chunks tossed in signature masala and layered with aromatic rice — indulgent, spicy, and simply irresistible.', 64.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 4, 'oak-tree'),
  ('dd-family-packs-to-go-only', 'Goat Dum Biryani - FAMILY PACK', 'Traditional Hyderabadi-style dum biryani with tender goat meat and fragrant basmati rice — slow-cooked for that authentic flavor.', 57.19, NULL, FALSE, FALSE, FALSE, NULL, 'active', 5, 'oak-tree'),
  ('dd-family-packs-to-go-only', 'Ulavacharu Chicken Boneless Biryani - FAMILY PACK', 'Boneless chicken cooked in rich horse gram (ulavacharu) gravy and layered with biryani rice — earthy, spicy, and full of Andhra flavor.', 51.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 6, 'oak-tree'),
  ('dd-family-packs-to-go-only', 'Chicken Dum Biryani  - FAMILY PACK', 'Classic Hyderabadi dum biryani — aromatic basmati rice layered with tender chicken and house-made spices for pure comfort.', 46.79, NULL, FALSE, FALSE, FALSE, NULL, 'active', 7, 'oak-tree'),
  ('dd-family-packs-to-go-only', 'Vijayawada Boneless Biryani - FAMILY PACK', 'A fiery South Indian special with boneless chicken cooked in bold masala and layered with fragrant rice — spicy and sensational.', 51.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 8, 'oak-tree'),
  ('dd-family-packs-to-go-only', 'DD Spl Chicken Biryani - FAMILY PACK', 'Our signature Desi Dhamaka special — juicy chicken, aromatic rice, and secret spices for a truly royal biryani experience.', 51.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 9, 'oak-tree'),
  ('dd-family-packs-to-go-only', 'Shrimp Biryani - FAMILY PACK', 'Succulent shrimp simmered in spiced biryani masala and layered with long-grain rice — coastal flavor in every bite.', 57.19, NULL, FALSE, FALSE, FALSE, NULL, 'active', 10, 'oak-tree'),
  ('dd-family-packs-to-go-only', 'Ulavacharu Goat Dum Biryani - FAMILY PACK', 'Slow-cooked goat meat infused with earthy ulavacharu flavors — a rich Andhra-style biryani that stands out.', 59.27, NULL, FALSE, FALSE, FALSE, NULL, 'active', 11, 'oak-tree'),
  ('dd-family-packs-to-go-only', 'Ulavacharu Chicken Dum Biryani - FAMILY PACK', 'Tender chicken layered with biryani rice and simmered in authentic ulavacharu gravy — smoky, tangy, and full of taste.', 51.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 12, 'oak-tree'),
  ('dd-family-packs-to-go-only', 'Paneer biryani - FAMILY PACK', 'Soft paneer cubes cooked in fragrant biryani masala and layered with saffron rice — rich, creamy, and vegetarian delight.', 46.79, NULL, TRUE, FALSE, FALSE, NULL, 'active', 13, 'oak-tree'),
  ('dd-family-packs-to-go-only', 'ChickenFryBiryani(Bonein)-Family Pack', 'Crispy fried chicken layered with flavorful biryani rice — a perfect blend of crunch, spice, and aroma.', 47.83, NULL, TRUE, FALSE, FALSE, NULL, 'active', 14, 'oak-tree'),
  ('dd-family-packs-to-go-only', 'Veg biryani - FAMILY PACK', 'Aromatic basmati rice cooked with fresh vegetables, mint, and traditional spices — light, flavorful, and family-perfect.', 41.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 15, 'oak-tree'),
  ('cooker-pulav', 'Veg Cooker Pulav', 'Aromatic basmati rice cooked with fresh garden vegetables, mild spices, and ghee — simple, flavorful, and full of homestyle comfort.', 69.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('cooker-pulav', 'Mutton Cooker Pulav', 'Tender mutton slow-cooked with fragrant basmati rice and house-made spices — rich, rustic, and bursting with authentic Andhra flavor.', 89.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 2, 'oak-tree'),
  ('cooker-pulav', 'Chicken Cooker Pulav', 'Juicy chicken pieces simmered in aromatic rice and bold spices — a hearty, flavorful one-pot classic that tastes just like home.', 79.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 3, 'oak-tree'),
  ('naans', 'Butter Roti', 'Soft whole wheat roti brushed with creamy butter — the perfect sidekick to any curry.', 3.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('naans', 'Garlic Naan', 'Fluffy naan roasted with fresh garlic and butter — pure aroma therapy for food lovers.', 4.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'oak-tree'),
  ('naans', 'Plain Naan', 'Classic tandoor-baked naan — soft, light, and perfect with every bite of gravy', 3.11, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'oak-tree'),
  ('naans', 'Butter Naan', 'Tandoor-baked, golden naan slathered in melted butter — a crowd favorite!', 4.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 4, 'oak-tree'),
  ('naans', 'Malabar Paratha', 'Flaky, layered paratha with crisp edges and soft layers — Kerala-style indulgence.', 5.19, NULL, TRUE, FALSE, FALSE, NULL, 'active', 5, 'oak-tree'),
  ('naans', 'Lachha Paratha', 'Buttery, multi-layered paratha that’s crisp, rich, and oh-so-satisfying.', 5.19, NULL, TRUE, FALSE, FALSE, NULL, 'active', 6, 'oak-tree'),
  ('naans', 'Roti', 'Soft, homestyle whole wheat bread that pairs beautifully with all curries.', 3.11, NULL, TRUE, FALSE, FALSE, NULL, 'active', 7, 'oak-tree'),
  ('naans', 'Bread Basket', 'An assorted mix of our best breads — naan, roti, paratha — a must for sharing!', 16.63, NULL, TRUE, FALSE, FALSE, NULL, 'active', 8, 'oak-tree'),
  ('naans', 'Chilli Garlic Naan', 'Spicy and flavorful naan brushed with garlic butter and green chili — for the bold palate.', 4.15, NULL, TRUE, FALSE, FALSE, 2, 'active', 9, 'oak-tree'),
  ('naans', 'Cheese Naan', 'Melted cheese tucked inside soft naan — indulgence in every bite.', 4.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 10, 'oak-tree'),
  ('naans', 'Chilli Cheese Naan', 'A cheesy naan with a hint of heat — a delicious Indo-fusion twist.', 4.15, NULL, TRUE, FALSE, FALSE, 2, 'active', 11, 'oak-tree'),
  ('naans', 'Onion Kulcha', 'Stuffed with caramelized onions and spices — soft, aromatic, and addictive.', 4.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 12, 'oak-tree'),
  ('naans', 'Peshwari Naan', 'Sweet and nutty naan filled with coconut and dry fruits — a royal treat.', 4.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 13, 'oak-tree'),
  ('kebab-and-tandooris', 'Red Lantern Grill Chicken', NULL, 16.63, NULL, FALSE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('kebab-and-tandooris', 'Reshmi Kebab - Chicken', 'Tender chicken marinated in creamy cashew yogurt mix, grilled to perfection.', 20.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 2, 'oak-tree'),
  ('kebab-and-tandooris', 'Makhmali Paneer Tikka', 'Soft paneer cubes marinated in spiced cream and roasted till melt-in-mouth.', 16.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'oak-tree'),
  ('kebab-and-tandooris', 'DD spl Non Veg Kebab Platter', 'A chef’s special assortment of our best kebabs — juicy, smoky, and irresistible.', 24.95, NULL, TRUE, FALSE, TRUE, NULL, 'active', 4, 'oak-tree'),
  ('kebab-and-tandooris', 'Chicken Tikka Kebab', 'Classic tandoori delight — boneless chicken infused with rich spices and charred aroma.', 17.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 5, 'oak-tree'),
  ('kebab-and-tandooris', 'Murg Malai Kebab', 'Creamy, velvety chicken kebabs that melt in your mouth with every bite.', 17.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 6, 'oak-tree'),
  ('kebab-and-tandooris', 'Tandoori Pomfret', 'Whole pomfret marinated in spicy tandoori masala — grilled crisp and flavorful.', 20.79, NULL, TRUE, FALSE, FALSE, 2, 'active', 7, 'oak-tree'),
  ('kebab-and-tandooris', 'Tangdi Kebab', 'Juicy drumsticks marinated overnight and flame-grilled for smoky perfection.', 17.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 8, 'oak-tree'),
  ('kebab-and-tandooris', 'Paneer Tikka Kebab', 'Chargrilled paneer with bell peppers and onions — tandoor magic on a skewer', 16.63, NULL, TRUE, FALSE, FALSE, NULL, 'active', 9, 'oak-tree'),
  ('kebab-and-tandooris', 'Chicken Malai Kebab', 'Creamy, soft chicken marinated with cheese and herbs — a royal bite.', 17.67, NULL, FALSE, FALSE, FALSE, NULL, 'active', 10, 'oak-tree'),
  ('kebab-and-tandooris', 'Chicken Tandoori', 'The classic red-hot tandoori chicken — smoky, spicy, and full of flavor.', 16.63, NULL, FALSE, FALSE, FALSE, 2, 'active', 11, 'oak-tree'),
  ('kebab-and-tandooris', 'Tawa Fish', 'Pan-seared fish cooked with house spices for a bold and zesty flavor.', 19.75, NULL, FALSE, FALSE, FALSE, NULL, 'active', 12, 'oak-tree'),
  ('kebab-and-tandooris', 'Chicken Seekh Kebab', 'Minced chicken mixed with herbs and spices, skewered and grilled to perfection.', 17.67, NULL, FALSE, FALSE, FALSE, NULL, 'active', 13, 'oak-tree'),
  ('kebab-and-tandooris', 'Pathar Ka Gosht ( Goat)', 'Traditional Hyderabadi-style goat slices cooked on hot stone with signature spices.', 21.83, NULL, FALSE, FALSE, FALSE, NULL, 'active', 14, 'oak-tree'),
  ('kebab-and-tandooris', 'Chicken Hariyali', 'Green-marinated chicken rich in mint and coriander — fresh and flavorful.', 17.67, NULL, FALSE, FALSE, FALSE, NULL, 'active', 15, 'oak-tree'),
  ('kebab-and-tandooris', 'Mixed Veg Kebab ( Gobi/Mushroom/ Panner/ Peppers)', 'A colorful mix of grilled veggies and paneer tossed with tangy masala.', 17.67, NULL, TRUE, FALSE, FALSE, NULL, 'active', 16, 'oak-tree'),
  ('kebab-and-tandooris', 'Chicken Chapli', 'Spicy minced chicken patties shallow-fried — a North Indian street-style favorite.', 17.67, NULL, FALSE, FALSE, FALSE, 2, 'active', 17, 'oak-tree'),
  ('kebab-and-tandooris', 'Tandoori Jinga', 'Succulent jumbo prawns grilled with a smoky tandoori punch.', 20.79, NULL, TRUE, FALSE, FALSE, NULL, 'active', 18, 'oak-tree'),
  ('non-veg-entrees', 'royyala vepudu', 'Andhra-style prawn fry bursting with spicy flavors and ghee-roasted goodness.', 20.79, NULL, FALSE, FALSE, FALSE, 2, 'active', 1, 'oak-tree'),
  ('non-veg-entrees', 'Mutton Milagu Pirattal (Boneless)', 'Tender mutton chunks tossed with crushed pepper and curry leaves — pure South spice.', 20.79, NULL, FALSE, FALSE, FALSE, NULL, 'active', 2, 'oak-tree'),
  ('non-veg-entrees', 'Bhimavaram Royyala vepudu', 'Fiery coastal prawns cooked in signature Bhimavaram masala for true heat lovers.', 20.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 3, 'oak-tree'),
  ('non-veg-entrees', 'Butter Chicken', 'Creamy tomato gravy hugging juicy tandoori chicken — smooth, rich, and comforting.', 16.63, NULL, FALSE, FALSE, FALSE, NULL, 'active', 4, 'oak-tree'),
  ('non-veg-entrees', 'DD Chef''s Special Chicken Curry ( Homestyle)', 'A nostalgic homestyle curry cooked with hand-pounded spices and love.', 17.67, NULL, FALSE, FALSE, TRUE, NULL, 'active', 5, 'oak-tree'),
  ('non-veg-entrees', 'Hyderabadi Goat Curry', 'Slow-cooked goat curry simmered in Hyderabadi spice blend — authentic and aromatic.', 18.71, NULL, FALSE, FALSE, FALSE, NULL, 'active', 6, 'oak-tree'),
  ('non-veg-entrees', 'Methi Chicken', 'Chicken cooked with fresh fenugreek leaves in a mildly spiced creamy base.', 16.63, NULL, FALSE, FALSE, FALSE, NULL, 'active', 7, 'oak-tree'),
  ('non-veg-entrees', 'Chicken Tikka Masala', 'Grilled chicken pieces in a rich tomato-onion gravy — the ultimate crowd-pleaser.', 16.63, NULL, FALSE, FALSE, FALSE, NULL, 'active', 8, 'oak-tree'),
  ('non-veg-entrees', 'Chicken Chettinad', 'A fiery South Indian curry with roasted coconut, black pepper, and bold masalas.', 16.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 9, 'oak-tree'),
  ('non-veg-entrees', 'Chicken Mughlai', 'Royal Mughlai-style chicken in a luscious cream-cashew sauce.', 16.63, NULL, FALSE, FALSE, FALSE, NULL, 'active', 10, 'oak-tree'),
  ('non-veg-entrees', 'Natu Kodi Curry', 'Country-style chicken cooked in traditional Andhra spices — rustic and full of flavor.', 18.71, NULL, FALSE, FALSE, FALSE, NULL, 'active', 11, 'oak-tree'),
  ('non-veg-entrees', 'DD Chef''s Special Mutton Curry ( Homestyle)', 'Tender mutton slow-cooked in a spicy gravy — comfort food at its finest.', 19.75, NULL, FALSE, FALSE, TRUE, 2, 'active', 12, 'oak-tree'),
  ('non-veg-entrees', 'Andhra Chicken Curry', 'Classic Andhra chicken bursting with fiery red chili and earthy aromas.', 16.63, NULL, FALSE, FALSE, FALSE, 2, 'active', 13, 'oak-tree'),
  ('non-veg-entrees', 'Railway Chicken Curry (With Bone)', 'British-era comfort curry cooked with whole spices and coconut hints.', 16.63, NULL, FALSE, FALSE, FALSE, NULL, 'active', 14, 'oak-tree'),
  ('non-veg-entrees', 'Goat Mughalai', 'Rich Mughlai-inspired goat curry simmered in spiced yogurt and nuts.', 18.71, NULL, FALSE, FALSE, FALSE, NULL, 'active', 15, 'oak-tree'),
  ('non-veg-entrees', 'Goat Chettinad', 'Fiery and peppery goat curry — a South Indian spice bomb.', 18.71, NULL, FALSE, FALSE, FALSE, 2, 'active', 16, 'oak-tree'),
  ('non-veg-entrees', 'Chicken Karaikudi', 'Chettinad-style curry packed with roasted spices and bold flavors.', 16.63, NULL, FALSE, FALSE, FALSE, NULL, 'active', 17, 'oak-tree'),
  ('non-veg-entrees', 'Chepala Pulusu', 'Traditional Andhra fish curry slow-cooked in tangy tamarind gravy.', 17.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 18, 'oak-tree'),
  ('non-veg-entrees', 'Kashmiri Goat Rogan Josh', 'Aromatic Kashmiri goat curry with saffron and rich masala base.', 18.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 19, 'oak-tree'),
  ('non-veg-entrees', 'Royyala Pulusu', 'Prawns simmered in tangy tamarind curry — coastal flavors at their best.', 18.71, NULL, FALSE, FALSE, FALSE, NULL, 'active', 20, 'oak-tree'),
  ('non-veg-entrees', 'Goat Vindaloo', 'Goan-style spicy goat curry with vinegar tang and deep spice tones.', 18.71, NULL, FALSE, FALSE, FALSE, 2, 'active', 21, 'oak-tree'),
  ('non-veg-entrees', 'Desi Chicken Curry (With Bone)', 'Homestyle country chicken curry — simple, spicy, and full of soul.', 16.63, NULL, FALSE, FALSE, FALSE, 2, 'active', 22, 'oak-tree'),
  ('non-veg-entrees', 'Egg Bhurji Dry', 'Masala-scrambled eggs tossed with onions, green chili, and Indian spices.', 13.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 23, 'oak-tree'),
  ('non-veg-entrees', 'Egg Pulusu', 'Masala-scrambled eggs tossed with onions, green chili, and Indian spices.', 15.59, NULL, FALSE, FALSE, FALSE, 2, 'active', 24, 'oak-tree'),
  ('non-veg-entrees', 'Goan Fish Curry', 'Coconut-rich coastal fish curry — tangy, creamy, and irresistibly good.', 17.67, NULL, FALSE, FALSE, FALSE, NULL, 'active', 25, 'oak-tree'),
  ('non-veg-entrees', 'Chicken Vindaloo', 'Spicy Goan chicken curry packed with vinegar-based masala heat.', 16.63, NULL, FALSE, FALSE, FALSE, 2, 'active', 26, 'oak-tree'),
  ('non-veg-appetizers', 'Kodi Pakodi', NULL, 15.59, NULL, FALSE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('non-veg-appetizers', 'DD SPL Cilantro Shrimp', NULL, 21, NULL, FALSE, FALSE, TRUE, NULL, 'active', 2, 'oak-tree'),
  ('non-veg-appetizers', 'Shrimp Pollichathu', NULL, 19.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 3, 'oak-tree'),
  ('non-veg-appetizers', 'Party Chicken Wild Wings', 'Crispy fried wings tossed in bold desi spices — the ultimate party starter!', 19.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 4, 'oak-tree'),
  ('non-veg-appetizers', 'Sesame Prawn Roast', 'Juicy prawns coated with toasted sesame and spicy masala for a nutty, coastal kick.', 20.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 5, 'oak-tree'),
  ('non-veg-appetizers', 'Shrimp Koli Wada with Jalapeno Sauce', 'Mumbai-style spiced shrimp fritters served with a zesty jalapeño dip.', 20.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 6, 'oak-tree'),
  ('non-veg-appetizers', 'Fish Amritsar', 'Crispy golden fish fillets fried Amritsari-style — crunchy, flaky, and flavorful.', 20.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 7, 'oak-tree'),
  ('non-veg-appetizers', 'Mutton Milagu Pirattal (Bone-in)', 'Bone-in mutton roasted with crushed black pepper and curry leaves — pure South Indian spice.', 18.71, NULL, FALSE, FALSE, FALSE, NULL, 'active', 8, 'oak-tree'),
  ('non-veg-appetizers', 'Party Chicken Wings', 'Crispy fried wings tossed in bold desi spices — the ultimate party starter!', 19.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 9, 'oak-tree'),
  ('non-veg-appetizers', 'Andhra Chilli Chicken', 'Fiery Andhra-style chicken bites tossed in a punchy, peppery sauce.', 15.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 10, 'oak-tree'),
  ('non-veg-appetizers', 'Fish Tikka Kebab', 'Tender fish cubes marinated in yogurt and grilled to smoky perfection.', 20.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 11, 'oak-tree'),
  ('non-veg-appetizers', 'Guntur Karampodi Kodi', 'Signature Guntur-style chicken fry dusted with fiery karampodi spice powder.', 16.63, NULL, FALSE, FALSE, FALSE, 2, 'active', 12, 'oak-tree'),
  ('non-veg-appetizers', 'Chicken Majestic', 'Crispy strips of chicken tossed in a creamy, spicy sauce — majestic indeed!', 15.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 13, 'oak-tree'),
  ('non-veg-appetizers', 'DD Spl Cilantro Fish', 'Pan-seared fish flavored with fresh cilantro and South Indian spices.', 17.67, NULL, FALSE, FALSE, TRUE, NULL, 'active', 14, 'oak-tree'),
  ('non-veg-appetizers', 'Mirapakaya Kodi Vepudu', 'A spicy dry chicken roast infused with green chilies and Andhra-style seasoning.', 16.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 15, 'oak-tree'),
  ('non-veg-appetizers', 'Chilli Shrimp', 'Crispy shrimp tossed in a bold Indo-Chinese chili sauce with peppers.', 18.71, NULL, FALSE, FALSE, FALSE, 2, 'active', 16, 'oak-tree'),
  ('non-veg-appetizers', 'Ameerpet Egg Fry', 'Street-style masala egg fry loaded with onions, chilies, and signature Ameerpet spice.', 14.55, NULL, FALSE, FALSE, FALSE, NULL, 'active', 17, 'oak-tree'),
  ('non-veg-appetizers', 'Chicken 65 Dry', 'Crispy, spicy, and iconic — the original South Indian chicken starter.', 15.59, NULL, FALSE, FALSE, FALSE, 2, 'active', 18, 'oak-tree'),
  ('non-veg-appetizers', 'Chilli Egg', 'Boiled eggs tossed in a tangy Indo-Chinese chili sauce — a fiery twist on comfort.', 15.59, NULL, FALSE, FALSE, FALSE, 2, 'active', 19, 'oak-tree'),
  ('non-veg-appetizers', 'Godavari Fish Fry', 'Coastal-style fried fish marinated in tangy masala and shallow-fried to golden perfection.', 21.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 20, 'oak-tree'),
  ('non-veg-appetizers', 'Gongura Mamsam fry (Boneless)', 'Tender mutton roasted with gongura (sorrel leaves) — tangy, spicy, and unforgettable.', 20.79, NULL, FALSE, FALSE, FALSE, 2, 'active', 21, 'oak-tree'),
  ('non-veg-appetizers', 'Mutton Ghee Roast (Boneless)', 'Succulent mutton roasted in ghee and Mangalorean spices — rich and aromatic.', 20.79, NULL, FALSE, FALSE, FALSE, NULL, 'active', 22, 'oak-tree'),
  ('non-veg-appetizers', 'Hyd Chicken 65 Wet', 'A juicy, saucy twist to the classic Chicken 65 — bursting with Hyderabad spice.', 15.59, NULL, FALSE, FALSE, FALSE, 2, 'active', 23, 'oak-tree'),
  ('non-veg-appetizers', 'Chicken Lollipop', 'Crispy lollipop chicken glazed in spicy sauce — juicy inside, crunchy outside.', 16.63, NULL, FALSE, FALSE, FALSE, 2, 'active', 24, 'oak-tree'),
  ('non-veg-appetizers', 'Chicken Pepper Fry', 'Aromatic South-style pepper chicken with roasted curry leaves and black pepper heat.', 15.59, NULL, FALSE, FALSE, FALSE, 2, 'active', 25, 'oak-tree'),
  ('non-veg-appetizers', 'Andhra Kodi Vepudu (Bone-In)', 'Traditional spicy chicken roast with bones — rustic, bold, and full of aroma.', 16.63, NULL, FALSE, FALSE, FALSE, 2, 'active', 26, 'oak-tree'),
  ('non-veg-appetizers', 'Andhra Kodi Vepudu (Boneless)', 'Classic Andhra chicken roast cooked to perfection — tender and fiery.', 17.67, NULL, FALSE, FALSE, FALSE, 2, 'active', 27, 'oak-tree'),
  ('non-veg-appetizers', 'Loose Prawns', 'Lightly battered prawns stir-fried with onions, garlic, and green chilies.', 18.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 28, 'oak-tree'),
  ('non-veg-appetizers', 'Palnadu Mamsam Roast (Boneless)', 'Authentic Palnadu-style dry mutton roast with ghee and local masalas', 20.79, NULL, FALSE, FALSE, FALSE, NULL, 'active', 29, 'oak-tree'),
  ('non-veg-appetizers', 'Shrimp Fry', 'Pan-fried shrimp tossed with house spices and curry leaves — coastal perfection.', 18.71, NULL, FALSE, FALSE, FALSE, NULL, 'active', 30, 'oak-tree'),
  ('non-veg-appetizers', 'Chicken 555', 'A crowd-favorite spicy dry chicken with crunchy texture and rich masala coating.', 16.63, NULL, FALSE, FALSE, FALSE, 2, 'active', 31, 'oak-tree'),
  ('non-veg-appetizers', 'Apollo Fish', 'Crispy fish tossed in Indo-Chinese spices — juicy, bold, and full of heat.', 17.67, NULL, FALSE, FALSE, FALSE, NULL, 'active', 32, 'oak-tree'),
  ('non-veg-appetizers', 'Mutton Ghee Roast (Bone-In)', 'Bone-in mutton slow-roasted with ghee and fiery red masala — a royal treat.', 18.71, NULL, FALSE, FALSE, FALSE, 2, 'active', 33, 'oak-tree'),
  ('non-veg-appetizers', 'Karivepaku Kodi', 'Crispy chicken cooked with curry leaf tempering — full of aroma and crunch.', 16.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 34, 'oak-tree'),
  ('non-veg-appetizers', 'Chicken Manchurian', 'Indo-Chinese fusion favorite — crispy chicken tossed in tangy soy-chili sauce.', 15.59, NULL, FALSE, FALSE, FALSE, 2, 'active', 35, 'oak-tree'),
  ('non-veg-appetizers', 'Pachi Mirchi Kodi Vepudu', 'Andhra-style green chili chicken fry — bold, spicy, and aromatic.', 15.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 36, 'oak-tree'),
  ('non-veg-appetizers', 'Natu Kodi Roast', 'Traditional country chicken slow-roasted with signature Andhra masalas.', 18.71, NULL, FALSE, FALSE, FALSE, NULL, 'active', 37, 'oak-tree'),
  ('non-veg-appetizers', 'Chilli Chicken', 'Crispy Indo-Chinese chicken coated in a spicy chili garlic sauce.', 15.59, NULL, FALSE, FALSE, FALSE, 2, 'active', 38, 'oak-tree'),
  ('non-veg-appetizers', 'Gongura Royyala Vepudu', 'Juicy prawns tossed with tangy gongura paste — a Telugu delicacy.', 18.71, NULL, FALSE, FALSE, FALSE, NULL, 'active', 39, 'oak-tree'),
  ('non-veg-appetizers', 'Black Pepper Prawns', 'Prawns stir-fried with cracked pepper and curry leaves — bold and aromatic.', 18.71, NULL, FALSE, FALSE, FALSE, NULL, 'active', 40, 'oak-tree'),
  ('non-veg-appetizers', 'Ginger Chicken', 'Tender chicken bites tossed in a flavorful ginger-garlic masala.', 16.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 41, 'oak-tree'),
  ('non-veg-appetizers', 'Shrimp Majestic', 'Crispy shrimp tossed in a creamy, spicy Andhra-style sauce.', 18.71, NULL, FALSE, FALSE, FALSE, 2, 'active', 42, 'oak-tree'),
  ('non-veg-appetizers', 'Mutton Pepper Fry (Bone-In)', 'Mutton roasted with freshly ground pepper and coconut bits — bold and meaty.', 18.71, NULL, FALSE, FALSE, FALSE, 2, 'active', 43, 'oak-tree'),
  ('non-veg-appetizers', 'Mutton Sukka (Bone-In)', 'Traditional dry mutton fry with a coarse masala and rustic South flavor.', 18.71, NULL, FALSE, FALSE, FALSE, NULL, 'active', 44, 'oak-tree'),
  ('non-veg-appetizers', 'Palnadu Mamsam Roast (Bone-In)', 'Classic Palnadu-style mutton fry — spicy, smoky, and ghee-rich.', 18.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 45, 'oak-tree'),
  ('non-veg-appetizers', 'Hell of Chicken Drums', 'Drumsticks coated in fiery marinade — spicy, smoky, and dangerously addictive.', 17.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 46, 'oak-tree'),
  ('non-veg-appetizers', 'Mutton Sukka (Boneless)', 'Boneless mutton roasted with coconut and coarse spices — a perfect bar-style starter.', 20.79, NULL, FALSE, FALSE, FALSE, NULL, 'active', 47, 'oak-tree'),
  ('non-veg-appetizers', 'Kothimeera Chicken', 'Juicy chicken tossed with fresh coriander, chili, and house masala — fresh and zesty.', 16.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 48, 'oak-tree'),
  ('non-veg-appetizers', 'Gongura Mamsam Fry (Bone-In)', 'Tangy gongura leaves meet spicy mutton — Andhra-style perfection.', 18.71, NULL, FALSE, FALSE, FALSE, 2, 'active', 49, 'oak-tree'),
  ('non-veg-appetizers', 'Fish 65', 'Golden-fried fish bites tossed in spicy 65 masala — crisp, spicy, and flavorful.', 17.67, NULL, FALSE, FALSE, FALSE, 2, 'active', 50, 'oak-tree'),
  ('non-veg-appetizers', 'Garlic Chicken', 'Soft chicken chunks glazed in garlic sauce — aromatic and satisfying.', 16.63, NULL, FALSE, FALSE, FALSE, NULL, 'active', 51, 'oak-tree'),
  ('non-veg-appetizers', 'Schezwan Chilli Fish', 'Crispy fish in spicy Schezwan sauce — a must-try Indo-Chinese favorite.', 17.67, NULL, FALSE, FALSE, FALSE, 2, 'active', 52, 'oak-tree'),
  ('non-veg-appetizers', 'Mutton Pepper Fry (Boneless)', 'Tender mutton tossed with pepper masala and ghee — spicy, earthy, and rich.', 20.79, NULL, FALSE, FALSE, FALSE, 2, 'active', 53, 'oak-tree'),
  ('south-indian-special', 'Poori with Goat Curry', NULL, 15.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('south-indian-special', 'Poori with Chicken Curry', 'Fluffy golden pooris served with rich, spicy chicken curry — a hearty South Indian breakfast favorite.', 14.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 2, 'oak-tree'),
  ('south-indian-special', 'Masala Dosa', 'Crispy dosa stuffed with spiced potato filling and served with chutney & sambar — an all-time classic.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'oak-tree'),
  ('south-indian-special', 'Mysore Bonda', 'Golden fried soft bondas with a crispy shell and fluffy inside — best enjoyed with coconut chutney.', 11.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 4, 'oak-tree'),
  ('south-indian-special', 'Sambar Vada', 'Crispy vadas soaked in hot, tangy sambar — comfort in every bite.', 11.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 5, 'oak-tree'),
  ('south-indian-special', 'Mysore Masala Dosa', 'Crispy dosa spread with Mysore red chutney and filled with spicy potato masala.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 6, 'oak-tree'),
  ('south-indian-special', 'Poori with Bhaji', 'Soft, puffed pooris paired with mildly spiced potato bhaji — simple, comforting, and satisfying.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 7, 'oak-tree'),
  ('south-indian-special', 'Plain Dosa', 'A paper-thin dosa roasted to golden crisp perfection — light and delicious.', 10.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 8, 'oak-tree'),
  ('south-indian-special', 'Chicken curry Dosa', 'A modern twist — dosa filled with flavorful chicken curry for a fusion of spice and crisp.', 15.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 9, 'oak-tree'),
  ('south-indian-special', 'Vada', 'Deep-fried savory lentil doughnuts — crunchy outside, soft inside, and best with chutney.', 11.43, NULL, TRUE, FALSE, FALSE, NULL, 'active', 10, 'oak-tree'),
  ('south-indian-special', 'Set Dosa', 'Soft, fluffy dosas served in a set of three — the perfect comfort breakfast.', 12.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 11, 'oak-tree'),
  ('south-indian-special', 'Chapathi with Goat Kurma', 'Soft wheat chapathis paired with rich, flavorful goat kurma — homely and satisfying.', 15.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 12, 'oak-tree'),
  ('south-indian-special', 'Idli with Vada(Combo)', 'A South Indian favorite combo — soft idlis and crispy vadas served with chutneys & sambar.', 12.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 13, 'oak-tree'),
  ('south-indian-special', 'Podi Dosa', 'Crispy dosa dusted with spicy gunpowder (podi) and drizzled with ghee — full of South flavor.', 12.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 14, 'oak-tree'),
  ('south-indian-special', 'Chapathi with Veg Kurma', 'Healthy chapathis served with creamy mixed vegetable kurma — light yet flavorful.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 15, 'oak-tree'),
  ('south-indian-special', 'Parota with Goat Kurma', 'Flaky Kerala-style parotas with spicy goat kurma — rich and indulgent.', 15.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 16, 'oak-tree'),
  ('south-indian-special', 'Cheese Dosa', 'Crispy dosa loaded with melted cheese — a South Indian favorite with a modern twist.', 12.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 17, 'oak-tree'),
  ('south-indian-special', 'Parota with Chicken Kurma', 'Layered parotas paired with aromatic chicken kurma — soft, spicy, and comforting.', 14.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 18, 'oak-tree'),
  ('south-indian-special', 'Parota with Veg Kurma', 'Crispy, layered parotas served with mild vegetable kurma — a perfect vegetarian delight.', 12.47, NULL, TRUE, FALSE, FALSE, NULL, 'active', 19, 'oak-tree'),
  ('south-indian-special', 'Ghee Karam Dosa', 'Aromatic dosa brushed with ghee and spicy karam — pure Andhra-style indulgence.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 20, 'oak-tree'),
  ('south-indian-special', 'Rayalaseema Karam Dosa', 'Fiery dosa from Rayalaseema with bold chili karam and ghee — not for the faint-hearted!', 12.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 21, 'oak-tree'),
  ('south-indian-special', 'Guntur Ghee Karam Idli', 'Soft idlis topped with spicy Guntur karam and ghee drizzle — simple, spicy, and addictive.', 11.43, NULL, TRUE, FALSE, FALSE, 2, 'active', 22, 'oak-tree'),
  ('south-indian-special', 'Onion Dosa', 'Crispy dosa layered with chopped onions and green chilies — crunchy, spicy, and flavorful.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 23, 'oak-tree'),
  ('south-indian-special', 'Egg Dosa', 'Classic dosa topped with egg and house masala — protein-packed and delicious.', 13.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 24, 'oak-tree'),
  ('south-indian-special', 'Chapathi with Chicken Kurma', 'Whole wheat chapathis paired with creamy chicken kurma — homestyle perfection.', 14.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 25, 'oak-tree'),
  ('south-indian-special', 'Uthappam Onion Chilli', 'Thick, soft uthappam topped with onions and green chilies — flavorful and filling.', 12.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 26, 'oak-tree'),
  ('south-indian-special', 'Cone Dosa', 'Crispy dosa rolled into a cone shape — light, crunchy, and fun to eat.', 11.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 27, 'oak-tree'),
  ('south-indian-special', 'Chicken Keema Dosa', NULL, 15.59, NULL, FALSE, FALSE, FALSE, NULL, 'active', 28, 'oak-tree'),
  ('south-indian-special', 'Uthappam Mix Veg', 'Soft uthappam topped with colorful veggies — wholesome and satisfying.', 12.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 29, 'oak-tree'),
  ('south-indian-special', 'Chocolate Dosa', NULL, 12.47, NULL, TRUE, FALSE, FALSE, NULL, 'active', 30, 'oak-tree'),
  ('south-indian-special', 'Pesarattu Upma Dosa', NULL, 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 31, 'oak-tree'),
  ('biryanis', 'Mutton Dum Biryani', 'Slow-cooked mutton layered with fragrant basmati rice, infused with rich spices and ghee — the royal Hyderabadi classic.', 19.75, NULL, FALSE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('biryanis', 'Chicken Dum Biryani', 'Tender chicken simmered with aromatic spices and saffron basmati rice — pure Hyderabadi perfection in every bite.', 16.63, NULL, FALSE, FALSE, FALSE, NULL, 'active', 2, 'oak-tree'),
  ('biryanis', 'Vijayawada Chicken Biryani (Boneless)', 'Boneless chicken in fiery Vijayawada-style spice mix layered with fragrant rice — a bold Andhra favorite.', 18.71, NULL, FALSE, FALSE, FALSE, 2, 'active', 3, 'oak-tree'),
  ('biryanis', 'Mutton Fry Piece Biryani (Boneless)', 'Juicy boneless mutton pieces fried and mixed with spiced biryani rice — rich, flavorful, and indulgent.', 21.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 4, 'oak-tree'),
  ('biryanis', 'Chicken Fry Piece Biryani (Bone-In)', 'Aromatic basmati rice layered with bone-in chicken fry pieces — a true Desi Dhamaka signature dish.', 18.71, NULL, FALSE, FALSE, FALSE, NULL, 'active', 5, 'oak-tree'),
  ('biryanis', 'Mutton Fry Piece Biryani (Bone-In)', 'Bone-in mutton cooked in authentic Hyderabadi dum style — juicy, spicy, and unforgettable.', 19.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 6, 'oak-tree'),
  ('biryanis', 'DD Special Chicken Biryani', 'House-special biryani bursting with flavors of chicken, caramelized onions, mint & chef''s secret masala.', 19.75, NULL, FALSE, FALSE, TRUE, NULL, 'active', 7, 'oak-tree'),
  ('biryanis', 'Chicken Biryani (Boneless)', 'Succulent boneless chicken cooked to perfection with layered fragrant rice — soft, spicy, and satisfying.', 17.67, NULL, FALSE, FALSE, FALSE, 2, 'active', 8, 'oak-tree'),
  ('biryanis', 'DD Spl Nalli Gosht Biryani', 'Tender lamb shank biryani slow-cooked in royal spices — rich, melt-in-mouth and irresistibly aromatic.', 29.11, NULL, FALSE, FALSE, TRUE, NULL, 'active', 9, 'oak-tree'),
  ('biryanis', 'Egg Biryani', 'Soft-boiled eggs layered with flavorful biryani rice and spices — simple yet full of flavor.', 15.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 10, 'oak-tree'),
  ('biryanis', 'Goat Kheema Biryani', 'Minced goat meat cooked in bold masala and layered with basmati rice — a must-try for biryani lovers.', 23.91, NULL, FALSE, FALSE, FALSE, NULL, 'active', 11, 'oak-tree'),
  ('biryanis', 'DD Spl Natu Kodi Biryani', 'Traditional country chicken cooked with rustic Andhra spices — authentic and soul-satisfying.', 24.95, NULL, FALSE, FALSE, TRUE, NULL, 'active', 12, 'oak-tree'),
  ('biryanis', 'Mamsam Roast Biryani (Bone-In)', 'Bone-in mutton roasted with spices and layered with aromatic rice — fiery and flavorful.', 20.79, NULL, FALSE, FALSE, FALSE, 2, 'active', 13, 'oak-tree'),
  ('biryanis', 'DD Special Chicken Biryani (Boneless)', 'Chef’s boneless special — juicy chicken layered with rich masala and fragrant rice.', 20.79, NULL, FALSE, FALSE, TRUE, NULL, 'active', 14, 'oak-tree'),
  ('biryanis', 'Chicken Fry Piece Biryani (Bone Less)', 'Crispy boneless chicken fry blended with aromatic biryani rice — every bite a burst of spice.', 19.75, NULL, FALSE, FALSE, FALSE, NULL, 'active', 15, 'oak-tree'),
  ('biryanis', 'Shrimp Fry Biryani', 'Golden fried shrimp tossed in spicy masala and layered with biryani rice — coastal flavor meets Hyderabadi aroma.', 19.75, NULL, FALSE, FALSE, FALSE, 2, 'active', 16, 'oak-tree'),
  ('biryanis', 'Mamsam Roast Biryani (Bone less)', 'Boneless mutton slow-roasted and mixed with biryani rice — bold, meaty, and satisfying.', 21.83, NULL, FALSE, FALSE, FALSE, NULL, 'active', 17, 'oak-tree'),
  ('biryanis', 'Gongura Mutton Biryani', 'Tangy gongura and spiced mutton layered in biryani rice — Andhra-style with a twist.', 20.79, NULL, FALSE, FALSE, FALSE, NULL, 'active', 18, 'oak-tree'),
  ('biryanis', 'Gongura Chicken Biryani', 'Spicy, tangy gongura-flavored chicken biryani — a perfect Andhra specialty.', 17.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 19, 'oak-tree'),
  ('biryanis', 'Fish Biryani', 'Fresh fish fillets cooked in flavorful biryani masala and layered with basmati rice — soft and aromatic.', 19.75, NULL, FALSE, FALSE, FALSE, NULL, 'active', 20, 'oak-tree'),
  ('biryanis', 'Ulavacharu Mutton Dum Biryani', 'Creamy horse gram (ulavacharu) meets spicy mutton dum biryani — smoky, tangy, and indulgent.', 20.79, NULL, FALSE, FALSE, FALSE, 2, 'active', 21, 'oak-tree'),
  ('biryanis', 'Ulavacharu Chicken Dum Biryani', 'Slow-cooked chicken biryani blended with signature ulavacharu sauce — earthy and unforgettable.', 17.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 22, 'oak-tree'),
  ('biryanis', 'Mutton Keema Biryani', 'Minced mutton cooked with rich masala and basmati rice — hearty and full-bodied.', 23.91, NULL, FALSE, FALSE, FALSE, NULL, 'active', 23, 'oak-tree'),
  ('biryanis', 'Chicken Keema Biryani', 'Spiced minced chicken layered with fluffy biryani rice — flavorful and satisfying.', 21.83, NULL, FALSE, FALSE, FALSE, NULL, 'active', 24, 'oak-tree'),
  ('dd-special-mandi', 'PaneerKeemaMandiFull', NULL, 69.67, NULL, TRUE, FALSE, FALSE, NULL, 'inactive', 1, 'oak-tree'),
  ('dd-special-mandi', 'PaneerKeemaMandiHalf', NULL, 44.71, NULL, TRUE, FALSE, FALSE, NULL, 'inactive', 2, 'oak-tree'),
  ('dd-special-mandi', 'Paneer Keema Mandi Single', NULL, 27.03, NULL, TRUE, FALSE, FALSE, NULL, 'inactive', 3, 'oak-tree'),
  ('dd-special-mandi', 'Mellissa Mandi', NULL, 140, NULL, TRUE, FALSE, FALSE, NULL, 'active', 4, 'oak-tree'),
  ('dd-special-mandi', 'SeaFood Mandi(Fish/Shrimp)', 'A grand seafood feast — tender fish and shrimp grilled with Arabic spices and served over aromatic mandi rice.', 94.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 5, 'oak-tree'),
  ('dd-special-mandi', 'DDspecial NalliGoshtMandi(Half)~40Mins', 'A half platter of our signature Nalli Gosht — juicy, slow-cooked lamb shanks with royal mandi spices.', 58.23, NULL, TRUE, FALSE, FALSE, NULL, 'active', 6, 'oak-tree'),
  ('dd-special-mandi', 'DDspecial NalliGoshtMandi(Single)~40Mins', 'Rich, flavorful lamb shank served over buttery mandi rice — melt-in-mouth indulgence in every bite.', 27.03, NULL, TRUE, FALSE, FALSE, NULL, 'active', 7, 'oak-tree'),
  ('dd-special-mandi', 'GoatMandi(Half)~40Mins', 'A rich, spicy half-portion mandi featuring slow-cooked goat and flavorful rice.', 47.83, NULL, TRUE, FALSE, FALSE, 2, 'active', 8, 'oak-tree'),
  ('dd-special-mandi', 'ChickenMandi(Single)~40Mins', 'Juicy chicken grilled to perfection and served with fragrant mandi rice — simple, smoky, and delicious.', 27.03, NULL, TRUE, FALSE, FALSE, NULL, 'active', 9, 'oak-tree'),
  ('dd-special-mandi', 'PaneerMandi(Single)~40Mins', 'Soft paneer cubes grilled with herbs and served over aromatic mandi rice — a vegetarian treat.', 27.03, NULL, TRUE, FALSE, FALSE, NULL, 'active', 10, 'oak-tree'),
  ('dd-special-mandi', 'GoatMandi(Full)~40Mins', 'A full feast of goat mandi — soft meat layered with buttery rice and bold spices.', 84.23, NULL, TRUE, FALSE, FALSE, NULL, 'active', 11, 'oak-tree'),
  ('dd-special-mandi', 'FishMandi(Single)~40Mins', 'Crispy fish fillet served with flavorful mandi rice — a coastal twist on the classic Arabic favorite.', 27.03, NULL, TRUE, FALSE, FALSE, NULL, 'active', 12, 'oak-tree'),
  ('dd-special-mandi', 'ChickenMandi(Full) ~40Mins', 'A full chicken mandi feast — tender chicken, ghee rice, and authentic Arabic flavors.', 79.03, NULL, TRUE, FALSE, FALSE, NULL, 'active', 13, 'oak-tree'),
  ('dd-special-mandi', 'Extra Mandi Rice', 'Flavorful, ghee-infused mandi rice — available only with mandi orders.', 14.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 14, 'oak-tree'),
  ('dd-special-mandi', 'Chicken Mandi (Half)~40Mins', 'A half platter of our signature chicken mandi — rich, aromatic, and perfectly spiced.', 47.83, NULL, FALSE, FALSE, FALSE, NULL, 'active', 15, 'oak-tree'),
  ('dd-special-mandi', 'GoatMandi(Single)~40Mins', 'Tender goat cooked with aromatic spices, served over flavorful mandi rice — hearty and satisfying.', 27.03, NULL, TRUE, FALSE, FALSE, NULL, 'active', 16, 'oak-tree'),
  ('dd-special-mandi', 'MixedFullMandi(Chicken/Mutton)~40Mins', 'A royal combo of chicken and mutton served over rich mandi rice — a perfect blend of both worlds.', 89.43, NULL, FALSE, FALSE, FALSE, NULL, 'active', 17, 'oak-tree'),
  ('dd-special-mandi', 'VegKeemaMandi(Single)~40Mins', 'Spiced vegetable keema served over mandi rice — flavorful and filling.', 27.03, NULL, TRUE, FALSE, FALSE, NULL, 'active', 18, 'oak-tree'),
  ('dd-special-mandi', 'PaneerMandi(Half)~40Mins', 'Creamy paneer pieces cooked with house spices — rich and satisfying.', 44.71, NULL, TRUE, FALSE, FALSE, NULL, 'active', 19, 'oak-tree'),
  ('dd-special-mandi', 'FishMandi(Half)~40Mins', 'Generous fish portions grilled and paired with aromatic rice — light yet indulgent.', 47.83, NULL, TRUE, FALSE, FALSE, NULL, 'active', 20, 'oak-tree'),
  ('dd-special-mandi', 'GuttiVankaya Mandi(Half)~40Mins', 'Half platter of Gutti Vankaya Mandi — tangy, spicy, and packed with flavor.', 44.71, NULL, TRUE, FALSE, FALSE, 2, 'active', 21, 'oak-tree'),
  ('dd-special-mandi', 'DDspecial NalliGosht Mandi(Full)~40Mins', 'A luxurious full platter for meat lovers — tender lamb shanks, ghee rice, and signature mandi masala.', 94.63, NULL, TRUE, FALSE, FALSE, NULL, 'active', 22, 'oak-tree'),
  ('dd-special-mandi', 'ShrimpMandi(Single)~40Mins', 'Juicy shrimp tossed in mandi masala and served with aromatic rice — a seafood delight.', 27.03, NULL, TRUE, FALSE, FALSE, NULL, 'active', 23, 'oak-tree'),
  ('dd-special-mandi', 'ShrimpMandi(Half)~40Mins', 'Half platter of shrimp mandi — tender shrimp with rich, flavorful rice.', 47.83, NULL, TRUE, FALSE, FALSE, NULL, 'active', 24, 'oak-tree'),
  ('dd-special-mandi', 'ShrimpMandi(Full)~40Mins', 'A royal seafood spread — full platter of shrimp mandi bursting with Arabic spice and ghee aroma.', 94.63, NULL, TRUE, FALSE, FALSE, NULL, 'active', 25, 'oak-tree'),
  ('dd-special-mandi', 'NatuKodi Mandi(Half)~40Mins', 'Half platter featuring spicy country chicken and fragrant mandi rice.', 47.83, NULL, FALSE, FALSE, FALSE, 2, 'active', 26, 'oak-tree'),
  ('dd-special-mandi', 'NatuKodi Mandi(Single)~40Mins', 'Rustic country chicken cooked in traditional Andhra style, layered with mandi rice — earthy and aromatic.', 27.03, NULL, FALSE, FALSE, FALSE, NULL, 'active', 27, 'oak-tree'),
  ('dd-special-mandi', 'GuttiVankaya Mandi(Single)~40Mins', 'Stuffed brinjal curry paired with fragrant mandi rice — a true Andhra classic.', 27.03, NULL, TRUE, FALSE, FALSE, NULL, 'active', 28, 'oak-tree'),
  ('dd-special-mandi', 'NatuKodi Mandi(Full)~40Mins', 'Full mandi feast of traditional Natu Kodi — bold, flavorful, and authentic.', 84.23, NULL, FALSE, FALSE, FALSE, NULL, 'active', 29, 'oak-tree'),
  ('dd-special-mandi', 'EggMandi(Single)~40Mins', 'Perfectly cooked eggs layered with spiced mandi rice — simple yet flavorful.', 27.03, NULL, TRUE, FALSE, FALSE, NULL, 'active', 30, 'oak-tree'),
  ('dd-special-mandi', 'VegKeemaMandi(Half)~40Mins', 'Half platter of aromatic mandi rice topped with delicious veg keema masala.', 44.71, NULL, TRUE, FALSE, FALSE, NULL, 'active', 31, 'oak-tree'),
  ('dd-special-mandi', 'PaneerMandi(Full)~40Mins', 'A full platter of paneer mandi — aromatic rice layered with marinated, grilled paneer.', 69.67, NULL, TRUE, FALSE, FALSE, NULL, 'active', 32, 'oak-tree'),
  ('dd-special-mandi', 'GuttiVankaya Mandi(Full)~40Mins', 'A full feast of stuffed brinjal and spiced mandi rice — pure South Indian soul food.', 69.67, NULL, TRUE, FALSE, FALSE, NULL, 'active', 33, 'oak-tree'),
  ('dd-special-mandi', 'FishMandi(Full)~40Mins', 'A full mandi platter for seafood lovers — golden fish layered with spicy, buttery rice.', 84.23, NULL, TRUE, FALSE, FALSE, 2, 'active', 34, 'oak-tree'),
  ('dd-special-mandi', 'VegKeemaMandi(Full)~40Mins', 'A vegetarian delight — rich veg keema and mandi rice served together for hearty comfort.', 69.67, NULL, TRUE, FALSE, FALSE, NULL, 'active', 35, 'oak-tree'),
  ('dd-special-mandi', 'EggMandi(Half)~40Mins', 'Half platter of egg mandi — comforting, rich, and lightly spiced.', 47.83, NULL, TRUE, FALSE, FALSE, NULL, 'active', 36, 'oak-tree'),
  ('dd-special-mandi', 'EggMandi(Full)~40Mins', 'A full platter featuring soft eggs and mandi rice — perfect for egg lovers.', 68.63, NULL, TRUE, FALSE, FALSE, NULL, 'active', 37, 'oak-tree'),
  ('dd-specials', 'Chicken Haleem', NULL, 17, NULL, FALSE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('dd-specials', 'Goat Haleem', 'Slow-cooked to perfection — tender goat blended with wheat, lentils, and aromatic spices. Creamy, hearty, and rich in authentic Hyderabadi flavor.', 18.71, NULL, FALSE, FALSE, FALSE, NULL, 'active', 2, 'oak-tree'),
  ('dd-specials', 'Boti Fry', 'Juicy chunks of goat boti sautéed with bold Andhra spices — smoky, spicy, and irresistibly flavorful.', 17.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 3, 'oak-tree'),
  ('dd-specials', 'DD Spl Potlam Biryani', 'Our show-stopper! Spicy biryani wrapped in an omelet and cooked to perfection — layers of flavor in every bite.', 24.95, NULL, TRUE, FALSE, TRUE, 2, 'active', 4, 'oak-tree'),
  ('dd-specials', 'Mutton Liver Fry', 'Tender pieces of mutton liver stir-fried with pepper, curry leaves, and traditional masala — a spicy South Indian favorite.', 19.75, NULL, FALSE, FALSE, FALSE, 2, 'active', 5, 'oak-tree'),
  ('dd-specials', 'DD Chef''s Special Tawa Fish (Boneless)', 'Fresh boneless fish grilled on a hot tawa with house-blend spices — smoky, juicy, and absolutely addictive.', 21.83, NULL, FALSE, FALSE, TRUE, NULL, 'active', 6, 'oak-tree'),
  ('dd-specials', 'DD Chef''s Special Tawa Fish (Bone-In)', 'Bone-in fish fillet seared to perfection with Chef’s signature masala — crisp outside, soft inside, and bursting with flavor.', 20.79, NULL, FALSE, FALSE, TRUE, NULL, 'active', 7, 'oak-tree'),
  ('dd-specials', 'Nalli Gosht Roast', 'Tender lamb shanks slow-roasted in rich gravy — fall-off-the-bone perfection loaded with royal Hyderabadi taste.', 21.83, NULL, FALSE, FALSE, FALSE, NULL, 'active', 8, 'oak-tree'),
  ('kids-menu', 'French Fries', 'Crispy golden fries served hot — the ultimate kid-favorite snack!', 9.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('kids-menu', 'Chicken Nuggets', 'Tender, juicy chicken bites coated in a crunchy golden crust — fun to eat and full of flavor.', 11.43, NULL, FALSE, FALSE, FALSE, NULL, 'active', 2, 'oak-tree'),
  ('kids-menu', 'DD Mini Kulcha', 'Soft, buttery mini kulchas served with mild curry — a delightful desi treat made just for little tummies!', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'oak-tree'),
  ('snacks', 'Malai Bun', 'Soft, sweet bun filled with rich cream — a melt-in-the-mouth Hyderabad classic.', 5, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('snacks', 'Plain Bun', 'Fluffy, warm bun that''s simple, soft, and nostalgic — the perfect tea-time partner.', 5, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'oak-tree'),
  ('snacks', 'Boiled Peanuts Masala', 'Tender peanuts tossed with onions, tomatoes, and spices — a spicy, tangy delight!', 11.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 3, 'oak-tree'),
  ('snacks', 'Roasted Peanut Masala', 'Crispy roasted peanuts mixed with zesty masala — perfect for crunchy cravings.', 11.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 4, 'oak-tree'),
  ('snacks', 'Cut Mirchi', 'Crispy fried green chilies sliced and seasoned to perfection — bold, spicy, and addictive!', 10.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 5, 'oak-tree'),
  ('snacks', 'Stuffed Mirchi', 'Green chilies stuffed with flavorful masala, deep-fried till golden — fiery and irresistible.', 11.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 6, 'oak-tree'),
  ('snacks', 'Mirchi Bajji', 'Street-style hot chili fritters coated in gram flour — crunchy outside, soft inside.', 11.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 7, 'oak-tree'),
  ('snacks', 'Bandi Punugulu', 'Golden, fluffy fritters made from fermented dosa batter — a South Indian favorite!', 11.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 8, 'oak-tree'),
  ('snacks', 'Samosa', 'Crispy pastry stuffed with spiced potatoes — the all-time favorite Indian snack.', 11.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 9, 'oak-tree'),
  ('snacks', 'Egg Bonda (3Pcs)', 'Boiled eggs dipped in spiced batter and fried golden brown — crispy, rich, and satisfying.', 12.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 10, 'oak-tree'),
  ('snacks', 'Kaju Fry', 'Crunchy cashews tossed with pepper and house spices — a royal and irresistible snack.', 14.55, NULL, TRUE, FALSE, FALSE, NULL, 'active', 11, 'oak-tree'),
  ('indo-chinese', 'Schezwan Chicken Noodles', 'Fiery noodles tossed with juicy chicken, veggies, and Schezwan spice — a bold Indo-Chinese favorite!', 15.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 1, 'oak-tree'),
  ('indo-chinese', 'Schezwan Veg Noodles', 'Loaded with fresh vegetables and tossed in spicy Schezwan sauce — a perfect balance of heat and flavor.', 14.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 2, 'oak-tree'),
  ('indo-chinese', 'Chicken Noodles', 'Classic stir-fried noodles with tender chicken and crunchy veggies — comforting and full of taste.', 15.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 3, 'oak-tree'),
  ('indo-chinese', 'Street food Fried Rice Chicken', 'Inspired by Indian street flavors — smoky, spicy, and irresistibly tasty in every bite!', 16.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 4, 'oak-tree'),
  ('indo-chinese', 'Chicken Fried Rice', 'Aromatic rice wok-tossed with juicy chicken, egg, and veggies — the ultimate comfort meal.', 15.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 5, 'oak-tree'),
  ('indo-chinese', 'Veg Noodles', 'Soft noodles tossed with colorful vegetables and house-made sauces — light, flavorful, and satisfying.', 13.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 6, 'oak-tree'),
  ('indo-chinese', 'Chicken Schezwan Fried Rice', 'Spicy Schezwan rice bursting with flavors of garlic, chili, and tender chicken — a fiery favorite!', 16.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 7, 'oak-tree'),
  ('indo-chinese', 'Shrimp Fried Rice', 'Juicy shrimp tossed with rice, soy, and aromatic spices — ocean-fresh goodness in every bite.', 16.63, NULL, FALSE, FALSE, FALSE, NULL, 'active', 8, 'oak-tree'),
  ('indo-chinese', 'Veg Fried Rice', 'Simple yet delicious — wok-tossed rice loaded with veggies and authentic Indo-Chinese flavors.', 14.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 9, 'oak-tree'),
  ('indo-chinese', 'Egg Noodles', 'Stir-fried noodles with scrambled egg, soy, and veggies — perfect for egg lovers!', 14.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 10, 'oak-tree'),
  ('indo-chinese', 'Egg Fried Rice', 'Fluffy rice blended with scrambled eggs, veggies, and spices — a delicious quick meal.', 14.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 11, 'oak-tree'),
  ('indo-chinese', 'Schezwan Shrimp Fried Rice', 'Spicy, zesty rice with shrimp and Schezwan sauce — a fiery twist for seafood lovers.', 16.63, NULL, FALSE, FALSE, FALSE, 2, 'active', 12, 'oak-tree'),
  ('indo-chinese', 'Veg Schezwan Fried Rice', 'Wok-tossed rice infused with chili-garlic Schezwan sauce and crunchy vegetables — full of flavor and heat.', 14.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 13, 'oak-tree'),
  ('indo-chinese', 'Egg Schezwan Fried Rice', 'Egg fried rice meets Schezwan spice — bold, saucy, and unforgettable!', 15.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 14, 'oak-tree'),
  ('soft-drinks', 'Club Soda', NULL, 4.99, NULL, TRUE, FALSE, FALSE, NULL, 'inactive', 1, 'oak-tree'),
  ('soft-drinks', 'Coke - Mexican Bottle (20oz)', 'Classic Coca-Cola with authentic Mexican sweetness — a true nostalgic refreshment.', 4.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'oak-tree'),
  ('soft-drinks', 'Chilled Poland Spring water', 'Pure, crisp hydration to complement your meal perfectly.', 1.18, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'oak-tree'),
  ('soft-drinks', 'Diet Coke - Can', 'Light, bubbly, and refreshing — zero calories, all the flavor.', 2.07, NULL, TRUE, FALSE, FALSE, NULL, 'active', 4, 'oak-tree'),
  ('soft-drinks', 'Poland Spring Water Bottle', 'Fresh, clean water to keep you cool and refreshed.', 0.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 5, 'oak-tree'),
  ('soft-drinks', 'sprite can', 'Crisp lemon-lime fizz that hits refresh instantly.', 2.07, NULL, TRUE, FALSE, FALSE, NULL, 'active', 6, 'oak-tree'),
  ('soft-drinks', 'Thumps Up - Can', 'India’s bold cola with a strong, fizzy kick — perfect with spicy dishes!', 2.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 7, 'oak-tree'),
  ('soft-drinks', 'Mango Lassi', 'Rich and creamy yogurt drink blended with ripe mangoes — a perfect desi cooler.', 6.23, NULL, TRUE, FALSE, FALSE, NULL, 'active', 8, 'oak-tree'),
  ('soft-drinks', 'Limca Can', 'Zesty lemon drink with that unmistakable Indian tang.', 2.69, NULL, TRUE, FALSE, FALSE, NULL, 'active', 9, 'oak-tree'),
  ('soft-drinks', 'Goli Soda', 'Old-school Indian soda pop — fun, fizzy, and full of nostalgia!', 4.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 10, 'oak-tree'),
  ('soft-drinks', 'Coke - Can', 'The timeless favorite — fizzy, cool, and always satisfying.', 2.07, NULL, TRUE, FALSE, FALSE, NULL, 'active', 11, 'oak-tree'),
  ('soft-drinks', 'Mexican Fanta', 'Burst of orange sweetness in every sip — pure sunshine in a bottle.', 5.19, NULL, TRUE, FALSE, FALSE, NULL, 'active', 12, 'oak-tree'),
  ('soft-drinks', 'Butter Milk', 'Cool, spiced yogurt drink — refreshing and perfect after a hearty meal.', 5.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 13, 'oak-tree'),
  ('soft-drinks', 'Smart Water', 'Hydration with a hint of purity — stay smart, stay refreshed.', 4.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 14, 'oak-tree'),
  ('soft-drinks', 'Zero Coke - Can', 'All the Coca-Cola taste with none of the sugar.', 2.07, NULL, TRUE, FALSE, FALSE, NULL, 'active', 15, 'oak-tree'),
  ('soft-drinks', 'Fresh Lemon Soda', 'Freshly squeezed lemon with sparkling soda — sweet, salty, or both!', 6.23, NULL, TRUE, FALSE, FALSE, NULL, 'active', 16, 'oak-tree'),
  ('soft-drinks', 'Topo Chico', 'The premium sparkling mineral water with a crisp, refreshing fizz.', 4.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 17, 'oak-tree'),
  ('soft-drinks', 'Salt Lassi', 'A savory yogurt drink that cools you from the inside out.', 5.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 18, 'oak-tree'),
  ('soft-drinks', 'Sprite Bottle', 'Zingy lemon-lime refreshment in every sip.', 4.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 19, 'oak-tree'),
  ('soft-drinks', 'Diet Coke - Bottle', 'Light, fizzy, and refreshing — the perfect guilt-free cola.', 4.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 20, 'oak-tree'),
  ('soft-drinks', 'Mexican Sprite', 'Extra fizzy, extra flavorful — the ultimate lemon-lime experience.', 5.19, NULL, TRUE, FALSE, FALSE, NULL, 'active', 21, 'oak-tree'),
  ('soft-drinks', 'Sweet Lassi', 'Creamy, sweet, and soothing — a traditional Indian favorite.', 5.19, NULL, TRUE, FALSE, FALSE, NULL, 'active', 22, 'oak-tree'),
  ('soft-drinks', 'Canada Dry', 'Classic ginger ale that pairs perfectly with rich, spicy meals.', 3.11, NULL, TRUE, FALSE, FALSE, 2, 'active', 23, 'oak-tree'),
  ('soft-drinks', 'Gingerale Can', 'Smooth and bubbly with a hint of ginger — a refreshing twist.', 2.07, NULL, TRUE, FALSE, FALSE, NULL, 'active', 24, 'oak-tree'),
  ('soft-drinks', 'GingerAle Bottle', 'Crisp and full-bodied ginger ale to refresh your palate.', 4.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 25, 'oak-tree'),
  ('soft-drinks', 'CanadaDry Can', 'Classic bubbly ginger flavor in a crisp, chilled can.', 2.07, NULL, TRUE, FALSE, FALSE, NULL, 'active', 26, 'oak-tree'),
  ('soft-drinks', 'Zero Coke - Bottle', 'Full flavor, zero sugar — enjoy the lighter side of Coke.', 4.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 27, 'oak-tree'),
  ('soft-drinks', 'Can Drinks', 'Your favorite chilled sodas — pick your pop and refresh instantly.', 2.07, NULL, TRUE, FALSE, FALSE, NULL, 'active', 28, 'oak-tree'),
  ('soft-drinks', 'Limca', 'The iconic lemony soda from India — cool, crisp, and citrusy.', 3.63, NULL, TRUE, FALSE, FALSE, NULL, 'active', 29, 'oak-tree'),
  ('soft-drinks', 'Topochico - Can', 'Bright mineral fizz with natural sparkle — refreshingly different.', 3.11, NULL, TRUE, FALSE, FALSE, NULL, 'active', 30, 'oak-tree'),
  ('soft-drinks', 'Mexican Coke', 'Made with real cane sugar — richer, smoother, and extra delicious!', 5.19, NULL, TRUE, FALSE, FALSE, NULL, 'active', 31, 'oak-tree'),
  ('chai', 'Irani Chai', 'Traditional Hyderabad-style tea — strong, creamy, and irresistibly aromatic.', 3.41, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('chai', 'Masala Chai', 'A comforting blend of tea, milk, and Indian spices — a cup of warmth in every sip.', 2.37, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'oak-tree'),
  ('coffee', 'DD spl Filter Coffee', 'South Indian-style filter coffee, brewed to perfection with rich aroma and flavor.', 4.99, NULL, TRUE, FALSE, TRUE, NULL, 'active', 1, 'oak-tree'),
  ('coffee', 'Instant Coffee(Bru)', 'Quick, strong, and smooth — India’s favorite instant coffee delight.', 3.11, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'oak-tree'),
  ('desserts', 'Apricot Delight', NULL, 8.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('desserts', 'Sweet Paan', 'Refreshing betel leaf delight filled with sweet nuts and flavors — the perfect after-meal treat.', 2.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'oak-tree'),
  ('desserts', 'Gulab Jamun', 'Soft, golden dumplings soaked in warm sugar syrup — a timeless Indian classic.', 6.23, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'oak-tree'),
  ('desserts', 'Double Ka Meetha', 'Hyderabadi bread pudding made with ghee, milk, and saffron — rich and royal.', 8.31, NULL, TRUE, FALSE, FALSE, NULL, 'active', 4, 'oak-tree'),
  ('desserts', 'Carrot Halwa', 'Slow-cooked carrots in milk and ghee, topped with nuts — pure indulgence.', 7.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 5, 'oak-tree'),
  ('desserts', 'Rasmalai', 'Soft cheese patties soaked in creamy, saffron milk — melt-in-mouth perfection.', 6.23, NULL, TRUE, FALSE, FALSE, NULL, 'active', 6, 'oak-tree'),
  ('desserts', 'Beetroot Halwa', 'A healthy twist on tradition — earthy beetroot cooked in milk and ghee.', 8.31, NULL, TRUE, FALSE, FALSE, NULL, 'active', 7, 'oak-tree'),
  ('desserts', 'Sorakaya Halwa', 'Delicately flavored bottle gourd halwa — light, rich, and wholesome.', 8.31, NULL, TRUE, FALSE, FALSE, NULL, 'active', 8, 'oak-tree'),
  ('desserts', 'DD Special Sweet', NULL, 12.47, NULL, TRUE, FALSE, TRUE, NULL, 'active', 9, 'oak-tree'),
  ('desserts', 'Badhusha (4pcs)', 'Flaky, golden sweet soaked in light syrup — crispy outside, soft inside.', 5.19, NULL, TRUE, FALSE, FALSE, NULL, 'active', 10, 'oak-tree'),
  ('desserts', 'Ice Cream', 'Chilled scoops of creamy delight — the perfect finish to your meal.', 6.23, NULL, TRUE, FALSE, FALSE, NULL, 'active', 11, 'oak-tree'),
  ('desserts', 'Gummadikaya Halwa', 'Pumpkin-based traditional sweet with rich ghee flavor and nutty aroma.', 8.31, NULL, TRUE, FALSE, FALSE, NULL, 'active', 12, 'oak-tree'),
  ('desserts', 'icecream gulabjamun', 'Warm gulab jamun paired with cold ice cream — a heavenly fusion dessert.', 8.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 13, 'oak-tree'),
  ('thalis', 'Veg Thali', 'A wholesome South Indian platter with flavorful curries, dal, rice, roti, and sweets — a perfect balance of taste and tradition.', 20.79, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('thalis', 'Non Veg Thali', 'A hearty feast featuring signature meat curries, rice, roti, and sides — crafted for true food lovers.', 22.87, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'oak-tree'),
  ('weekend-specials', 'Thalapakatty Mutton Biryani', NULL, 21.99, NULL, FALSE, FALSE, FALSE, NULL, 'inactive', 1, 'oak-tree'),
  ('weekend-specials', 'Bagara Rice with Mutton Curry', NULL, 18.99, NULL, FALSE, FALSE, FALSE, NULL, 'inactive', 2, 'oak-tree'),
  ('weekend-specials', 'Bagara Rice with Chicken Curry', NULL, 16.99, NULL, FALSE, FALSE, FALSE, NULL, 'inactive', 3, 'oak-tree'),
  ('weekend-specials', 'BreakfastBuffet - KIDS', NULL, 7.99, NULL, TRUE, FALSE, FALSE, NULL, 'inactive', 4, 'oak-tree'),
  ('weekend-specials', 'BreakfastBuffet -Adults', NULL, 15.99, NULL, TRUE, FALSE, FALSE, NULL, 'inactive', 5, 'oak-tree'),
  ('weekend-specials', 'Adult Buffet', NULL, 29.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 6, 'oak-tree'),
  ('weekend-specials', 'Kids Buffet', NULL, 19.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 7, 'oak-tree'),
  ('weekend-specials', 'Kamju Pitta Biryani', NULL, 19.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 8, 'oak-tree'),
  ('weekend-specials', 'Kamjupitta Tandoori', NULL, 19.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 9, 'oak-tree'),
  ('weekend-specials', 'Kamju Pitta Fry', NULL, 18.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 10, 'oak-tree'),
  ('weekend-specials', 'Kamju Pitta Mandi', NULL, 79.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 11, 'oak-tree'),
  ('weekend-specials', 'Nayudu Gari kamju Pitta Pulao', NULL, 29.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 12, 'oak-tree'),
  ('weekend-specials', 'Nayudu Gari Goat Pulao', 'Authentic Rayalaseema-style goat pulao — slow-cooked to perfection with rich spices and tender meat.', 29.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 13, 'oak-tree'),
  ('weekend-specials', 'Nayudu Gari Chicken Pulao', 'Aromatic chicken pulao inspired by Nayudu Gari tradition — flavorful, juicy, and perfectly spiced.', 29.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 14, 'oak-tree'),
  ('weekend-specials', 'NayuduGari Veg Pulao', 'Fragrant rice cooked with garden-fresh veggies and house spices — a royal vegetarian indulgence.', 28.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 15, 'oak-tree'),
  ('weekend-specials', 'NayuduGari Natukodi Pulao', 'Rustic country chicken pulao cooked in traditional style — spicy, soulful, and deeply satisfying.', 29.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 16, 'oak-tree'),
  ('weekend-specials', 'Thalapakattu Goat Biryani', 'Classic Tamil-style biryani with bold flavors, fluffy rice, and tender goat pieces — a timeless favorite.', 22.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 17, 'oak-tree'),
  ('tuesday-offers', 'CHICKEN BIRYANI (Tuesday TO GO)', 'Your favorite chicken biryani at a special Tuesday price — flavorful, filling, and ready to go!', 11, NULL, FALSE, FALSE, FALSE, NULL, 'active', 1, 'oak-tree'),
  ('tuesday-offers', 'MUTTON BIRYANI (Tuesday TO GO)', 'Slow-cooked mutton biryani with rich spices — an irresistible midweek treat.', 12, NULL, FALSE, FALSE, FALSE, NULL, 'active', 2, 'oak-tree'),
  ('tuesday-offers', 'VEG BIRYANI (Tuesday TO GO)', 'Aromatic vegetarian biryani — light, flavorful, and perfect for a weekday indulgence.', 11, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'oak-tree')
) AS v(cat_slug, name, description, price, image, veg, popular, chef_special, spice_level, status, display_order, location_id)
JOIN cat c ON c.slug = v.cat_slug
WHERE NOT EXISTS (
  SELECT 1 FROM public.menu_items mi
  JOIN public.menu_categories mc ON mc.id = mi.category_id
  WHERE mc.location_id = 'oak-tree' AND mc.slug = v.cat_slug AND mi.name = v.name
);

COMMIT;
