-- ============================================================
-- Desi Dhamaka — menu seed for Lawrenceville
-- location_id: lawrenceville
-- Source: desidhamakanj.net/lawrenceville/menu HTML export
-- Order URL: https://orders.chefgaa.com/store/desi-dhamaka/menu
-- Categories: 19 · Items: 344
-- Run supabase/clear_menu_locations.sql BEFORE this file.
-- Idempotent: re-running will not duplicate rows.
-- ============================================================

BEGIN;

-- Categories
INSERT INTO public.menu_categories (name, slug, image, display_order, status, location_id)
VALUES
  ('Soups', 'soups', NULL, 1, 'active', 'lawrenceville'),
  ('Vegetarian Appetizers', 'vegetarian-appetizers', NULL, 2, 'active', 'lawrenceville'),
  ('Non-Vegetarian Appetizers', 'non-vegetarian-appetizers', NULL, 3, 'active', 'lawrenceville'),
  ('Kebab & Tandooris', 'kebab-and-tandooris', NULL, 4, 'active', 'lawrenceville'),
  ('Naans & Breads', 'naans-and-breads', NULL, 5, 'active', 'lawrenceville'),
  ('Vegetarian Entrees', 'vegetarian-entrees', NULL, 6, 'active', 'lawrenceville'),
  ('Non-Vegetarian Entrees', 'non-vegetarian-entrees', NULL, 7, 'active', 'lawrenceville'),
  ('Vegetarian Rice & Biryani', 'vegetarian-rice-and-biryani', NULL, 8, 'active', 'lawrenceville'),
  ('Non-Veg Biryani', 'non-veg-biryani', NULL, 9, 'active', 'lawrenceville'),
  ('DD Special Mandi', 'dd-special-mandi', NULL, 10, 'active', 'lawrenceville'),
  ('DD Specials', 'dd-specials', NULL, 11, 'active', 'lawrenceville'),
  ('DD Family Packs', 'dd-family-packs', NULL, 12, 'active', 'lawrenceville'),
  ('Indo Chinese', 'indo-chinese', NULL, 13, 'active', 'lawrenceville'),
  ('Snacks', 'snacks', NULL, 14, 'active', 'lawrenceville'),
  ('Chai & Coffee', 'chai-and-coffee', NULL, 15, 'active', 'lawrenceville'),
  ('Soft Drinks', 'soft-drinks', NULL, 16, 'active', 'lawrenceville'),
  ('Kids Menu', 'kids-menu', NULL, 17, 'active', 'lawrenceville'),
  ('Desserts', 'desserts', NULL, 18, 'active', 'lawrenceville'),
  ('Thali', 'thali', NULL, 19, 'active', 'lawrenceville')
ON CONFLICT (location_id, slug) DO NOTHING;

-- Menu items
WITH cat AS (
  SELECT id, slug FROM public.menu_categories WHERE location_id = 'lawrenceville'
)
INSERT INTO public.menu_items (category_id, name, description, price, image, veg, popular, chef_special, spice_level, status, display_order, location_id)
SELECT c.id, v.name, v.description, v.price, v.image, v.veg, v.popular, v.chef_special, v.spice_level, v.status::public.content_status, v.display_order, v.location_id
FROM (VALUES
  ('soups', 'Desi Veg Manchow Soup', 'A vibrant blend of crisp vegetables and fragrant spices, topped with crunchy fried noodles and fresh cilantro for an irresistible finish.', 9.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'lawrenceville'),
  ('soups', 'Desi Chicken Manchow Soup', 'A vibrant fusion of tender chicken simmered in a spicy, aromatic broth with crunchy vegetables and a hint of tangy soy sauce.', 9.59, NULL, FALSE, FALSE, FALSE, 2, 'active', 2, 'lawrenceville'),
  ('soups', 'Natu Kodi Soup', 'Fragrant free-range chicken simmered to perfection with aromatic spices, fresh herbs, and a hint of tangy tamarind.', 10.35, NULL, FALSE, FALSE, FALSE, NULL, 'active', 3, 'lawrenceville'),
  ('soups', 'Goat Paya (Aattukal) Soup', 'Rich and aromatic — tender slow-cooked goat trotters in a blend of fragrant spices and herbs. Deep, comforting broth.', 10.35, NULL, FALSE, FALSE, FALSE, NULL, 'active', 4, 'lawrenceville'),
  ('vegetarian-appetizers', 'Punjabi Samosa', 'Crispy golden pastries stuffed with spiced potatoes, peas, and aromatic herbs. Served with tangy tamarind chutney.', 10.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'lawrenceville'),
  ('vegetarian-appetizers', 'Paneer Pepper Fry', 'Tender paneer with colorful bell peppers, aromatic spices, and a hint of tangy lime. Pan-seared to perfection.', 15.59, NULL, TRUE, FALSE, FALSE, 2, 'active', 2, 'lawrenceville'),
  ('vegetarian-appetizers', 'Mushroom Pepper Fry', 'Tender sautéed mushrooms with vibrant bell peppers and a drizzle of zesty lime.', 14.59, NULL, TRUE, FALSE, FALSE, 2, 'active', 3, 'lawrenceville'),
  ('vegetarian-appetizers', 'Baby Corn Pepper Fry', 'Crispy baby corn tossed in vibrant bell peppers and aromatic spices. Finished with fresh herbs.', 14.59, NULL, TRUE, FALSE, FALSE, 2, 'active', 4, 'lawrenceville'),
  ('vegetarian-appetizers', 'Gobi Pepper Fry', 'Crispy cauliflower stir-fried with bell peppers, aromatic spices, and a hint of tangy tamarind.', 14.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 5, 'lawrenceville'),
  ('vegetarian-appetizers', 'Corn Masala Fry', 'Golden corn kernels tossed in fragrant spices, finished with fresh cilantro and a squeeze of lime.', 14.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 6, 'lawrenceville'),
  ('vegetarian-appetizers', 'Gobi 65', 'Crispy cauliflower florets marinated in aromatic spices and tangy yogurt, deep-fried golden. Served with mint chutney.', 14.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 7, 'lawrenceville'),
  ('vegetarian-appetizers', 'Hyderabad Paneer 65', 'Crispy marinated paneer in vibrant South Indian spices, fried golden. Served with zesty mint chutney.', 15.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 8, 'lawrenceville'),
  ('vegetarian-appetizers', 'Onion Pakoda', 'Crispy golden fritters with thinly sliced onions, fragrant spices, and light chickpea batter.', 14.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 9, 'lawrenceville'),
  ('vegetarian-appetizers', 'Spinach Pakoda', 'Crispy spinach pakodas delicately spiced and expertly fried, served with zesty tamarind chutney.', 14.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 10, 'lawrenceville'),
  ('vegetarian-appetizers', 'Cashew Pakoda', 'Crispy pakodas featuring crunchy roasted cashews in spiced chickpea batter, served with tamarind chutney.', 15.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 11, 'lawrenceville'),
  ('vegetarian-appetizers', 'Chilli Baby Corn', 'Crisp baby corn in fiery chili, garlic, and soy sauce, fried golden. Served with tangy dipping sauce.', 14.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 12, 'lawrenceville'),
  ('vegetarian-appetizers', 'Chilli Gobi', 'Crispy cauliflower in fiery spices and tangy chili sauce. Garnished with cilantro and served with yogurt dip.', 14.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 13, 'lawrenceville'),
  ('vegetarian-appetizers', 'Chilli Mushroom', 'Tender mushrooms tossed in zesty garlic, ginger, and vibrant chili peppers. Finished with fresh coriander.', 14.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 14, 'lawrenceville'),
  ('vegetarian-appetizers', 'Chilli Lotus Root', 'Crispy lotus root stir-fried in fiery chili sauce, garnished with scallions and sesame seeds.', 15.59, NULL, TRUE, FALSE, FALSE, 2, 'active', 15, 'lawrenceville'),
  ('vegetarian-appetizers', 'Chilli Paneer', 'Crispy golden paneer in vibrant spicy chili sauce with garlic and tangy soy. Garnished with cilantro.', 15.59, NULL, TRUE, FALSE, FALSE, 2, 'active', 16, 'lawrenceville'),
  ('vegetarian-appetizers', 'Veg Manchurian', 'Crispy bite-sized vegetable balls in tangy, spicy Manchurian sauce, garnished with green onions.', 14.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 17, 'lawrenceville'),
  ('vegetarian-appetizers', 'Baby Corn Manchurian', 'Crispy baby corn tossed in tangy, spicy Manchurian sauce, garnished with fresh spring onions and garlic.', 14.59, NULL, TRUE, FALSE, FALSE, 2, 'active', 18, 'lawrenceville'),
  ('vegetarian-appetizers', 'Lotus Root Manchurian', 'Crispy lotus root in fragrant soy, garlic, and ginger, tossed with bell peppers, scallions, and sesame seeds.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 19, 'lawrenceville'),
  ('vegetarian-appetizers', 'Gobi Manchurian', 'Crispy golden cauliflower in tangy, spicy Manchurian sauce with soy, garlic, and chili. Garnished with cilantro.', 14.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 20, 'lawrenceville'),
  ('vegetarian-appetizers', 'Paneer Manchurian', 'Soft paneer cubes in a rich, tangy Manchurian gravy.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 21, 'lawrenceville'),
  ('vegetarian-appetizers', 'Mushroom Manchurian', 'Crispy mushroom bites in tangy Manchurian sauce — a delightful blend of savory and spicy flavors.', 14.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 22, 'lawrenceville'),
  ('vegetarian-appetizers', 'Paneer 555', 'Succulent paneer cubes marinated in a tantalizing mix of spices and grilled to perfection.', 15.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 23, 'lawrenceville'),
  ('vegetarian-appetizers', 'Gobi 555', 'Crispy cauliflower tossed in a tangy, spicy sauce — a flavor-packed vegetarian delight.', 15.59, NULL, TRUE, FALSE, FALSE, 2, 'active', 24, 'lawrenceville'),
  ('vegetarian-appetizers', 'Baby Corn 555', 'Crispy golden baby corn coated in a savory blend of spices and fried to perfection.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 25, 'lawrenceville'),
  ('vegetarian-appetizers', 'Mushroom 555', 'Sautéed mushrooms, garlic, and herbs in a tantalizing 555 spice blend.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 26, 'lawrenceville'),
  ('vegetarian-appetizers', 'Vegetable Bullets', 'Crispy mixed vegetable bullets fried golden.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 27, 'lawrenceville'),
  ('vegetarian-appetizers', 'Paneer Burji Dry', 'Aromatic crumbled paneer sautéed with onions, tomatoes, and spices. A flavorful starter.', 16.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 28, 'lawrenceville'),
  ('vegetarian-appetizers', 'Paneer Majestic', 'Succulent paneer cubes in a tantalizing blend of spices — a vegetarian delight with burst of flavors.', 16.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 29, 'lawrenceville'),
  ('vegetarian-appetizers', 'Gobi Majestic', 'Crispy cauliflower florets in a tangy and aromatic sauce. A delightful vegetarian appetizer.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 30, 'lawrenceville'),
  ('vegetarian-appetizers', 'Mushroom Majestic', 'Rich earthy mushrooms sautéed to perfection — a vegetarian delight that will tantalize your taste buds.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 31, 'lawrenceville'),
  ('vegetarian-appetizers', 'Baby Corn Majestic', 'Tender baby corn in a flavorful blend of spices and sauces — crispy and delightful.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 32, 'lawrenceville'),
  ('vegetarian-appetizers', 'Plantain Bajji with Coconut Dip', 'Crispy plantain bajji served with a creamy coconut dip — a vegetarian starter bursting with savory flavors.', 15.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 33, 'lawrenceville'),
  ('vegetarian-appetizers', 'Chana Pepper Fry', 'Bold chickpeas sautéed with vibrant peppers and aromatic spices in this delightful vegetarian appetizer.', 14.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 34, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Ameerpet Egg Fry', 'Perfectly fried eggs seasoned with aromatic spices. Served hot and bursting with flavor.', 15.59, NULL, FALSE, FALSE, FALSE, NULL, 'active', 1, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Chilli Egg', 'Crispy fried eggs tossed in a zesty chili sauce — a flavor explosion in every bite.', 16.59, NULL, FALSE, FALSE, FALSE, 2, 'active', 2, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Chilli Chicken', 'Tender chicken stir-fried with vibrant bell peppers and onions in a zesty blend of spicy Asian flavors.', 16.59, NULL, FALSE, FALSE, FALSE, 2, 'active', 3, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Chicken 65 Dry', 'Tender chicken in aromatic spices, fried to crispy, flavorful perfection. A South Indian classic.', 16.59, NULL, FALSE, FALSE, FALSE, 2, 'active', 4, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Chicken Majestic', 'Tender chicken in a flavorful blend of spices, sautéed and finished with cream and herbs.', 16.59, NULL, FALSE, FALSE, FALSE, NULL, 'active', 5, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Chicken Pepper Fry', 'Tender chicken with colorful bell peppers and aromatic spices — zesty and flavorful.', 16.59, NULL, FALSE, FALSE, FALSE, 2, 'active', 6, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Chicken Manchurian', 'Succulent chicken in tangy, savory Manchurian sauce — a perfect balance of sweet and spicy.', 16.59, NULL, FALSE, FALSE, FALSE, 2, 'active', 7, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Hyd Chicken 65 Wet', 'Tender spiced chicken cooked to juicy perfection in a luscious, tangy sauce. Bursting with Hyderabad flavor.', 16.59, NULL, FALSE, FALSE, FALSE, 2, 'active', 8, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Chicken Lollipop', 'Tender drumettes marinated in spices and herbs, deep-fried crispy. Served with zesty dipping sauce.', 17.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 9, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Hell of Chicken Drums', 'Crispy, fiery chicken drums in a devilish blend of spices. Sets your taste buds ablaze!', 18.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 10, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Chicken 555', 'Succulent chicken bites marinated in five flavorful spices, perfectly grilled to juicy perfection.', 17.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 11, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Kothimeera Chicken', 'Chicken cooked with fresh coriander and bold spices.', 17.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 12, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Karivepaaku Kodi', 'Crispy chicken marinated in aromatic curry leaves and spices, fried to perfection.', 17.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 13, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Guntur Karampodi Kodi', 'Succulent chicken in spicy Guntur chili powder, fried to perfection — heat and flavor in every bite.', 17.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 14, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Andhra Kodi Vepudu (Bone-In)', 'Tender bone-in chicken in flavorful Andhra-style spice blend — tantalizing aroma, perfect heat.', 17.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 15, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Andhra Kodi Vepudu (Boneless)', 'Tender boneless chicken sautéed with traditional Andhra spices for a flavorful kick.', 18.67, NULL, FALSE, FALSE, FALSE, NULL, 'active', 16, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Mirapakaya Kodi Vepudu', 'Spicy chicken with green chilies and traditional spices — perfect balance of heat and savory goodness.', 17.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 17, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Natu Kodi Roast', 'Tender chicken in traditional Indian spices, slow-roasted. Served with mint chutney.', 19.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 18, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Mutton Ghee Roast (Bone-In)', 'Tender bone-in mutton pieces in rich spices, sautéed in fragrant ghee until perfectly roasted.', 19.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 19, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Mutton Ghee Roast (Boneless)', 'Tender boneless mutton in aromatic ghee — rich and flavorful roast with traditional spices.', 21.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 20, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Gongura Mamsam Fry (Bone-In)', 'Tender bone-in mutton marinated in tangy gongura sauce and expertly fried to perfection.', 19.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 21, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Gongura Mamsam Fry (Boneless)', 'Tender boneless lamb marinated in tangy gongura sauce and pan-fried to perfection.', 21.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 22, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Mutton Sukka (Bone-In)', 'Tender mutton chunks in aromatic spices, sautéed with onions and curry leaves — burst of flavor.', 19.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 23, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Mutton Sukka (Boneless)', 'Tender boneless mutton in a flavorful blend of spices — succulent and aromatic.', 21.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 24, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Palnadu Mamsam Roast (Bone-In)', 'Traditional bone-in mutton roast with rustic Palnadu spices.', 19.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 25, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Palnadu Mamsam Roast (Boneless)', 'Tender boneless lamb in spicy Palnadu style roast, bursting with bold South Indian flavors.', 21.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 26, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Mutton Pepper Fry (Bone-In)', 'Tender mutton in peppercorns and spices, pan-fried for a crispy exterior and juicy interior.', 19.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 27, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Mutton Pepper Fry (Boneless)', 'Tender boneless mutton sautéed with fiery aromatic peppercorns and spices.', 21.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 28, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Fish 65', 'Crispy and flavorful fish marinated with aromatic spices and deep-fried to perfection.', 18.67, NULL, FALSE, FALSE, FALSE, 2, 'active', 29, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Apollo Fish', 'Crispy fish marinated in exotic spices — a delightful fusion of tangy and spicy flavors.', 18.67, NULL, FALSE, FALSE, FALSE, 2, 'active', 30, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'DD SPL Cilantro Fish', 'Fresh fish marinated in fragrant cilantro-infused blend, grilled to perfection.', 18.67, NULL, FALSE, FALSE, TRUE, NULL, 'active', 31, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Gongura Royyala Vepudu', 'Tender shrimp sautéed with tangy gongura leaves and aromatic spices — a South Indian delicacy.', 19.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 32, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Black Pepper Prawns', 'Juicy prawns sautéed with a bold kick of black pepper — savory and aromatic.', 19.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 33, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Loose Prawns', 'Tender prawns delicately seasoned and lightly fried. Served with zesty dipping sauce.', 19.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 34, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Godavari Fish Fry', 'Crispy marinated fish fillets fried to golden perfection — a tantalizing blend of spices.', 22.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 35, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Shrimp Majestic', 'Plump shrimp in exotic spices, grilled to perfection. Served with zesty citrus aioli.', 19.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 36, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Chilli Shrimp', 'Crispy shrimp tossed in a bold, spicy chilli sauce.', 19.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 37, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Shrimp Fry', 'Crispy golden shrimp fried to perfection, served with zesty cocktail sauce.', 19.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 38, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Pachi Mirchi Kodi Vepudu', 'Tender chicken stir-fried with green chilies, curry leaves, and aromatic spices.', 16.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 39, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Fish Tikka Kebab', 'Tender chunks of marinated fish, expertly grilled with aromatic spices.', 21.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 40, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Andhra Chilli Chicken', 'Tender chicken in fiery Andhra spices, sautéed with bell peppers and onions.', 16.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 41, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Party Chicken Wings', 'Crispy and flavorful wings tossed in tangy party sauce — a crowd-pleasing appetizer.', 20.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 42, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Mutton Milagu Pirattal (Bone-In)', 'Tender bone-in mutton tossed in a fragrant blend of black pepper and spices.', 19.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 43, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Fish Amritsar', 'Tender fillets marinated in Indian spices and fried golden. Served with zesty mango chutney.', 21.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 44, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Shrimp Koli Wada with Jalapeno Sauce', 'Crispy shrimp fritters, perfectly spiced and served with a zesty jalapeno sauce.', 21.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 45, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Sesame Prawn Roast', 'Plump prawns glazed in a savory sesame marinade and roasted to perfection.', 21.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 46, 'lawrenceville'),
  ('non-vegetarian-appetizers', 'Party Chicken Wild Wings', 'Succulent wings tossed in a zesty wild sauce — a party in every bite!', 20.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 47, 'lawrenceville'),
  ('kebab-and-tandooris', 'Paneer Tikka Kebab', 'Succulent paneer cubes grilled to perfection in a traditional tandoor oven — smoky flavors and aromatic spices.', 17.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'lawrenceville'),
  ('kebab-and-tandooris', 'Makhmali Paneer Tikka', 'Tender paneer in a velvety blend of spices, grilled to perfection. Melt-in-your-mouth delight.', 17.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'lawrenceville'),
  ('kebab-and-tandooris', 'Chicken Tandoori', 'Tender marinated chicken infused with aromatic Indian spices, grilled in our tandoor. Served with raita.', 17.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 3, 'lawrenceville'),
  ('kebab-and-tandooris', 'Seekh Kebab (Chicken)', 'Succulent chicken seekh, expertly seasoned and grilled in our traditional tandoor oven.', 21.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 4, 'lawrenceville'),
  ('kebab-and-tandooris', 'Mixed Veg Kebab (Gobi/Mushroom/Paneer/Peppers)', 'Perfectly grilled cauliflower, mushrooms, marinated paneer, and vibrant peppers.', 18.67, NULL, TRUE, FALSE, FALSE, NULL, 'active', 5, 'lawrenceville'),
  ('kebab-and-tandooris', 'Chicken Tikka Kebab', 'Tender marinated chicken grilled to perfection in our traditional tandoori oven.', 18.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 6, 'lawrenceville'),
  ('kebab-and-tandooris', 'Tangdi Kebab', 'Juicy chicken drumsticks marinated in aromatic spices, grilled in a traditional tandoor.', 18.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 7, 'lawrenceville'),
  ('kebab-and-tandooris', 'Chicken Seekh Kebab', 'Tender spiced ground chicken skewered and grilled to perfection. Served with cooling raita.', 18.67, NULL, FALSE, FALSE, FALSE, NULL, 'active', 8, 'lawrenceville'),
  ('kebab-and-tandooris', 'Chicken Chapli', 'Flavorful Chicken Chapli kebab — minced chicken, aromatic spices, and fresh herbs, grilled to perfection.', 18.67, NULL, FALSE, FALSE, FALSE, NULL, 'active', 9, 'lawrenceville'),
  ('kebab-and-tandooris', 'Chicken Hariyali', 'Tender chicken in vibrant fresh mint, cilantro, and aromatic spices, grilled to juicy perfection.', 18.67, NULL, FALSE, FALSE, FALSE, NULL, 'active', 10, 'lawrenceville'),
  ('kebab-and-tandooris', 'Murg Malai Kebab', 'Tender chicken in creamy yogurt, cashew paste, and aromatic spices. A melt-in-your-mouth tandoori delight.', 18.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 11, 'lawrenceville'),
  ('kebab-and-tandooris', 'Tawa Fish', 'Flavorful Tawa Fish grilled with aromatic spices — succulent seafood served sizzling hot.', 20.75, NULL, FALSE, FALSE, FALSE, NULL, 'active', 12, 'lawrenceville'),
  ('kebab-and-tandooris', 'Tandoori Jinga', 'Jumbo prawns in tandoori spices, grilled over coals.', 21.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 13, 'lawrenceville'),
  ('kebab-and-tandooris', 'Tandoori Pomfret', 'Succulent whole fish marinated and delicately grilled in a traditional tandoor oven.', 21.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 14, 'lawrenceville'),
  ('kebab-and-tandooris', 'Pathar Ka Gosht (Goat)', 'Thinly sliced goat cooked on a hot stone slab with spices.', 22.83, NULL, FALSE, FALSE, FALSE, NULL, 'active', 15, 'lawrenceville'),
  ('kebab-and-tandooris', 'DD SPL Non Veg Kebab Platter', 'A flavorful platter of juicy grilled chicken kebabs, marinated in aromatic spices and cooked to perfection for every bite.', 25.95, NULL, TRUE, FALSE, TRUE, NULL, 'active', 16, 'lawrenceville'),
  ('kebab-and-tandooris', 'Reshmi Kebab – Chicken', 'Tender chicken in aromatic spices, grilled to perfection — mouthwatering delight.', 21.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 17, 'lawrenceville'),
  ('naans-and-breads', 'Roti', 'Flaky traditional Indian flatbread, served warm — the ideal accompaniment to any curry.', 4.11, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'lawrenceville'),
  ('naans-and-breads', 'Butter Roti', 'Soft Indian flatbread brushed with rich, creamy butter. Warm and buttery goodness.', 4.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'lawrenceville'),
  ('naans-and-breads', 'Plain Naan', 'Soft and pillowy, baked with a hint of char from our tandoor oven. Perfect with any dish.', 4.11, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'lawrenceville'),
  ('naans-and-breads', 'Butter Naan', 'Soft and fluffy naan infused with rich buttery flavor, baked golden to perfection.', 5.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 4, 'lawrenceville'),
  ('naans-and-breads', 'Garlic Naan', 'Freshly baked Garlic Naan infused with aromatic garlic and herbs — crispy outside, fluffy inside.', 5.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 5, 'lawrenceville'),
  ('naans-and-breads', 'Chilli Garlic Naan', 'A fiery twist — zesty garlic and spicy chilli, baked crispy in our traditional tandoor.', 5.15, NULL, TRUE, FALSE, FALSE, 2, 'active', 6, 'lawrenceville'),
  ('naans-and-breads', 'Cheese Naan', 'Warm fluffy naan with a blend of gooey melted cheese — a delectable twist on a classic.', 5.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 7, 'lawrenceville'),
  ('naans-and-breads', 'Chilli Cheese Naan', 'Warm fluffy naan stuffed with gooey melted cheese and a kick of spicy chillies.', 5.15, NULL, TRUE, FALSE, FALSE, 2, 'active', 8, 'lawrenceville'),
  ('naans-and-breads', 'Peshwari Naan', 'Indian flatbread filled with sweet and nutty blend of coconut, raisins, and almonds.', 5.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 9, 'lawrenceville'),
  ('naans-and-breads', 'Onion Kulcha', 'Fragrant oven-baked naan infused with caramelized onions — sweet and savory blend.', 5.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 10, 'lawrenceville'),
  ('naans-and-breads', 'Lachha Paratha', 'Flaky and buttery Indian flatbread, hand-stretched and layered to perfection.', 6.19, NULL, TRUE, FALSE, FALSE, NULL, 'active', 11, 'lawrenceville'),
  ('naans-and-breads', 'Malabar Paratha', 'Soft and flaky Malabar Paratha, cooked golden — buttery delight on its own or with curry.', 6.19, NULL, TRUE, FALSE, FALSE, NULL, 'active', 12, 'lawrenceville'),
  ('naans-and-breads', 'Bread Basket', 'A variety of freshly baked naans served warm and perfect for sharing.', 17.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 13, 'lawrenceville'),
  ('vegetarian-entrees', 'Dal Tadka', 'Fragrant lentils with aromatic spices, finished with sizzling tempering of ghee, cumin, and garlic.', 14.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'lawrenceville'),
  ('vegetarian-entrees', 'Tomato Dal', 'Comforting blend of lentils and tomatoes simmered with aromatic spices — Indian comfort food.', 14.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'lawrenceville'),
  ('vegetarian-entrees', 'Mango Dal', 'Luscious mango and creamy lentils in fragrant spices — a tantalizing blend of sweet and savory.', 14.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'lawrenceville'),
  ('vegetarian-entrees', 'Palak Dal', 'Lentils simmered with fresh spinach and aromatic spices — hearty vegetarian nourishment.', 14.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 4, 'lawrenceville'),
  ('vegetarian-entrees', 'Dal Makhani', 'Creamy black lentils slow-cooked with aromatic spices, butter, and fresh cream.', 14.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 5, 'lawrenceville'),
  ('vegetarian-entrees', 'Shahi Paneer', 'Succulent paneer simmered in a rich, creamy tomato and cashew sauce — fit for royalty.', 15.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 6, 'lawrenceville'),
  ('vegetarian-entrees', 'Chana Saag', 'Tender chickpeas and fresh spinach simmered in aromatic spices — a vegetarian delight.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 7, 'lawrenceville'),
  ('vegetarian-entrees', 'Bendi Masala', 'Crispy okra in a bold, spiced masala gravy.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 8, 'lawrenceville'),
  ('vegetarian-entrees', 'Bendi Vepudu', 'Tender okra sautéed with aromatic spices and onions — a comforting South Indian dish.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 9, 'lawrenceville'),
  ('vegetarian-entrees', 'Bendi Pulusu', 'Tender okra simmered in tangy tamarind sauce with a blend of aromatic spices.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 10, 'lawrenceville'),
  ('vegetarian-entrees', 'Kadai Bendi', 'Tender okra cooked with aromatic spices in a traditional kadai pan.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 11, 'lawrenceville'),
  ('vegetarian-entrees', 'Chana Masala', 'Aromatic chickpea curry in rich spices and tomatoes — a vegetarian delight.', 15.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 12, 'lawrenceville'),
  ('vegetarian-entrees', 'Paneer Burji Gravy', 'Crumbled paneer in luscious gravy of aromatic spices. Pairs perfectly with naan or rice.', 15.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 13, 'lawrenceville'),
  ('vegetarian-entrees', 'Chettinad Mushroom', 'Bold mushrooms cooked in a fragrant blend of South Indian spices.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 14, 'lawrenceville'),
  ('vegetarian-entrees', 'Chettinad Paneer', 'Tender paneer in flavorful Chettinad spice blend — rich and aromatic.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 15, 'lawrenceville'),
  ('vegetarian-entrees', 'Chettinad Mix Veg', 'Seasonal vegetables in a rich, aromatic Chettinad spice mix.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 16, 'lawrenceville'),
  ('vegetarian-entrees', 'Aloo Gobi', 'Tender cauliflower and potatoes in fragrant spices — a comforting vegetarian entrée.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 17, 'lawrenceville'),
  ('vegetarian-entrees', 'Aloo Palak', 'Tender spinach sautéed with aromatic spices and hearty potatoes.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 18, 'lawrenceville'),
  ('vegetarian-entrees', 'Aloo Mutter', 'Tender peas and potatoes in a fragrant blend of spices — comforting and flavorful.', 16.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 19, 'lawrenceville'),
  ('vegetarian-entrees', 'Kadai Veg', 'Mixed vegetables sautéed in aromatic spices and simmered in a traditional kadai.', 16.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 20, 'lawrenceville'),
  ('vegetarian-entrees', 'Kadai Paneer', 'Tender paneer with bell peppers, onions, and aromatic Indian spices — rich and satisfying.', 16.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 21, 'lawrenceville'),
  ('vegetarian-entrees', 'Kadai Mushroom', 'Bold sautéed mushrooms, bell peppers, and onions in a rich tomato-based sauce.', 16.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 22, 'lawrenceville'),
  ('vegetarian-entrees', 'Veg Korma', 'Aromatic medley of fresh vegetables in a creamy, spiced coconut and cashew sauce.', 16.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 23, 'lawrenceville'),
  ('vegetarian-entrees', 'Paneer Korma', 'Succulent paneer in a rich, spiced cashew and yogurt sauce — creamy and aromatic.', 16.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 24, 'lawrenceville'),
  ('vegetarian-entrees', 'Aloo Korma', 'Tender potatoes in a creamy, aromatic sauce of spices and herbs.', 16.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 25, 'lawrenceville'),
  ('vegetarian-entrees', 'Mushroom Korma', 'Velvety mushrooms in a creamy aromatic blend of spices and coconut milk.', 16.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 26, 'lawrenceville'),
  ('vegetarian-entrees', 'Gutti Vankaya (Stuffed Brinjal)', 'Tender brinjal stuffed with spices, nuts, and herbs — a vegetarian delicacy.', 16.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 27, 'lawrenceville'),
  ('vegetarian-entrees', 'Punjabi Palak Paneer', 'Creamy spinach with aromatic spices and chunks of soft paneer cheese.', 16.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 28, 'lawrenceville'),
  ('vegetarian-entrees', 'Paneer Tikka Masala', 'Grilled paneer in rich, creamy tomato-based masala sauce.', 16.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 29, 'lawrenceville'),
  ('vegetarian-entrees', 'Paneer Butter Masala', 'Tender paneer in a rich tomato and butter sauce — a classic vegetarian favorite.', 16.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 30, 'lawrenceville'),
  ('vegetarian-entrees', 'Navratan Korma', 'Nine garden-fresh vegetables in a luscious cashew cream sauce — a royal medley.', 16.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 31, 'lawrenceville'),
  ('vegetarian-entrees', 'Malai Kofta', 'Vegetable and paneer dumplings in a rich, creamy cashew and tomato gravy.', 16.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 32, 'lawrenceville'),
  ('vegetarian-entrees', 'Kaju Curry', 'Creamy cashew curry with a rich blend of spices and tender vegetables.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 33, 'lawrenceville'),
  ('non-vegetarian-entrees', 'Egg Bhurji Dry', 'Scrambled eggs with aromatic spices, tomatoes, and onions — flavorful and satisfying.', 14.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 1, 'lawrenceville'),
  ('non-vegetarian-entrees', 'Egg Pulusu', 'Tender eggs simmered in tangy tamarind-based gravy — a flavorful South Indian delicacy.', 16.59, NULL, FALSE, FALSE, FALSE, NULL, 'active', 2, 'lawrenceville'),
  ('non-vegetarian-entrees', 'Chicken Vindaloo', 'Tender chicken in a fiery blend of vinegar, garlic, and spices — traditional Indian cuisine.', 17.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 3, 'lawrenceville'),
  ('non-vegetarian-entrees', 'Andhra Chicken Curry', 'Tender chicken in flavorful Andhra spices — a rich and aromatic curry.', 17.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 4, 'lawrenceville'),
  ('non-vegetarian-entrees', 'Chicken Mughlai', 'Tender chicken in rich aromatic Mughlai sauce with creamy yogurt and fragrant spices.', 17.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 5, 'lawrenceville'),
  ('non-vegetarian-entrees', 'Chicken Chettinad', 'Tender chicken in a rich aromatic blend of South Indian spices.', 17.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 6, 'lawrenceville'),
  ('non-vegetarian-entrees', 'Methi Chicken', 'Tender chicken with aromatic fenugreek leaves — a traditional Indian savory delight.', 17.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 7, 'lawrenceville'),
  ('non-vegetarian-entrees', 'Chicken Tikka Masala', 'Tender chicken in aromatic spices, cooked in a rich, creamy tomato-based curry sauce.', 17.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 8, 'lawrenceville'),
  ('non-vegetarian-entrees', 'Chicken Karaikudi', 'Tender chicken in aromatic spices and coconut milk — South Indian Karaikudi flavors.', 17.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 9, 'lawrenceville'),
  ('non-vegetarian-entrees', 'Butter Chicken', 'Tender chicken in a rich tomato and butter sauce — a classic favorite with aromatic spices.', 17.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 10, 'lawrenceville'),
  ('non-vegetarian-entrees', 'Desi Chicken Curry (With Bone)', 'Tender chicken in traditional Indian spices — a rich and flavorful homestyle curry.', 17.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 11, 'lawrenceville'),
  ('non-vegetarian-entrees', 'Railway Chicken Curry (With Bone)', 'Tender chicken in aromatic spices and tomatoes — a classic Indian curry.', 17.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 12, 'lawrenceville'),
  ('non-vegetarian-entrees', 'DD Chef''s Special Chicken Curry (Homestyle)', 'A nostalgic homestyle chicken curry with hand-pounded spices — bursting with authentic flavor.', 18.67, NULL, FALSE, FALSE, TRUE, NULL, 'active', 13, 'lawrenceville'),
  ('non-vegetarian-entrees', 'Natu Kodi Curry', 'Tender chicken in a rich curry sauce with traditional South Indian spices.', 19.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 14, 'lawrenceville'),
  ('non-vegetarian-entrees', 'Hyderabadi Goat Curry', 'Tender goat in a fragrant blend of traditional Hyderabadi spices — authentic and aromatic.', 19.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 15, 'lawrenceville'),
  ('non-vegetarian-entrees', 'Goat Vindaloo', 'Tender goat in spicy vinegar, ginger, and aromatic spices — slow-cooked to perfection.', 19.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 16, 'lawrenceville'),
  ('non-vegetarian-entrees', 'Kashmiri Goat Rogan Josh', 'Tender goat in a rich aromatic blend of traditional Kashmiri spices.', 19.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 17, 'lawrenceville'),
  ('non-vegetarian-entrees', 'Goat Chettinad', 'Tender goat in toasted spices, coconut, and curry leaves — rich and flavorful.', 19.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 18, 'lawrenceville'),
  ('non-vegetarian-entrees', 'Goat Mughalai', 'Tender goat in a rich and creamy Mughalai sauce, bursting with aromatic flavors.', 19.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 19, 'lawrenceville'),
  ('non-vegetarian-entrees', 'DD Chef''s Special Mutton Curry (Homestyle)', 'Succulent mutton in a rich, aromatic curry sauce — a true taste of culinary craftsmanship.', 20.75, NULL, FALSE, FALSE, TRUE, NULL, 'active', 20, 'lawrenceville'),
  ('non-vegetarian-entrees', 'Goan Fish Curry', 'Fresh fish in fragrant coconut and spice-infused curry sauce — inspired by Goa.', 18.67, NULL, FALSE, FALSE, FALSE, NULL, 'active', 21, 'lawrenceville'),
  ('non-vegetarian-entrees', 'Chepala Pulusu', 'Tender fish in tangy tamarind sauce with aromatic spices — flavorful and satisfying.', 18.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 22, 'lawrenceville'),
  ('non-vegetarian-entrees', 'Royyala Pulusu', 'Tender shrimp in tangy tamarind sauce with a medley of aromatic spices.', 19.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 23, 'lawrenceville'),
  ('non-vegetarian-entrees', 'Bhimavaram Royyala Vepudu', 'Bold Andhra-style spicy shrimp stir-fry bursting with aromatic spices and curry leaves.', 21.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 24, 'lawrenceville'),
  ('non-vegetarian-entrees', 'Royyala Vepudu', 'South Indian shrimp stir-fry bursting with aromatic spices and fresh curry leaves.', 21.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 25, 'lawrenceville'),
  ('non-vegetarian-entrees', 'Mutton Milagu Pirattal (Boneless)', 'Tender boneless mutton in a fragrant blend of black pepper and spices.', 21.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 26, 'lawrenceville'),
  ('vegetarian-rice-and-biryani', 'Jeera Rice', 'Fragrant basmati rice with cumin seeds and aromatic spices — pairs perfectly with any curry.', 14.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'lawrenceville'),
  ('vegetarian-rice-and-biryani', 'Curd Rice', 'Creamy South Indian rice mixed with yogurt, mustard seeds, curry leaves, and green chili.', 14.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 2, 'lawrenceville'),
  ('vegetarian-rice-and-biryani', 'Veg Biryani', 'Aromatic basmati rice with fresh vegetables, fragrant spices, and herbs.', 16.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'lawrenceville'),
  ('vegetarian-rice-and-biryani', 'Chilli Mushroom Biryani', 'Juicy mushrooms with garlic, ginger, and chili peppers, layered with fragrant basmati rice.', 16.59, NULL, TRUE, FALSE, FALSE, 2, 'active', 4, 'lawrenceville'),
  ('vegetarian-rice-and-biryani', 'Gobi Masala Biryani', 'Aromatic basmati rice with fragrant spices, tender cauliflower, and savory masalas.', 16.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 5, 'lawrenceville'),
  ('vegetarian-rice-and-biryani', 'Cut Mirchi Biryani', 'Spicy Cut Mirchi Biryani with fragrant basmati rice and fiery green chilies.', 16.59, NULL, TRUE, FALSE, FALSE, 2, 'active', 6, 'lawrenceville'),
  ('vegetarian-rice-and-biryani', 'Paneer Biryani', 'Aromatic blend of fragrant basmati rice, succulent paneer, and a symphony of spices.', 17.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 7, 'lawrenceville'),
  ('vegetarian-rice-and-biryani', 'Gutti Vankaya Biryani', 'Aromatic basmati rice with stuffed baby eggplants and fragrant spices — a traditional delight.', 17.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 8, 'lawrenceville'),
  ('vegetarian-rice-and-biryani', 'Ulavacharu Biryani (Veg)', 'Aromatic basmati rice with lentils and flavorful spices — rich vegetarian goodness.', 17.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 9, 'lawrenceville'),
  ('vegetarian-rice-and-biryani', 'Ulavacharu Biryani (Paneer)', 'Flavorful Ulavacharu Biryani with succulent paneer and aromatic spices.', 17.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 10, 'lawrenceville'),
  ('vegetarian-rice-and-biryani', 'Gongura Biryani (Veg)', 'Aromatic basmati rice with tangy gongura leaves and exotic spices.', 17.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 11, 'lawrenceville'),
  ('vegetarian-rice-and-biryani', 'Gongura Biryani (Paneer)', 'Tangy and aromatic Gongura Biryani with succulent paneer.', 17.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 12, 'lawrenceville'),
  ('vegetarian-rice-and-biryani', 'Veg Keema Biryani', 'Spiced minced vegetables and fragrant basmati rice — a vegetarian biryani delight.', 17.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 13, 'lawrenceville'),
  ('vegetarian-rice-and-biryani', 'Paneer Keema Biryani', 'Fragrant basmati rice with succulent paneer and aromatic spices, cooked to perfection.', 17.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 14, 'lawrenceville'),
  ('non-veg-biryani', 'Egg Biryani', 'Fragrant basmati rice and delicate spices with perfectly boiled eggs.', 16.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 1, 'lawrenceville'),
  ('non-veg-biryani', 'Chicken Dum Biryani', 'Tender chicken with fragrant basmati rice and aromatic spices, slow-cooked to perfection.', 17.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 2, 'lawrenceville'),
  ('non-veg-biryani', 'Ulavacharu Chicken Dum Biryani', 'Tender chicken in Ulavacharu gravy, layered with fragrant basmati rice.', 18.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 3, 'lawrenceville'),
  ('non-veg-biryani', 'Vijayawada Chicken Biryani (Boneless)', 'Boneless chicken in aromatic spices, layered with fragrant basmati rice in Vijayawada style.', 19.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 4, 'lawrenceville'),
  ('non-veg-biryani', 'Gongura Chicken Biryani', 'Tender chicken with tangy gongura leaves, layered with aromatic basmati rice.', 18.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 5, 'lawrenceville'),
  ('non-veg-biryani', 'Chicken Biryani (Boneless)', 'Tender boneless chicken with fragrant basmati rice, aromatic spices, and traditional biryani flavors.', 18.67, NULL, FALSE, FALSE, FALSE, NULL, 'active', 6, 'lawrenceville'),
  ('non-veg-biryani', 'Chicken Fry Piece Biryani (Bone-In)', 'Juicy bone-in chicken marinated, fried crispy, and layered with fragrant basmati rice.', 19.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 7, 'lawrenceville'),
  ('non-veg-biryani', 'Chicken Fry Piece Biryani (Boneless)', 'Tender boneless chicken in aromatic spices, fried to perfection and nestled in fragrant rice.', 20.75, NULL, FALSE, FALSE, FALSE, NULL, 'active', 8, 'lawrenceville'),
  ('non-veg-biryani', 'DD Special Chicken Biryani (Bone-In)', 'Tender marinated bone-in chicken with fragrant basmati rice and aromatic spices.', 20.75, NULL, FALSE, FALSE, TRUE, NULL, 'active', 9, 'lawrenceville'),
  ('non-veg-biryani', 'DD Special Chicken Biryani (Boneless)', 'Tender boneless chicken with fragrant basmati rice and aromatic DD special spices.', 21.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 10, 'lawrenceville'),
  ('non-veg-biryani', 'Chicken Keema Biryani', 'Tender chicken keema with fragrant basmati rice and aromatic spices.', 22.83, NULL, FALSE, FALSE, FALSE, NULL, 'active', 11, 'lawrenceville'),
  ('non-veg-biryani', 'DD SPL Natu Kodi Biryani', 'Tender marinated country chicken with fragrant basmati rice, aromatic spices, and fresh herbs.', 25.95, NULL, FALSE, FALSE, TRUE, NULL, 'active', 12, 'lawrenceville'),
  ('non-veg-biryani', 'Mutton Dum Biryani', 'Tender mutton in aromatic spices, layered with fragrant basmati rice — slow-cooked to perfection.', 20.75, NULL, FALSE, FALSE, FALSE, NULL, 'active', 13, 'lawrenceville'),
  ('non-veg-biryani', 'Gongura Mutton Biryani', 'Tender mutton in tangy gongura sauce, layered with fragrant basmati rice.', 21.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 14, 'lawrenceville'),
  ('non-veg-biryani', 'Ulavacharu Mutton Dum Biryani', 'Tender mutton in flavorful ulavacharu sauce, layered with fragrant basmati rice.', 21.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 15, 'lawrenceville'),
  ('non-veg-biryani', 'Goat Kheema Biryani', 'Rich and aromatic goat meat with fragrant spices layered with perfectly cooked basmati rice.', 24.91, NULL, FALSE, FALSE, FALSE, NULL, 'active', 16, 'lawrenceville'),
  ('non-veg-biryani', 'DD Spl Nalli Gosht Biryani', 'Succulent lamb shank and aromatic spices layered with fluffy basmati rice.', 30.11, NULL, FALSE, FALSE, TRUE, NULL, 'active', 17, 'lawrenceville'),
  ('non-veg-biryani', 'Mamsam Roast Biryani (Bone-In)', 'Tender bone-in mutton in aromatic spices, layered with fragrant basmati rice.', 21.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 18, 'lawrenceville'),
  ('non-veg-biryani', 'Mamsam Roast Biryani (Boneless)', 'Tender boneless lamb in aromatic spices, layered with fragrant basmati rice.', 22.83, NULL, FALSE, FALSE, FALSE, NULL, 'active', 19, 'lawrenceville'),
  ('non-veg-biryani', 'Fish Biryani', 'Tender fish with fragrant basmati rice, aromatic spices, and herbs.', 20.75, NULL, FALSE, FALSE, FALSE, NULL, 'active', 20, 'lawrenceville'),
  ('non-veg-biryani', 'Shrimp Fry Biryani', 'Succulent shrimp and aromatic spices layered with fragrant basmati rice.', 20.75, NULL, FALSE, FALSE, FALSE, NULL, 'active', 21, 'lawrenceville'),
  ('non-veg-biryani', 'Mutton Fry Piece Biryani (Bone-In)', 'Tender bone-in mutton pieces with aromatic spices, layered with fragrant basmati rice.', 20.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 22, 'lawrenceville'),
  ('non-veg-biryani', 'Mutton Fry Piece Biryani (Boneless)', 'Tender boneless mutton in aromatic spices, layered with fragrant basmati rice.', 22.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 23, 'lawrenceville'),
  ('non-veg-biryani', 'Mutton Keema Biryani', 'Tender mutton keema and aromatic spices layered with basmati rice — hearty and full-bodied.', 24.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 24, 'lawrenceville'),
  ('dd-special-mandi', 'Veg Keema Mandi (Single)', NULL, 27.03, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'lawrenceville'),
  ('dd-special-mandi', 'Veg Keema Mandi (Half)', NULL, 44.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'lawrenceville'),
  ('dd-special-mandi', 'Veg Keema Mandi (Full)', NULL, 69.67, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'lawrenceville'),
  ('dd-special-mandi', 'Gutti Vankaya Mandi (Single)', NULL, 27.03, NULL, TRUE, FALSE, FALSE, NULL, 'active', 4, 'lawrenceville'),
  ('dd-special-mandi', 'Gutti Vankaya Mandi (Half)', NULL, 44.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 5, 'lawrenceville'),
  ('dd-special-mandi', 'Gutti Vankaya Mandi (Full)', NULL, 69.67, NULL, TRUE, FALSE, FALSE, NULL, 'active', 6, 'lawrenceville'),
  ('dd-special-mandi', 'Paneer Mandi (Single)', NULL, 27.03, NULL, TRUE, FALSE, FALSE, NULL, 'active', 7, 'lawrenceville'),
  ('dd-special-mandi', 'Paneer Mandi (Half)', NULL, 44.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 8, 'lawrenceville'),
  ('dd-special-mandi', 'Paneer Mandi (Full)', NULL, 69.67, NULL, TRUE, FALSE, FALSE, NULL, 'active', 9, 'lawrenceville'),
  ('dd-special-mandi', 'Egg Mandi (Single)', NULL, 27.03, NULL, FALSE, FALSE, FALSE, NULL, 'active', 10, 'lawrenceville'),
  ('dd-special-mandi', 'Egg Mandi (Half)', NULL, 44.83, NULL, FALSE, FALSE, FALSE, NULL, 'active', 11, 'lawrenceville'),
  ('dd-special-mandi', 'Egg Mandi (Full)', NULL, 68.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 12, 'lawrenceville'),
  ('dd-special-mandi', 'Chicken Mandi (Single)', NULL, 27.03, NULL, FALSE, FALSE, FALSE, NULL, 'active', 13, 'lawrenceville'),
  ('dd-special-mandi', 'Chicken Mandi (Half)', NULL, 47.83, NULL, FALSE, FALSE, FALSE, NULL, 'active', 14, 'lawrenceville'),
  ('dd-special-mandi', 'Chicken Mandi (Full)', NULL, 79.03, NULL, FALSE, FALSE, FALSE, NULL, 'active', 15, 'lawrenceville'),
  ('dd-special-mandi', 'NatuKodi Mandi (Single)', NULL, 27.03, NULL, FALSE, FALSE, FALSE, NULL, 'active', 16, 'lawrenceville'),
  ('dd-special-mandi', 'NatuKodi Mandi (Half)', NULL, 47.83, NULL, FALSE, FALSE, FALSE, NULL, 'active', 17, 'lawrenceville'),
  ('dd-special-mandi', 'NatuKodi Mandi (Full)', NULL, 84.23, NULL, FALSE, FALSE, FALSE, NULL, 'active', 18, 'lawrenceville'),
  ('dd-special-mandi', 'Goat Mandi (Single)', NULL, 27.03, NULL, FALSE, FALSE, FALSE, NULL, 'active', 19, 'lawrenceville'),
  ('dd-special-mandi', 'Goat Mandi (Half)', NULL, 47.83, NULL, FALSE, FALSE, FALSE, NULL, 'active', 20, 'lawrenceville'),
  ('dd-special-mandi', 'Goat Mandi (Full)', NULL, 84.23, NULL, FALSE, FALSE, FALSE, NULL, 'active', 21, 'lawrenceville'),
  ('dd-special-mandi', 'Fish Mandi (Single)', NULL, 27.03, NULL, FALSE, FALSE, FALSE, NULL, 'active', 22, 'lawrenceville'),
  ('dd-special-mandi', 'Fish Mandi (Half)', NULL, 47.83, NULL, FALSE, FALSE, FALSE, NULL, 'active', 23, 'lawrenceville'),
  ('dd-special-mandi', 'Fish Mandi (Full)', NULL, 84.23, NULL, FALSE, FALSE, FALSE, NULL, 'active', 24, 'lawrenceville'),
  ('dd-special-mandi', 'DD Special Nalli Gosht Mandi (Single)', NULL, 27.03, NULL, FALSE, FALSE, TRUE, NULL, 'active', 25, 'lawrenceville'),
  ('dd-special-mandi', 'DD Special Nalli Gosht Mandi (Half)', NULL, 58.23, NULL, FALSE, FALSE, TRUE, NULL, 'active', 26, 'lawrenceville'),
  ('dd-special-mandi', 'DD Special Nalli Gosht Mandi (Full)', NULL, 94.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 27, 'lawrenceville'),
  ('dd-special-mandi', 'Shrimp Mandi (Single)', NULL, 27.03, NULL, FALSE, FALSE, FALSE, NULL, 'active', 28, 'lawrenceville'),
  ('dd-special-mandi', 'Shrimp Mandi (Half)', NULL, 47.83, NULL, FALSE, FALSE, FALSE, NULL, 'active', 29, 'lawrenceville'),
  ('dd-special-mandi', 'Shrimp Mandi (Full)', NULL, 94.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 30, 'lawrenceville'),
  ('dd-special-mandi', 'Mixed Full Mandi (Chicken/Mutton)', NULL, 89.43, NULL, FALSE, FALSE, FALSE, NULL, 'active', 31, 'lawrenceville'),
  ('dd-special-mandi', 'SeaFood Mandi (Fish/Shrimp)', NULL, 94.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 32, 'lawrenceville'),
  ('dd-special-mandi', 'Extra Mandi Rice', NULL, 14.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 33, 'lawrenceville'),
  ('dd-specials', 'Goat Haleem', 'Tender goat blended with wheat, lentils, and aromatic spices slow-cooked to perfection. Rich, creamy Hyderabadi flavor.', 19.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 1, 'lawrenceville'),
  ('dd-specials', 'Boti Fry', 'Tender cubes of marinated boti, expertly fried to perfection with a tantalizing blend of spices.', 18.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'lawrenceville'),
  ('dd-specials', 'DD Chef''s Special Tawa Fish (Bone-In)', 'Succulent bone-in fish grilled with Chef''s signature masala — maximum taste and aroma.', 21.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 3, 'lawrenceville'),
  ('dd-specials', 'DD Chef''s Special Tawa Fish (Boneless)', 'Succulent boneless fish expertly seasoned and grilled on a traditional tawa with harmonious spices.', 22.83, NULL, FALSE, FALSE, TRUE, NULL, 'active', 4, 'lawrenceville'),
  ('dd-specials', 'Nalli Gosht Roast', 'Tender lamb shank slow-roasted in a flavorful blend of aromatic spices — melt-in-your-mouth.', 22.83, NULL, FALSE, FALSE, FALSE, NULL, 'active', 5, 'lawrenceville'),
  ('dd-specials', 'DD SPL Potlam Biryani', 'Fragrant aromatic spices, tender meat, and basmati rice cooked to perfection. Savor in every bite.', 25.95, NULL, TRUE, FALSE, TRUE, NULL, 'active', 6, 'lawrenceville'),
  ('dd-family-packs', 'Veg Biryani Family Pack', 'Aromatic basmati rice cooked with fresh vegetables, mint, and traditional spices.', 42.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'lawrenceville'),
  ('dd-family-packs', 'Egg Biryani Family Pack', 'Fluffy basmati rice layered with spiced boiled eggs and aromatic masala.', 43.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 2, 'lawrenceville'),
  ('dd-family-packs', 'Paneer Biryani Family Pack', 'Soft paneer cubes cooked in fragrant biryani masala and layered with saffron rice.', 47.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'lawrenceville'),
  ('dd-family-packs', 'Chicken Dum Biryani Family Pack', 'Classic Hyderabadi dum biryani — aromatic basmati rice layered with tender chicken.', 47.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 4, 'lawrenceville'),
  ('dd-family-packs', 'Ulavacharu Chicken Dum Biryani Family Pack', 'Tender chicken layered with biryani rice and simmered in authentic ulavacharu gravy.', 52.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 5, 'lawrenceville'),
  ('dd-family-packs', 'Vijayawada Boneless Biryani Family Pack', 'A fiery South Indian special with boneless chicken cooked in bold masala.', 52.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 6, 'lawrenceville'),
  ('dd-family-packs', 'DD SPL Chicken Biryani Family Pack', 'Our signature Desi Dhamaka special — juicy chicken, aromatic rice, and secret spices.', 52.99, NULL, FALSE, FALSE, TRUE, NULL, 'active', 7, 'lawrenceville'),
  ('dd-family-packs', 'Ulavacharu Chicken Boneless Biryani Family Pack', 'Boneless chicken cooked in rich horse gram (ulavacharu) gravy and layered with biryani rice.', 52.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 8, 'lawrenceville'),
  ('dd-family-packs', 'Ulavacharu Goat Dum Biryani Family Pack', 'Slow-cooked goat meat infused with earthy ulavacharu flavors — a rich Andhra-style biryani.', 60.27, NULL, FALSE, FALSE, FALSE, NULL, 'active', 9, 'lawrenceville'),
  ('dd-family-packs', 'Goat Dum Biryani Family Pack', 'Traditional Hyderabadi-style dum biryani with tender goat meat and fragrant basmati rice.', 58.19, NULL, FALSE, FALSE, FALSE, NULL, 'active', 10, 'lawrenceville'),
  ('dd-family-packs', 'Shrimp Biryani Family Pack', 'Succulent shrimp simmered in spiced biryani masala and layered with long-grain rice.', 58.19, NULL, FALSE, FALSE, FALSE, NULL, 'active', 11, 'lawrenceville'),
  ('dd-family-packs', 'Chicken Fry Piece Biryani Bone-In Family Pack', 'Aromatic basmati rice layered with chicken fry pieces — a true Desi Dhamaka signature.', 48.83, NULL, FALSE, FALSE, FALSE, NULL, 'active', 12, 'lawrenceville'),
  ('dd-family-packs', 'Chicken Fry Piece Biryani Boneless Family Pack', 'Tender boneless chicken fry blended with aromatic biryani rice — every bite a burst of spice.', 56, NULL, FALSE, FALSE, FALSE, NULL, 'active', 13, 'lawrenceville'),
  ('dd-family-packs', 'Mutton Fry Piece Biryani Bone-In Family Pack', 'Tender mutton pieces fried and mixed with spiced rice — rich, flavorful, and indulgent.', 60.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 14, 'lawrenceville'),
  ('dd-family-packs', 'Mutton Fry Piece Biryani Boneless Family Pack', 'Soft boneless mutton cooked in rich spices and blended with fragrant biryani rice.', 65.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 15, 'lawrenceville'),
  ('indo-chinese', 'Veg Noodles', 'Soft noodles tossed with colorful vegetables and house-made sauces — light, flavorful, and satisfying.', 11.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'lawrenceville'),
  ('indo-chinese', 'Egg Noodles', 'Stir-fried noodles with scrambled egg, soy, and veggies — perfect for egg lovers!', 11.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 2, 'lawrenceville'),
  ('indo-chinese', 'Chicken Noodles', 'Classic stir-fried noodles with tender chicken and crunchy veggies — comforting and full of taste.', 11.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 3, 'lawrenceville'),
  ('indo-chinese', 'Veg Fried Rice', 'Simple yet delicious — wok-tossed rice loaded with veggies and authentic Indo-Chinese flavors.', 12.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 4, 'lawrenceville'),
  ('indo-chinese', 'Egg Fried Rice', 'Fluffy rice blended with scrambled eggs, veggies, and spices — a delicious quick meal.', 12.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 5, 'lawrenceville'),
  ('indo-chinese', 'Chicken Fried Rice', 'Aromatic rice wok-tossed with juicy chicken, egg, and veggies — the ultimate comfort meal.', 12.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 6, 'lawrenceville'),
  ('indo-chinese', 'Veg Schezwan Fried Rice', 'Wok-tossed rice infused with chili-garlic Schezwan sauce and crunchy vegetables.', 13.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 7, 'lawrenceville'),
  ('indo-chinese', 'Egg Schezwan Fried Rice', 'Egg fried rice meets Schezwan spice — bold, saucy, and unforgettable!', 13.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 8, 'lawrenceville'),
  ('indo-chinese', 'Chicken Schezwan Fried Rice', 'Spicy Schezwan rice bursting with flavors of garlic, chili, and tender chicken.', 13.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 9, 'lawrenceville'),
  ('indo-chinese', 'Schezwan Shrimp Fried Rice', 'Spicy, zesty rice with shrimp and Schezwan sauce — a fiery twist for seafood lovers.', 15.99, NULL, FALSE, FALSE, FALSE, 2, 'active', 10, 'lawrenceville'),
  ('indo-chinese', 'Shrimp Fried Rice', 'Juicy shrimp tossed with rice, soy, and aromatic spices — ocean-fresh goodness in every bite.', 15.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 11, 'lawrenceville'),
  ('indo-chinese', 'Street Food Fried Rice', 'Inspired by Indian street flavors — smoky, spicy, and irresistibly tasty in every bite!', 15.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 12, 'lawrenceville'),
  ('indo-chinese', 'Chicken Hakka Noodles', 'Stir-fried noodles tossed with succulent chicken, veggies, and signature Indo-Chinese flavors.', 13.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 13, 'lawrenceville'),
  ('indo-chinese', 'Veg Hakka Noodles', 'Stir-fried noodles tossed with crunchy veggies and Indo-Chinese seasonings for a tasty, street-style treat.', 11.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 14, 'lawrenceville'),
  ('indo-chinese', 'Egg Hakka Noodles', 'Stir-fried noodles tossed with fluffy eggs, veggies, and flavorful Indo-Chinese seasoning.', 12.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 15, 'lawrenceville'),
  ('snacks', 'Roasted Peanut Masala', 'Crunchy roasted peanuts tossed in a flavorful masala blend — perfect for crunchy cravings.', 12.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'lawrenceville'),
  ('snacks', 'Samosa', 'Crispy golden pastries stuffed with spiced potatoes, peas, and aromatic herbs.', 12.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'lawrenceville'),
  ('snacks', 'Cut Mirchi', 'Spicy green chilies stuffed with spices and herbs, deep-fried crispy — fiery and addictive.', 11.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 3, 'lawrenceville'),
  ('snacks', 'Mirchi Bajji', 'Crispy and spicy fresh green chilies in flavorful batter, fried golden. A tantalizing Indian snack.', 12.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 4, 'lawrenceville'),
  ('snacks', 'Stuffed Mirchi', 'Spicy green chilies stuffed with flavorful potatoes and spices, fried to crispy perfection.', 12.99, NULL, TRUE, FALSE, FALSE, 2, 'active', 5, 'lawrenceville'),
  ('snacks', 'Bandi Punugulu', 'Crispy outside, soft inside — savory fritters from lentil batter and spices. Perfect for sharing.', 12.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 6, 'lawrenceville'),
  ('snacks', 'Kaju Fry', 'Crispy cashews in a flavorful blend of spices — satisfying crunch with every bite.', 15.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 7, 'lawrenceville'),
  ('snacks', 'Egg Bonda (3 Pcs)', 'Crispy on the outside, soft inside — three perfectly spiced and fried egg fritters.', 14.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 8, 'lawrenceville'),
  ('snacks', 'Boiled Peanuts Masala', 'Bold flavors of perfectly boiled peanuts coated in a tantalizing blend of spices.', 12.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 9, 'lawrenceville'),
  ('snacks', 'Malai Bun', 'Soft, pillowy bun filled with creamy, rich malai (clotted cream) — a decadent snack.', 6, NULL, TRUE, FALSE, FALSE, NULL, 'active', 10, 'lawrenceville'),
  ('snacks', 'Plain Bun', 'Freshly baked plain bun — light and fluffy, perfect for any time of day.', 6, NULL, TRUE, FALSE, FALSE, NULL, 'active', 11, 'lawrenceville'),
  ('chai-and-coffee', 'Masala Chai', 'Aromatic blend of black tea, warm spices, and creamy milk. Brewed to perfection — pure bliss.', 3.07, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'lawrenceville'),
  ('chai-and-coffee', 'Irani Chai', 'Rich and aromatic authentic Irani Chai — premium tea leaves and warm spices, traditionally brewed.', 4.11, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'lawrenceville'),
  ('chai-and-coffee', 'Desi Chai', 'Comforting fragrant blend of black tea, aromatic spices, and creamy milk. Piping hot.', 3.07, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'lawrenceville'),
  ('chai-and-coffee', 'Instant Coffee (Bru)', 'Rich aroma and bold flavor of Bru Instant Coffee — a satisfying pick-me-up anytime.', 4.11, NULL, TRUE, FALSE, FALSE, NULL, 'active', 4, 'lawrenceville'),
  ('chai-and-coffee', 'DD SPL Filter Coffee', 'Rich and aromatic South Indian specialty filter coffee — freshly ground beans and steamed milk.', 5.99, NULL, TRUE, FALSE, TRUE, NULL, 'active', 5, 'lawrenceville'),
  ('soft-drinks', 'Can Drinks', 'Assorted canned sodas.', 2.07, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'lawrenceville'),
  ('soft-drinks', 'Butter Milk', 'Creamy and refreshing buttermilk.', 5.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'lawrenceville'),
  ('soft-drinks', 'Mango Lassi', 'Refreshing blend of ripe mangoes and creamy yogurt.', 6.23, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'lawrenceville'),
  ('soft-drinks', 'Sweet Lassi', 'Traditional Indian yogurt drink with a touch of cardamom.', 5.19, NULL, TRUE, FALSE, FALSE, NULL, 'active', 4, 'lawrenceville'),
  ('soft-drinks', 'Salt Lassi', 'Refreshing tangy yogurt drink with a hint of salt.', 5.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 5, 'lawrenceville'),
  ('soft-drinks', 'Fresh Lemon Soda', 'Made with freshly squeezed lemons — a burst of citrusy delight.', 6.23, NULL, TRUE, FALSE, FALSE, NULL, 'active', 6, 'lawrenceville'),
  ('soft-drinks', 'Goli Soda', 'Nostalgic refreshing carbonated beverage bursting with fizz.', 4.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 7, 'lawrenceville'),
  ('soft-drinks', 'Thums Up – Can', 'Bold and refreshing Thums Up.', 2.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 8, 'lawrenceville'),
  ('soft-drinks', 'Topo Chico', 'Effervescent sparkling water, imported from Mexico.', 4.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 9, 'lawrenceville'),
  ('soft-drinks', 'Topo Chico – Can', 'Refreshing Topo Chico sparkling water in a can.', 3.11, NULL, TRUE, FALSE, FALSE, NULL, 'active', 10, 'lawrenceville'),
  ('soft-drinks', 'Poland Spring Water Bottle', 'Fresh, clean water to keep you cool and refreshed.', 0.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 11, 'lawrenceville'),
  ('soft-drinks', 'Coke – Can', 'Ice-cold Coca-Cola in a convenient can.', 2.07, NULL, TRUE, FALSE, FALSE, NULL, 'active', 12, 'lawrenceville'),
  ('soft-drinks', 'Diet Coke – Can', 'Crisp, refreshing Diet Coke.', 2.07, NULL, TRUE, FALSE, FALSE, NULL, 'active', 13, 'lawrenceville'),
  ('soft-drinks', 'Diet Coke – Bottle', 'Crisp, refreshing Diet Coke in a bottle.', 4.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 14, 'lawrenceville'),
  ('soft-drinks', 'Zero Coke – Can', 'The bold flavor you love with zero sugar.', 2.07, NULL, TRUE, FALSE, FALSE, NULL, 'active', 15, 'lawrenceville'),
  ('soft-drinks', 'Zero Coke – Bottle', 'Bold Coke flavor with zero sugar, in a bottle.', 4.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 16, 'lawrenceville'),
  ('soft-drinks', 'Sprite Can', 'Crisp, clean lemon-lime flavor.', 2.07, NULL, TRUE, FALSE, FALSE, NULL, 'active', 17, 'lawrenceville'),
  ('soft-drinks', 'Sprite Bottle', 'Refreshing Sprite lemon-lime flavor in a bottle.', 4.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 18, 'lawrenceville'),
  ('soft-drinks', 'Ginger Ale Can', 'Light and refreshing ginger ale.', 2.07, NULL, TRUE, FALSE, FALSE, NULL, 'active', 19, 'lawrenceville'),
  ('soft-drinks', 'Ginger Ale Bottle', 'Light and refreshing ginger ale in a bottle.', 4.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 20, 'lawrenceville'),
  ('soft-drinks', 'Limca Can', 'Refreshing bubbly Limca — lemon and lime blend.', 2.69, NULL, TRUE, FALSE, FALSE, NULL, 'active', 21, 'lawrenceville'),
  ('soft-drinks', 'Limca', 'Refreshing bubbly Limca soda.', 3.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 22, 'lawrenceville'),
  ('soft-drinks', 'Canada Dry Can', 'Light and refreshing ginger ale.', 2.07, NULL, TRUE, FALSE, FALSE, NULL, 'active', 23, 'lawrenceville'),
  ('soft-drinks', 'Canada Dry', 'Canada Dry ginger ale — light and crisp.', 3.11, NULL, TRUE, FALSE, FALSE, NULL, 'active', 24, 'lawrenceville'),
  ('soft-drinks', 'Mexican Coke', 'Made with real cane sugar.', 5.19, NULL, TRUE, FALSE, FALSE, NULL, 'active', 25, 'lawrenceville'),
  ('soft-drinks', 'Coke – Mexican Bottle (20oz)', 'Classic Mexican Coke in a 20oz bottle.', 4.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 26, 'lawrenceville'),
  ('soft-drinks', 'Mexican Fanta', 'Refreshing Mexican Fanta made with real cane sugar.', 5.19, NULL, TRUE, FALSE, FALSE, NULL, 'active', 27, 'lawrenceville'),
  ('soft-drinks', 'Mexican Sprite', 'Sparkling fusion of crisp citrusy flavors.', 5.19, NULL, TRUE, FALSE, FALSE, NULL, 'active', 28, 'lawrenceville'),
  ('soft-drinks', 'Smart Water', 'Crisp hydration with an electrolyte boost.', 4.15, NULL, TRUE, FALSE, FALSE, NULL, 'active', 29, 'lawrenceville'),
  ('kids-menu', 'French Fries', 'Crispy and golden French fries, perfectly seasoned and served hot — a classic kid favorite.', 10.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'lawrenceville'),
  ('kids-menu', 'Chicken Nuggets', 'Crispy golden-brown chicken nuggets served with savory dipping sauce. Perfectly bite-sized.', 12.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 2, 'lawrenceville'),
  ('kids-menu', 'DD Mini Kulcha', 'Miniature kulchas stuffed with spiced potatoes, onions, and herbs, baked golden — made for little ones.', 14.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'lawrenceville'),
  ('desserts', 'Ice Cream', 'Creamy scoops of rich vanilla ice cream — the perfect indulgence to end your meal.', 7.23, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'lawrenceville'),
  ('desserts', 'Gulab Jamun', 'Decadent soft syrup-soaked Indian sweet dumplings, served warm.', 7.23, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'lawrenceville'),
  ('desserts', 'Rasmalai', 'Soft paneer cheese soaked in saffron-infused milk, garnished with chopped pistachios.', 7.23, NULL, TRUE, FALSE, FALSE, NULL, 'active', 3, 'lawrenceville'),
  ('desserts', 'Carrot Halwa', 'Rich and decadent grated carrots in ghee, sugar, and aromatic spices. Garnished with crushed nuts.', 8.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 4, 'lawrenceville'),
  ('desserts', 'Double Ka Meetha', 'Decadent Indian bread pudding soaked in saffron-infused syrup, garnished with nuts and dried fruits.', 9.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 5, 'lawrenceville'),
  ('desserts', 'Sorakaya Halwa', 'Decadent bottle gourd halwa in milk, sugar, and aromatic cardamom.', 9.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 6, 'lawrenceville'),
  ('desserts', 'Gummadikaya Halwa', 'Luscious pumpkin halwa in ghee, sugar, and aromatic spices — rich, melt-in-your-mouth.', 9.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 7, 'lawrenceville'),
  ('desserts', 'DD Special Sweet', 'Chef''s special house dessert — a sweet surprise worth saving room for.', 13.47, NULL, TRUE, FALSE, TRUE, NULL, 'active', 8, 'lawrenceville'),
  ('desserts', 'Beetroot Halwa', 'Decadent grated beetroots simmered in rich milk, ghee, and sugar. Garnished with nuts.', 9.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 9, 'lawrenceville'),
  ('desserts', 'Ice Cream Gulab Jamun', 'Creamy ice cream with warm, syrup-soaked Gulab Jamun — a perfect balance of flavors.', 9.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 10, 'lawrenceville'),
  ('desserts', 'Sweet Paan', 'Traditional Indian dessert with betel leaves, gulkand, fennel seeds, and more. A perfect ending.', 3.59, NULL, TRUE, FALSE, FALSE, NULL, 'active', 11, 'lawrenceville'),
  ('thali', 'Veg Thali', 'A colorful assortment of seasonal vegetables, aromatic spices, lentils, and fluffy basmati rice. A symphony of flavors.', 21.99, NULL, TRUE, FALSE, FALSE, NULL, 'active', 1, 'lawrenceville'),
  ('thali', 'Non Veg Thali', 'A delectable selection of tender meats, aromatic spices, and flavorful accompaniments.', 23.87, NULL, TRUE, FALSE, FALSE, NULL, 'active', 2, 'lawrenceville'),
  ('thali', 'Chicken Cooker Pulav', 'Tender chicken with fragrant basmati rice and a blend of aromatic spices.', 90.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 3, 'lawrenceville'),
  ('thali', 'Mutton Cooker Pulav', 'Tender mutton slow-cooked with aromatic spices, mixed with fragrant basmati rice.', 100.99, NULL, FALSE, FALSE, FALSE, NULL, 'active', 4, 'lawrenceville')
) AS v(cat_slug, name, description, price, image, veg, popular, chef_special, spice_level, status, display_order, location_id)
JOIN cat c ON c.slug = v.cat_slug
WHERE NOT EXISTS (
  SELECT 1 FROM public.menu_items mi
  JOIN public.menu_categories mc ON mc.id = mi.category_id
  WHERE mc.location_id = 'lawrenceville' AND mc.slug = v.cat_slug AND mi.name = v.name
);

COMMIT;
